### ISSUE TITLE
the tv shows don't load, its always asking for VLC. and I don't know how to operate it (the movies do work though) 

### ISSUE THREAD

**Issue by fawziyakx** [popcorntime/popcorntime#1012]
Operating System Version:

Popcorn Time Version:

Download date:

#### Expected Behaviour

...

#### Actual Behaviour

...

#### Steps to reproduce the behaviour

1. ...
2. ...
3. ...

**Comment by dseddah** [comment]
Same here
Operating System Version:

OS X 10.14.5

Popcorn Time Version:

3.10 
Download date:

June 8, 2019 (5 mn ago)

Expected Behaviour

content   should be displayed continuously

Actual Behaviour

After a while (3mn or so), the video stops playing and  an error message pops up :
"the video encountered an issue. Please try an external player like VLC to view this content"

...

Steps to reproduce the behaviour

1) Go to series
2) pick Game of Thrones (any first seasons episode), like S3E04 for example. It will crash right after the opening sequence.

...
...

**Comment by kiriles90** [comment]
@Persei08 not an actual issue, close please
