### ISSUE TITLE
Contribute Request

### ISSUE THREAD

**Issue by ettoreboy** [popcorntime/popcorntime#1056]
Hello,
I see that this repository is not recently active. Do you think there are some easy contribution or any issue labeled for a contributor beginner?

**Comment by Persei08** [comment]
Maybe those ones:

#898, #933, #897, #881

You probably know it, but be sure to base your work on the development branch.

Else look at issues created by users, but there are lot of useless ones which are just waste of time: 
- The ones already fixed (because too much people report issue for old 0.3.10 while dev is done on development branch)
- some network related issues (tab not loading, spinning loader, torrent staying on 'connecting')
- missing or wrong movie/episodes
- subtitles desync
- codecs related issues

**Comment by ettoreboy** [comment]
Thank you @Persei08,
I have a solution for #933 (similar to what it was proposed https://github.com/popcorn-official/popcorn-desktop/pull/971 but never merged).

Can I create a branch?

**Comment by Persei08** [comment]
>Can I create a branch?

hmm, what do you mean?  Submitting a new pull request ?

Hmm, If your fix have some improvements and you think is a bit better than #971 then submit it.
Else you should better comment on #971 to tell you've reviewed and approve his changes.

**Comment by ettoreboy** [comment]
Yes I am trying to submit a new PR by creating a new branch but I am not authorised to do so. 

I fix also the building issue #971 has. I think #971 should be closed once I get mine approved.

**Comment by Persei08** [comment]
You should fork PT repo then push the branch on your repo, and submit the PR from there

**Comment by ettoreboy** [comment]
I understand!
I created this and commented on a duplicated one that has been not merged, but it is needed to pass the build for the next one. So in order:
1. https://github.com/popcorn-official/popcorn-desktop/pull/1060
2. https://github.com/popcorn-official/popcorn-desktop/pull/1061

Thanks!
