### ISSUE TITLE
Seems Limited in Movies and TV Shows Need To Have Every Single Movie To Date 

### ISSUE THREAD

**Issue by vegeta45** [popcorntime/popcorntime#1079]
Operating System Version:
Windows 10

Popcorn Time Version:
3.10

Download date:
10/30/2019

#### Expected Behaviour

… some shows are missing episodes and there are limited shows and movies

#### Actual Behaviour

… some shows are missing episodes 

#### Steps to reproduce the behaviour

1. … need to have every movie and shows and cartoon shows to date ( even movies in theaters )
2. … missing episodes need to be fix
3. … need rotten tomatoes ratings

**Comment by Persei08** [comment]
I guess it will never happen for different reasons...  

American movies, European movies, Hindi movies, Hong-Kong movies, Japanese Movies, Korean movies,... this list is endless and we don't even talk about Tv shows.  

PT is focused on Movies and TV shows with international audience and get his magnet (torrent) links from yts.lt and eztv.io websites, and metadatas (synopsis, ratings, year, ...) from trakt.tv. And none of those sites have everything. Some episodes are missing because they aren't on eztv.io but also because with time passing, people stop to share old files too. That's another reason why it is also hard to find old seasons episodes.

Eventually could be possible to add some Hindi or other movies, but you have to find websites which can provide reliable magnet links for them and also for metadata... and then some contributors to write all the necessary code.

Movies in theaters, are released in bad quality (camrips with poor video and sound quality and even ads for gambling sites).  

Torrent releases in correct enough quality usually become available few days around their release on dvd/bluray/digital platforms.

**Comment by kiriles90** [comment]
@Persei08 not an actual Popcorn Time issue? close please
