### ISSUE TITLE
HTTPS support for the remote control feature

### ISSUE THREAD

**Issue by Alexandre-Nourissier** [popcorntime/popcorntime#108]
Operating System Version:
    Windows 10
Popcorn Time Version:
    0.3.9-0
Download date:
    2016/03/17 18:47

It's seems that the remote control feature only support the HTTP protocol (by default on the 8008 port).

![capture](https://cloud.githubusercontent.com/assets/10888984/13856319/ed61d89e-ec74-11e5-8cb1-2154190dc080.PNG)

Given the usage and nature of the app, I think that providing an HTTPS connection is a must in order to prevent personal information leakage in case of exploit of the HTTP implementation. 
We are in 2016, we must provide that capability, even if optional.

PS: Thanks for your hard work !

**Comment by Alexandre-Nourissier** [comment]
After investigation in the code, the rpc server is a butter-related feature.

**Comment by VitorVRS** [comment]
You dont https connection between remote and pct, since its a local server from the machine where is running pct and your phone.
Unless you dont trust in the machine running pct.

Plus if you really want this feature, each pct instance will need to have an certificate for it, so i think it doesnt worth.

**Comment by Alexandre-Nourissier** [comment]
Well, pro-users could use their own certificates from https://letsencrypt.org/. But it's only for encryption support after all, so yeah, overkill.
