### ISSUE TITLE
Add Options On The Butter Player

### ISSUE THREAD

**Issue by GKid94** [popcorntime/popcorntime#1086]
Add aspect ratio and crop options on the Butter player

**Comment by Persei08** [comment]
Stop spamming!

**Comment by GKid94** [comment]
How am I spamming

**Comment by Persei08** [comment]
I remember: https://github.com/popcorn-official/popcorn-desktop/issues?utf8=%E2%9C%93&q=is%3Aissue+aspect+ratio

You asked lot of times and a dev tagged your issue #263 with 'wontfix' tag and closed it.

**Comment by GKid94** [comment]
Well they still haven't added them and those issues are closed

**Comment by Persei08** [comment]
wontfix = Won't fix = Will not fix

You understand they don't want to add it, right ?

**Comment by GKid94** [comment]
Ok but I don't understand why not, maybe an explanation

**Comment by Persei08** [comment]
Because it isn't very useful to have it and maintain it. I don't know which videos you watch in PT but I can't remember any with bad aspect ratio. Also PT player is video.js player project so people have to spend time testing if possible when there are more important things to fix... And since bad aspect ratio are probably not common you can always use one of the supported external players.

**Comment by Persei08** [comment]
Also it's funny you ask for explanation when you can't even take the time to fill the issue template.

**Comment by GKid94** [comment]
Ok thx for the explanation
