### ISSUE TITLE
[request] BS Player as external player

### ISSUE THREAD

**Issue by GKid94** [popcorntime/popcorntime#1087]
Add an option to watch movies and series with the BS Player

**Comment by Persei08** [comment]
What BS stand for? :)

**Comment by Persei08** [comment]
Hi,

I removed my previous reply because it add nothing and was a bad joke in fact.

Have a look at [ext-player.js file](https://github.com/popcorn-official/popcorn-desktop/blob/development/src/app/lib/device/ext-player.js)

Lines 213-215, you have the folders path where PT should start to search for the executables, but executable path and other parameters arguments (fullscreen, subtitle, ...) should be defined before. Like what you can see for other players between lines 7 to 94.

Now, you have to find actual command line parameters of BSplayer and complete the arguments list with the appropriate ones.

**Comment by GKid94** [comment]
I don't know how to fix software, the BS Player option is just missing

**Comment by Persei08** [comment]
This isn't a issue, there is nothing to fix and the BS player option isn't missing...  you're asking for supporting another player.

What I need is the command-line (CLI) arguments for : 
- subtitles
- fullscreen
- stop
- pause

Can you provide them?

**Comment by GKid94** [comment]
Here there is a Butter, VLC and MPC option but no BS Player option

![342342](https://user-images.githubusercontent.com/18757054/68713700-ba7dce00-059e-11ea-8ad3-afde7a8ea9c8.jpg)

**Comment by Persei08** [comment]
You understand it isn't supported and you ask to support it, right ?

I don't even know why I suggested you to give me the CLI arguments, you just want us to waste time on insignificant details

**Comment by GKid94** [comment]
Why is it not supported

**Comment by Persei08** [comment]
Because else you will see it in the list

**Comment by GKid94** [comment]
But why can't you add the option to play movies and series with the BS Player, it has a VLC option

**Comment by Persei08** [comment]
I never said we can't. 
You understand every supported players were added one by one so PT can detect them and add them to the list of availlable external players, and then launch them to play the downloaded video?

I asked you to give us the BS player CLI arguments and you provided a screenshot showing a list of detected supported players.

**Comment by GKid94** [comment]
Ok how can I get the CLI arguments

**Comment by marcosnovaesq** [comment]
as in  http://forum.bsplayer.com/feature-requests-feedback-suggestions/2286-starting-bsplayer-command-line.html

is it what you asking?



 :? Did you have a look in BSPlayers "About box":

Command line:
bplay "my file.avi" ["my subtitles.txt"] [options]
or
bplay "my playlist.bsl" [options]
or
bplay "inifile.ini" [options]

File name must always be the first and subtitle file second
argument.
Options are:
-fs Start in full screen
-asx Start with x audio stream
x=1-> 1st audio stream
x=2-> 2nd audio stream
x=n-> n audio stream
x=0-> Semi's Directsound 3D
-stime=x Start movie at x seconds
-nsub Don't show subtitles even if subtitle file exists
-skin=s s=skin name
-lang=l l=language file without extension
-eend Exit when movie is finished
-pan Use Pan-scan
-res=WxHxD Start in specified resolution
W=width, H=height, D=color depth
Ex.: -res=1024x768x16
-ar=x:y Aspect ratio, Ex.: -ar=16:9


Ex.: bplay "my movie.avi" "my subtitles.txt" -fs
bplay "my movie.avi" "my subtitles.txt" -fs -as2
bplay "my movie.avi" "my subtitles.txt" -as3 -lang=English

**Comment by Persei08** [comment]
@marcosnovaesq  thx, I not sure those arguments are up to date. The post you link is from 2002, it's 17 year old and  it could have changed :/

Also, since @GKid94 like to ask new features like it just require us to snap our fingers, I think it could be great for him to do his part of the job and provide those arguments and a edited [ext-player.js file](https://github.com/popcorn-official/popcorn-desktop/blob/development/src/app/lib/device/ext-player.js) with the bsplayer entry (which I will provide detail to edit adequatly)

So @GKid94 tell me when you find the bsplayer CLI arguments for:

- subtitles
- fullscreen
- stop
- pause

Then I will tell you how to edit the file, so you can give me the ext-player.js file, then i will install a virtual machine to install your adware sponsored player and test if it works and eventually fix what I can to have it detected and working.

**Comment by GKid94** [comment]
@Persei08 Ok how do I find them

**Comment by Persei08** [comment]
@GKid94 You have to open command prompt and launch bsplayer in it  with argument /? or -h i guess. so it whould display the other arguments

**Comment by GKid94** [comment]
Doesn't work

![34534534](https://user-images.githubusercontent.com/18757054/69089825-f0143280-0a48-11ea-9335-e7a0bf9bbc08.jpg)

**Comment by Persei08** [comment]
Hi,
your path isn't good, you have an error with 'Program Files (x86)', you should put double quotes (") around because there are spaces in the folder name. Also you try to pass the argument to BSPlayer folder instead of bsplayer executable (which is in BSPlayer folder)

So the right command should be :

`C:\"Program Files (x86)"\Webteh\BSPlayer\bsplayer -h` or
`C:\"Program Files (x86)"\Webteh\BSPlayer\bsplayer /?`

But I have tested for you, and it return nothing. 

So after some times spend searching, I found they put a `cmdline.txt` file in `C:\"Program Files (x86)"\Webteh\BSPlayer\doc\` ::

```txt
Command line parameters
-----------------------

-fs		Start in fullscreen mode
-ar=W:H		Aspect ratio, ex.: -ar=16:9
-asx		Start with x audio stream
		x=1-> 1st audio stream
		x=2-> 2nd audio stream
		x=n-> n audio stream
-pan		Pan-scan mode
-nsub		Disable subtitles
-skin=SKIN	Start with specified skin, ex.:-skin=Base
-res=WxHxDxF	Startup resolution (W=width, H=height, D=color depth, F=Frequency), ex.: -res=800x600x32-80
-lang=		Specify language, ex:. -lang=English
-eend		Exit when movie is finished
-sdown		Shutdown when movie is finished
-stime=x	Start movie at x seconds
-deskmode	Start in desktop mode
-hide		Hide controls
```

So @GKid94, which arguments you think we should use for thoses:: 

 -subtitles ?
 -fullscreen ?
 -stop ?
 -pause ?

**Comment by GKid94** [comment]
Maybe this

1) -nsub		Disable subtitles
2) -fs		Start in fullscreen mode
3) -deskmode	Start in desktop mode
4) -deskmode	Start in desktop mode

**Comment by Persei08** [comment]
Not exactly.

There is no arguments to trigger stop and pause functions.
for fullscreen, `-fs` should works
for subtitles we will test later but if @marcosnovaesq CLI list is always good, it seem it need to be passed in second argument.

So, i've edited [ext-player.js](https://github.com/popcorn-official/popcorn-desktop/blob/1537575b4130ba603674a962f3f4ace6067e7be6/src/app/lib/device/ext-player.js#L93) to add the following code after line 93::

```js
        'BSPlayer': {
            type: 'bsplayer',
            switches: '',
            subswitch: '',
            fs: '-fs'
        }
```
It detect and launch BSplayer but it got an error and don't play the video. My virtual machine is insanely slow... i'm done for today. I'll do more tests later, but don't be in a hurry

**Comment by Persei08** [comment]
So, I'm testing this again.

Finally just this change are enough to watch the video in BSPlayer.

I have to do more test to check is subtitles are displayed too

**Comment by GKid94** [comment]
Great, keep working

**Comment by Persei08** [comment]
hmm, damn, was pretty sure i sent PR for this. Remind me, next week if I don't make the PR

**Comment by ado366** [comment]
Hi, 
I too would be very happy with this feature
Is there any way I can help to make this happen?

I tried appending the BS player code snippet in  ext-player.js but it doesn't seem to be working. Popcorn doesn't detect any external player after the modification.

**Comment by ado366** [comment]
Bump.
How can i help to get this done?

**Comment by kiriles90** [comment]
@Persei08 issue is fixed, close please

**Comment by Persei08** [comment]
![external-bsplayer-icon](https://user-images.githubusercontent.com/22459458/100445487-79733180-30ad-11eb-94ee-5038fb5b24a0.png)
![external-bsplayer-icon-orig](https://user-images.githubusercontent.com/22459458/100445488-7a0bc800-30ad-11eb-8a19-8411c5c4ca46.png)

**Comment by Persei08** [comment]
Finally done. Will be in next dev build
