### ISSUE TITLE
Butter Player Issues

### ISSUE THREAD

**Issue by GKid94** [popcorntime/popcorntime#1093]
Can't close the More videos popup when you pause the video, when you skip scenes on the video bar the player pauses the video instead of continuing to play, and you also can't see the upper YouTube video name and player buttons

![5435345](https://user-images.githubusercontent.com/18757054/69314041-6ffdf080-0c33-11ea-952a-90c70d05abec.jpg)

**Comment by Persei08** [comment]
Your description is misleading.

It happen on trailers videos because they are youtube videos displayed in butter player.
If you click the video or resume/play the video, the 'more videos' banner disappear.
When you skip scenes, it display the 'more videos' banner for not even a second.
The youtube video name, buttons and 'more videos' banner are IMO not necessary but I guess the youtube player add them.

But maybe someone should have a look at this some day. So I refer this issue to #898 since eventually it could be looked at, at the same time

**Comment by GKid94** [comment]
Ok but shouldn't you be able to close the More videos popup on the x button

**Comment by Persei08** [comment]
I think an event is added so when you click somewhere in the video, it toggle play/pause. 

Now butter player is just [videojs](https://videojs.com/) player with a custom skin. and apparently now youtube force the related videos, the youtube logo, the 'watch later' and 'share' buttons. Maybe there is a better way to integrate. But i think you can consider it is a low priority issue

**Comment by Persei08** [comment]
@GKid94 do you consider it fixed with 387 dev build?
