### ISSUE TITLE
Popcorntime keeps loading

### ISSUE THREAD

**Issue by SamRiskin23** [popcorntime/popcorntime#1095]
Operating System Version:
< Windows 10>

Popcorn Time Version:
<3.10>

Download date:
< 23th of November 2019 >

#### Expected Behaviour

...
I downloaded the app again because it doesn't show any movies/shows/... It keeps loading, but nothing happens
In my brother's pc everything works fine (also in Belgium, same Windows and same Popcorntime version. I don't use a VPN, but it worked before (without a VPN). 
I've tried all Popcorntime versions. I don't know what I have to do to make it work back again :(
![Knipsel](https://user-images.githubusercontent.com/15573068/69484344-71493c00-0e32-11ea-97a4-a4cd280fe832.JPG)

**Comment by Persei08** [comment]
Look like you can't reach the popcorn-api server.

Probably you're ISP is blocking the popcorn-api domain name.

Since they usually block domains by faking DNS entries, you can switch your DNS servers for cloudflare dns (1.0.0.1, 1.1.1.1) or google dns (8.8.8.8, 8.8.4.4) instead of your ISP ones.

Here a guide to change your DNS servers on different systems: https://www.howtogeek.com/167533/the-ultimate-guide-to-changing-your-dns-server/
