### ISSUE TITLE
add movie popcorn home screen

### ISSUE THREAD

**Issue by GlauberF** [popcorntime/popcorntime#1123]
**Operating System Version:**
Linux

**Feature**
I don't know if you have this option, but I didn't find it, do you have the possibility to add popcorn home screen movie?

Because I speak of Brazil, and the films / series presented are all in English, if you have a way to add a new film informing the magnetic link, it would be perfect.

**Comment by Persei08** [comment]
Not very sure if I understand well, but PT request content to [popcorn-api](https://github.com/popcorn-official/popcorn-api)

the popcorn-api scrap torrent websites (mainly YTS.mx and eztv.io) to get movies and episodes.

Introducing a feature to allow users to share their magnet links will create other problems (spams, fakes, bad quality, ...) that's why it is better to rely on websites where magnets links are already filtered/checked by websites teams.

But if someone want to do that, he can just do the website with an api which can be requested by PT
