### ISSUE TITLE
Trakt connection window flashes token and closes

### ISSUE THREAD

**Issue by smagnan** [popcorntime/popcorntime#1139]
Operating System Version:
Windows 10

Popcorn Time Version:
3.10.0

Download date:
21/2/2020

#### Expected Behaviour
connection to trakt account and token setup via app

#### Actual Behaviour & Steps to reproduce the behaviour
After clicking to connect to trakt:
- no issue connecting to trakt, then
- the new login token briefly flashes and the window closes right away
no login processed.

Screen capture:
[https://ibb.co/yqM0c2s](url)
![ezgif-5-35066ce04f27](https://user-images.githubusercontent.com/6959251/75103210-64142880-55ac-11ea-8aff-ec13a161124f.gif)

This issue seems to be a bit different from the one often reported online where the trakt token return fails. I do get a token but the window closes right away.

NOTE: I still can get the code by taking a video and getting the right frame, but once I go to https://trakt.tv/activate the code isn't valid anyway

**Comment by Persei08** [comment]
This was fixed in dev builds (ci.popcorntime.app/view/All/job/Popcorn-Time-Desktop/).

Now it works differently, PT provides a code, and open a browser page on https://trakt.tv/activate where users need to paste the code.

**Comment by smagnan** [comment]
Thank you! My bad I thought an auth fox was pushed on master already, but this is probably a different issue. I will try the dev build again (I imagine the website one is still master from the code I saw).
My only issue is that last time I tried the dev build (win 10 ×64), once installed the app wouldn't open. But when trying to uninstall it was saying "warning, app is running" even tho it didn't appear on the process list. Multiple installs/uninstall/db removed/restarts didn't fix the issue. Anyway, this is a different issue so I will close this one and try the dev version on my Linux instead, and master on Windows.

**Comment by Persei08** [comment]
Yes, the version on the main site is master branch. Normally if a dev builds is considered stable enough, it should be pushed on the on the main site and master branch be updated, but it didn't happened since long time.

Else, dev builds are hosted on ci.popcorntime.app, but some old versions are missing.

If you need just looking for a version working well enough, you should better have a look at [this reddit post](https://old.reddit.com/r/PopCornTime/comments/fa4hdz/latest_stable_dev_build/) for the moment
