### ISSUE TITLE
The  Wired season 4 missing

### ISSUE THREAD

**Issue by Nishant765** [popcorntime/popcorntime#1140]
Operating System Version:
 Windows 10

Popcorn Time Version:
Popcorn-Time 0.3.10

Download date:
2nd February 2019

#### Expected Behaviour
<Season 4 of Wired should be listed
...
 Actual Behaviour
The wired season 4 is completely missing
Please fix it.  All the other seasons are there.

**Comment by Persei08** [comment]
Hi,

I think you are talking about "The Wire" which have effectively season 4 missing.

There isn't people in background adding magnet links one by one all day long.
PT get magnet links (torrents) via an automatic process, by scrapping other torrent websites (usually EZTV for episodes). 
Here it seem it was from ETTV, but i'm not even sure if PT-api still index ETTV, but it is how it is.
Those singles episodes seem to  be always shared by at least 1 seeder and i guess that's why they still appear in PT.

But , since it's an old serie, you should better find a "complete season" torrent or magnet link and copy-paste it into PT window. It will ask you for which episode you want to watch, and you will have to do that for all season 4 episodes.

**Comment by ivan1986** [comment]
@Persei08 Many issues about missing episodes - maybe add disclaimer to new issue template?

**Comment by Nishant765** [comment]
@Persei08 Yeah sorry it was "The Wire" which I was talking about. Well thank you for the reply. Although many other episodes of Dark(Netflix) S1 are also missing. Is there any way that PT will add these episodes back in the future or will it be permanently like this? Cause getting torrent links for these rare and old tv shows are really hard, that's why many depend on PT for streaming these episodes cause of their awesome streaming and downloading service.

**Comment by Persei08** [comment]
@ivan1986 i don't have access to issue template settings

**Comment by Persei08** [comment]
@Nishant765 like i said PT automatically scrap episodes from eztv. and actually it will require to scrap other websites but alos to take into consideration that usually torrent users have habit to package all episodes of same season in a complete season torrent and stop sharing single episode torrents. But PT don't index those complete season torrent at the moment.
