### ISSUE TITLE
Why subtitles are always wrong?

### ISSUE THREAD

**Issue by marcobraghim** [popcorntime/popcorntime#1142]
Operating System Version:
Linux Debian 10

Popcorn Time Version:
0.3.10

Download date:
I cant remember

#### Expected Behaviour
When I start some movie the subtitle are load to pt_BR (brazilian portuguese) as right, but always with the wrong position, late or advanced, but NEVER in the right position, and more, even changing the position of subtitle it NEVER fits well. When I set with a scene, the next I have to set again... So the solution is to download from somewhere like opensubtitles and after a lot of try and frustration it works. The question is: Why the subtitle is always wrong? How can I at least, after find out someone which fits, set to be the default subtitle for pt_br for the next one who needs it?
...

#### Actual Behaviour
....
...

#### Steps to reproduce the behaviour

1. ...
2. ...
3. ...

**Comment by Persei08** [comment]
The subtitles are requested to opensubtitles api. If i'm not wrong, there is an algorithm which provides a score to each subtitles to find the supposed better one for each language. The scores are calculated using different criteria (I don't remember exactly but something like video filename, video fps, subtitles ratings, ...) .  But i think it works better with english subtitles because other languages have less subtitles alternatives.

So, you can increase of decrease offset with G or H keys as you already know, but sometimes after few seconds it desync again because there was some video framerate conversion at some point and the timing don't match.
(Check this [page to understand the difference between conform and interpolate conversion](https://toolstud.io/video/framerate.php).)
And sometimes the video have just diffrent cuts than the video used to make the subtitles.

Else you can try to find better subtitles and upload them on opensubtitles with the right filename, or you can edit and fix your downloaded subtitles (and then upload them on opensubtitles).

Under linux, when necessary, I try to [quickly fix subtitles with Gnome Subtitles](https://youtu.be/eUAhunOrG3w?t=82). In "Timings" > "Synchronize" menu, I can define some "sync points" around beginning, middle and end of video and eventually the final result is good enough to be uploaded on opensubtitles.

Last thing, the development branch now return multiple subtitles per languages.
The dev build 293 for linux have the multiple subtitles improvment and is stable enough if you disable "Activate update seeding" option to avoid random freeze. But since 293 is no longer on CI platform, I suggest you to look at this post: https://old.reddit.com/r/PopCornTime/comments/fa4hdz/latest_stable_dev_build/

BTW, I close the issue, because the dev branch return multiples subtitles and it require users to upload the good subtitles on opensubtitles and link them with the right filename.

**Comment by marcobraghim** [comment]
Thanks for your answer.

I think that could have a better way to determine which subtitle is better for a movie. **Native people should do it**, who else is better for this job?

But this should happen into popcorn too, why not? Because not ever the algoritm will find the best subtitles and after I found a perfect one, other people like me will have to make this research again...

You may agree with me that not ever the best rated subtitle into opensubtitles will be the best to the current version of the movie over popcorn, right? But when native people rate it into popcorn the doubts gone...

**Comment by marcobraghim** [comment]
I'm really thankful for popcorn, it's wonderful! But I can tell you for sure that this project would be really well accepted by people around the world if subtitles wasn't that big problem... There's a lot of people who give up after try to watch a movie over popcorn and get all this trouble with the subtitles. C'mon I can get along well with english, but even I gave up with popcorn some times because of this... =/ 

Sorry, I really don't want to be stupid or bother, but I really want this project to be bigger.

**Comment by Persei08** [comment]
@marcobraghim actually users can improve subtitles result by uploading the correct subtitles on opensubtitles and associating them with the right video filename.

**Comment by osrl** [comment]
adding a custom subtitle would be much easier I think

**Comment by marcobraghim** [comment]
> adding a custom subtitle would be much easier I think

The heart of matter is when I, as a native speaker of brasilian portuguese, finally find one subtitle that fits very well to the popcorn movie, I should have something to mark it as the best subtitle into popcorn in place of depends 100% of opensubtitles.org and its rating...

I think that people from a region where english is default language will never understand or care for real about who's not...
