### ISSUE TITLE
Philips Hue Entertainment SDK integration

### ISSUE THREAD

**Issue by leossmith** [popcorntime/popcorntime#1197]
#### Expected Behaviour
With Philips Hue Entertainment integration, Entertainment areas will be used by the player

Information can be found [here](https://developers.meethue.com/develop/hue-entertainment/philips-hue-entertainment-api/).

**Comment by Persei08** [comment]
What do you think can be done? for what kind of feature ?
Also, it will not really be useful to everyone... but, we 're just speaking for now.

The link ask me to login, but i'm bored to create an account just to access documentation. :/

**Comment by leossmith** [comment]
Well they way it works on Kodi is that when the app starts, it turns your "Entertainment zone" to low lights (called cinema lights). Then when the movie starts, all lights go off and they start changing colors based on what is displayed in the movie. When you pause, the lights go on again. 

The most important part is the changing of lights based on what is displayed. 

However, in the time passed since I first posted, Hue has a solution for this now, called philips hue gradient lighstrip and hue sync (although it costs roughly 500$)

**Comment by Persei08** [comment]
oh ok, I have yeelight rgb bubble. Some years ago, i was thinking it could be great to have something like that (a sort of philips ambilight effect), because i saw a youtube video of people doing it (with kodi and phillips hue I think). 

I ended wondering how to get the video frames and extract the main colors, but I never really dogged seriously into it.

Now, it seem we can use canvas to get frames ([link 1](https://stackoverflow.com/questions/43007634/javascript-how-to-extract-frame-from-video), [link 2](https://stackoverflow.com/questions/26748238/capture-frame-from-video-js-with-canvas)) and get average color ([link 3](https://stackoverflow.com/questions/2541481/get-average-color-of-image-via-javascript))

So I guess there is a way to do it, but now someone should spend some time experimenting.
 
If we can get the average colors of video for top, left, right sides every 250 or 500 ms. Half the job will be already done.


Someone want to play with that ? :D

**Comment by leossmith** [comment]
[This app](https://play.google.com/store/apps/details?id=huedynamiciap.android) does exactly that, using the camera of the device. Gets the image from camera, then using probably a matrix, extracts avg color from sides and top. Sadly, I have no idea about js, so I can't really jump in on this.
