### ISSUE TITLE
Enhancenent (language filter)

### ISSUE THREAD

**Issue by NessunoIM** [popcorntime/popcorntime#1207]
Can you add a filter so anyone can view the list of films only for a specific audio language or subtitle? For example a filter to view only films with Spanish subtitle... or films with French audio... or both!

**Comment by Persei08** [comment]
You should open this issue on [popcorn-api repo](https://github.com/popcorn-official/popcorn-api).
Because PT only request the api and display the results. so this is something to implement in popcorn-api first.
For audio, I think actually there is only english audio, but it is set arbitrary i guess based on the site language, for example [the movie Parasite](https://www.imdb.com/title/tt6751668/) is indexed from YTS with english language but this is false it is in korean in reality.

There was some idea at some point to have movies in different language but it was never done (or finish) eventually someday, but it's hard to tell.

For the subtitles the list is requested to opensubtitle when you load the movie details view, it isn't provided by the popcorn-api results.

**Comment by NessunoIM** [comment]
Ok, thanks.

Moved to:
 https://github.com/popcorn-official/popcorn-api/issues/132
