### ISSUE TITLE
Errors in Linux Ubuntu 19.10 Terminal

### ISSUE THREAD

**Issue by ghost** [popcorntime/popcorntime#1220]
Operating System Version:
Linux Ubuntu 19.10 64 bit

Popcorn Time Version:
4.1 latest

Download date:
25 March 2020 11:50am

#### Expected Behaviour
No Errors in Terminal
...

#### Actual Behaviour
Errors in Terminal 
1 . InitializeSandbox() called with multiple threads in process gpu-process.
2 .  os.tmpDir() is deprecated. Use os.tmpdir() instead.
3 .  Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
...

#### Steps to reproduce the behaviour
1 . Open the Folder
2 . open Terminal
3 . type : ./Popcorn-Time
4 . Check the terminal window
![Check_error](https://user-images.githubusercontent.com/29015880/77507953-80e39a80-6e8f-11ea-83e0-06dd6d5eba11.png)

**Comment by Persei08** [comment]
Those are warnings and aren't bugging the app as far as i know.

Testing that with dev build 439, 

`os.tmpDir` warning now longer triggered despite being used in `main_window.js` :/

~~Buffer() used in lot of dependencies:~~
~~- adm-zip ([here for example](https://github.com/cthackers/adm-zip/blob/master/zipFile.js#L357))~~
~~- agent-base~~
~~- airplay-protocol~~
~~- async~~
~~- async-limiter~~
~~- atob~~
~~- bencode~~
~~- bittorent-dht~~
~~- bittorent-protocol~~
~~- bittorent-tracker~~
~~- bonjour~~
~~- ... and the list is way too long~~

~~So, I close this, because warnings aren't too important here and this will always appear until dependencies no longer use it~~.



Edit: 
oops I was wrong warning aren't triggered for node_modules by default.
but this Buffer() warning, I can't find it in code.

But I still close this, because warnings aren't too important here
