### ISSUE TITLE
can´t see or found the subtitles menu

### ISSUE THREAD

**Issue by AlejandroVD** [popcorntime/popcorntime#1252]
Operating System Version:

Popcorn Time Version:

Download date:

#### Expected Behaviour

...

#### Actual Behaviour

...

#### Steps to reproduce the behaviour

1. Open Popcorn-time
2. Select a Movie
3. Enter to the subtitle menu (it´s empty)

**Comment by johnnyutah31** [comment]
Same problem, can't be just the two of us.

**Comment by kiriles90** [comment]
OpenSubtitles now (Apr 4, 2020) requires to be logged in for everyone/all apps that use their API -> https://forum.opensubtitles.org/viewtopic.php?t=17110 (damn covid19 prbly..)  

Create an opensubtitles.org account and login with it in Popcorn Time.  

If for some reason Popcorn Time's login doesnt work from the settings (even if it shows it was successful) until the bug is fix in a new version just go in `\src\app\settings.js` and change it there e.g

    Settings.opensubtitlesAuthenticated = true;  
    Settings.opensubtitlesUsername = 'myemail@hotmail.com';  
    Settings.opensubtitlesPassword = '12341234';

**Comment by dutchy1001** [comment]
I had same problem.
Fix @kiriles90  explained worked for me. thx

**Comment by kiriles90** [comment]
Yeah.. needs a proper fix. Team-PCT is aware/on it.

**Comment by team-pct** [comment]
https://ci.popcorntime.sh/job/Popcorn-Time-Desktop/407/

**Comment by Jany-M** [comment]
Subtitles now display in the list, once the movie is downloading/playing, but they still show empty when you're still in the single movie screen/detail.

**Comment by kiriles90** [comment]
@Jany-M that needs a couple of seconds to load then retry it. It was always like that (since it was fixed and changed to opensubtitles anyway after it was broken when yifysubtitles shutdown their api back in 2016-17)

**Comment by AlejandroVD** [comment]
the subtitles do not appear either

**Comment by kiriles90** [comment]
@AlejandroVD did you even read anything in this issue and try it?

**Comment by AlejandroVD** [comment]
Yes, can I contact with you in some way?

**Comment by kiriles90** [comment]
Just write here it might help someone else too that has the same issue as you (if we find what that issue is)

Anyway you have 3 options since opensubtitles now requires to login to use the API.
a) update to build 407 (https://ci.popcorntime.sh/job/Popcorn-Time-Desktop/407/) and login to opensubtitles.org in the settings
b) manually edit \src\app\settings.js in whatever older version you are using (0.4.3 is older too, its dev build 406)
c) properly fix whatever older version you are using the way it was fixed in dev build 407 (with https://github.com/popcorn-official/popcorn-desktop/commit/e0beb97881181da0d4c3ccc4127376992840ced6)

**Comment by AlejandroVD** [comment]
Thank you, sorry for bothering

**Comment by kiriles90** [comment]
You are not bothering. Let me know if you still have an issue after you tried one of the above.

**Comment by annyag** [comment]
I tried to follow the instructions but I can't open the .js file, I get an error Windons Scprit Host. My knowledge in this area is very limited. I'm using the latest version released, I already update Java

**Comment by kiriles90** [comment]
@annyag just update to build 407 (https://ci.popcorntime.sh/job/Popcorn-Time-Desktop/407/) or newer (when that newer comes)  

If you have an older version that you want to keep, open the .js file with a text editor that respects the linebreaks (e.g in Windows wordpad does but notepad doesnt) make your changes then save it.

**Comment by dutchy1001** [comment]
I use [Sublime text 3](https://www.sublimetext.com/3) or [notepad++](https://notepad-plus-plus.org/), both are free to download and respect linebreaks. Their both great to make small changes to the files locally

**Comment by annyag** [comment]
I was able to login from the settings but subtitles list is still not being display in list. Also notice that custom subtitles are not being loaded, the window show up and I can select de file, but is not being displayed. So no subtitle at all

**Comment by dutchy1001** [comment]
@annyag
just filling in the logon details in the settings is not working ATM (build 407 and before). 
As kiriles90 already explained you need to open the file "settings.js" in the installation folder (B in his previous post).
If you open the location  "C:\Users\your pc name\AppData\Local\Popcorn-Time\src\app" right click on the "settings.js" and choose from the popup "open with", this should give you some other options to open the file. 
If you have installed any of the 2 programs I suggested in my previous post you could then choose that one and edit the "opensubtitle"section like this:
`
- // OpenSubtitles
- Settings.opensubtitlesAutoUpload = true;
- Settings.opensubtitlesAuthenticated = true;
- Settings.opensubtitlesUsername = "yourmail@address";
- Settings.opensubtitlesPassword = "your password";`

with the logon details you created a account with "Opensubtitle.org"
Hope this helps

**Comment by annyag** [comment]
@dutchy1001 that is what I did, add login inf in setting.js file, downloaed Sublime and is exactly as above and yet, no subtitle list.

**Comment by dutchy1001** [comment]
Make sure PCT isn't open when changing, or restart after you changed it.
It works for me, I do need to keep clicking on the subtitle button a few times in the movie screen as not always it pops up with all the flags you can choose from.
Edit:
It didn't work when using the "download" option, I choose "watch now" and I use an external player (SMPlayer)

**Comment by annyag** [comment]
I've tried everything exactly as you explained, using the latest build 407, add login info in the settings.js file, I've uninstalled and reinstall several times, tried using a external player and nothing seems to work. Ty anyway guys.

**Comment by kiriles90** [comment]
@annyag we never said to install build 407 and edit settings.js. Those are two different solutions.

You can either
a) manually edit settings.js in your older version
b) fix your older version and login from the settings with e0beb97 or
c) if both of the above sound confusing and you have no attachment to an older version.. clean(!) install build 407 (https://ci.popcorntime.app/job/Popcorn-Time-Desktop/407/) and just login from the settings, no edits, no nothing (do this one)

If nothing works start a movie, pause it, press F12 go to console, and check for any errors and paste them here so we can maybe see what the issue is and it doesnt work for you while it works for everyone else.

**Comment by notnicky** [comment]
please, could someone help me in clear language to solve this ? I have no clue -.- on how to fix the subs.

**Comment by dutchy1001** [comment]
@notnicky 
I think my post is as clear as it can get or let us know what is not clear in that post....

**Comment by cinntia** [comment]
fiz o loggin so oppensubtitles.org no popcorn , mas nao adiantaaaaaa

**Comment by kiriles90** [comment]
@cinntia Its of big use to everyone else who actually follows the instructions and doesnt make a soup out of them. If you follow a) b) or c) (do c) correctly you would have solved your issue.

**Comment by notnicky** [comment]
that is, because unfortunately you'll have to clarify how to 'clean install'... not everyone is acquainted with computer-language.

**Comment by kiriles90** [comment]
Clean install =  uninstall the old version, delete any left-over folders/files and install the new version

**Comment by notnicky** [comment]
what I presumed it would be, ... still not working.

**Comment by kiriles90** [comment]
Works for everyone who follows the instructions correctly. I presume you keep doing something wrong.

**Comment by notnicky** [comment]
deleted anything with the name popcorn time on mymac, emptied the trash, went to : https://ci.popcorntime.sh/job/Popcorn-Time-Desktop/407/
downloaded the version: 

  | Popcorn-Time-0.4.3_osx64.zip

opened up the whole sh'bang, it's not asking me to login or anything.

login for subtitles still connected with opensubtitles.org...

... no subtitles to be found

**Comment by notnicky** [comment]
heaven lord cookies and cream it works... thanks to you and to me

**Comment by dutchy1001** [comment]
just woke up here so glad to see you got it.
Can you elaborate what went wrong?

**Comment by notnicky** [comment]
the Opensubtitles.org account uses an accountname and both the mailaddress.
Ive used the name instead of the address , which was the issue -.- takkk

**Comment by fehnicchio** [comment]
the same happened with me.
I did every thing you sad, unless to change de code, and nothing happened
You(popcorn) can do a new version(4.4) without this problem, because many people here, that use popcorn doesn't know how to code or anything like this. To edit the code, i need to download a javascript'program.

**Comment by dutchy1001** [comment]
@fehnicchio 
to edit code you need notepad++ or Sublime Text 3 (links in an earlier post). Both are handy anyway to have not only for checking/editing code.
If you did a clean install with [build 407](https://ci.popcorntime.sh/job/Popcorn-Time-Desktop/407/) then fill in your login details from Opensubtitle.org should work (I tested this a few hours ago to be sure). 
A clean install is when all files and folders have been deleted from your device (dont forget the files in your" \AppData\Local\Temp" location too)

**Comment by jordirar** [comment]
this did not happen before. What happened to the new update?

**Comment by kiriles90** [comment]
@jordirar nothing happened to the new update read the first comment to find out what happened (to opensubtitles.org)

**Comment by fehnicchio** [comment]
@dutchy1001 i did this, but nothing

**Comment by dutchy1001** [comment]
@fehnicchio 
sometimes you need to click the subtitle button (within the movie section) a few times before you can choose the language you want.
