### ISSUE TITLE
subs do not strem to external apps (VLC, external screen)

### ISSUE THREAD

**Issue by edik06** [popcorntime/popcorntime#1257]
Operating System Version:

Popcorn Time Version:

Download date:

#### Expected Behaviour

...

#### Actual Behaviour

...

#### Steps to reproduce the behaviour

1. ...slect sub language
2. ...play move with VLC or external screen (TV)
3. ...

**Comment by simgeucav** [comment]
i have same problem

**Comment by GitHub-gr** [comment]
Operating System Version: Windows 7

Popcorn Time Version: 0.4.4.0

Download date: 15/04/2020

**Expected Behaviour**
Watch movie with subtitles on DLNA Samsung SmartTV.

**Actual Behaviour**
Watch movie WITHOUT subtitles on DLNA Samsung SmartTV. It was working fine with version 0.3.10

**Steps to reproduce the behaviour**
1. slect sub language
2. play movie on external screen (TV)
3...

**OR**

1. select default sub language
2. play movie on external screen (TV)
3...

**Comment by kiriles90** [comment]
@Persei08 issue is fixed, close please
