### ISSUE TITLE
notification is wrong for movies

### ISSUE THREAD

**Issue by test2a** [popcorntime/popcorntime#1276]
Operating System Version:
linux

Popcorn Time Version:
0.4.3-0

i am using kde connect with my linux ubuntu running the latest install and the notification from the desktop version is incorrect for movies only.
when i watch a trailer, the correct name gets shown in the notification while the actual movie does not.
its not a big problem per se but just something you could look into. i have attached screenshots of the trailer running and also the movie
![Screenshot_2020-04-07-10-48-58-0363060841](https://user-images.githubusercontent.com/39449563/78635932-e3438e80-78c4-11ea-9502-537e71e6d868.png)
![Screenshot_2020-04-07-10-49-57-0592723383](https://user-images.githubusercontent.com/39449563/78635945-e9d20600-78c4-11ea-9b60-ce42d6925f38.png)

**Comment by Persei08** [comment]
Confirming the issue.
PCT dev build 439
Xubuntu 20.04 (with kdeconnect package)
kde connect from play store...

Looked a it quickly. The trailers are youtube embedded player included in PCT with iframe.  it's why the title is set.

So i tried to add a title tag `<title>Test</tilte>` into `src/app/index.html` and it works, you can edit the title on the fly and it update into kdeconnect. So, it's something which could probably be done if there isn't side effect on other OS or window managers (because it also change window title)

What I don't know for the moment is how to change `Chromium` for `Popcorn-Time (Chromium)` if youtube can do that, it mean there is a way.

Screenshot :) : 
![kdeconnect](https://user-images.githubusercontent.com/22459458/97779686-f4652d00-1b7f-11eb-8fbd-8479230133fd.png)

**Comment by Persei08** [comment]
So, patch merged in development branch. Will be in next dev build
