### ISSUE TITLE
Open susbtitles is still not working.

### ISSUE THREAD

**Issue by Andres2903** [popcorntime/popcorntime#1297]
Operating System Version:
 Windows 10

Popcorn Time Version:
0.4.3

Download date:
08/04/2020

#### Expected Behaviour
Show normal subtitles options.
...

#### Actual Behaviour
Since the last update the movies have no subtitles options at all, even when I'm logged in open subtitles
...

#### Steps to reproduce the behaviour

1. ...
2. ...
3. ...

**Comment by dinkadinka** [comment]
I have the same problem

**Comment by kiriles90** [comment]
Duplicate https://github.com/popcorn-official/popcorn-desktop/issues/1252 and fixed in https://ci.popcorntime.app/job/Popcorn-Time-Desktop/407/

(you both need to **update to build 407**, then you still need to login in the settings, this depends on opensubtitles if they ever lift this 'everyone needs to login for the API' limitation again)

**Comment by Sfj-12** [comment]
me to I had delete the app and reinstall but still the subtitle didn't work

**Comment by kiriles90** [comment]
@Sfj-12 **UPDATE TO BUILD 407 OR NEWER** (0.4.3 isnt newer, its build 406)

**Comment by dutchy1001** [comment]
fix at #1318

**Comment by Persei08** [comment]
Duplicate #1252
