### ISSUE TITLE
No subtitles downloading

### ISSUE THREAD

**Issue by micos000** [popcorntime/popcorntime#1313]
Operating System Version:
Windows 10

Popcorn Time Version:
0.4.3.0

Download date:
5-April-2020

#### Expected Behaviour
download subtitles
...

#### Actual Behaviour
no subtitles available
...

#### Steps to reproduce the behaviour
select a movie or a tv show and try to select a subtitle

The problem must be with the opensubtitles api. At April 4 opensubtitles.org took the decision to use API for logged-in users only. What that means:
- We need to provide your opensubtitles.ORG username and password for client, app, program, script etc you are using
- if the application doesn't support to configure this, contact app developers to give this option, it is against our API rules to not have this option implemented.

The API servers are currently overloaded, due to many people staying at home, and we hope with this measure in place, the API load will be back within "normal parameters" which will make the site more useable for our users.

**Comment by kiriles90** [comment]
Yes the login form is fixed in build 407 (0.4.3 is build 406)

Also afterwards due to many people having this issue opensubtitles made an exemption for Popcorn Time but used an old useragent (2016-circa?)

So.. now the options are either login (in the settings or in \src\app\settings.js for builds that the settings login is broken) or change the useragent in \src\app\lib\providers\opensubtitles.js to 'Butter V1' and then no need to login.

This will probably be fixed in the next build though (the useragent changed) so from build 408 you probably wont have to do anything again. It will just work out of the box.

**Comment by micos000** [comment]
Thank you for the reply. I will try what you say and I'll leave feedback.

**Comment by Zacktarus** [comment]
Hi! It's works for me by changing the useragent to 'Butter V1'.
Very thanks for your guess! ;)

**Comment by Persei08** [comment]
i close this there are lot of duplicate report for this issue. Check #1265
