### ISSUE TITLE
CHANGE POPCORN TIME BACK!!!!!!!!!!!!!!!!

### ISSUE THREAD

**Issue by paramvir-phagura** [popcorntime/popcorntime#1336]
Operating System Version:
Windows 10

What genius approved all these major changes to the client? The previous one from a while back was working flawlessly.

Issues:
- App doesn't even close
- Window border is scaled up to the point where it looks ugly
- No zoom?
- Playback pauses continuously on Mac for me, making the video unwatchable. This doesn't happen on my Windows PC though

**Comment by Persei08** [comment]
Being bitter don't solve the issues quicker.

Isn't that ironic, you want people to act better but you fail at reporting an issue by following rules or template.

Hold your frustration and try to help instead.

**Comment by pavan-p** [comment]
Your bio sums up your response.

All of the issues mentioned are valid and have their own posts by other users to go further in depth. I tried to make it clear if it wasn’t already, but the current client is crap when it near perfect like a month.

**Comment by paramvir-phagura** [comment]
Your bio sums up your response. Honestly makes me wonder if it's your lazy code that's not doing what it's supposed to be.

All of the issues mentioned are valid and have their own posts by other users that go further in depth. I tried to make it clear if it wasn’t already, but the current client is crap when it near perfect like a month ago.

Why break something when it was fine and should’ve been left alone. That's the only irony here tbh...

**Comment by Persei08** [comment]
>Your bio sums up your response. Honestly makes me wonder if it's your lazy code that's not doing what it's supposed to be.

Haha, yes it partly true for the not closing bug. But by the way it can't be your since you don't even try to contribute, isn't that the real irony, your profile show us you're a developer but you're here trash talking other dev. What do you expect to fix this way? Your frustration ?

>All of the issues mentioned are valid and have their own posts by other users that go further in depth. I tried to make it clear if it wasn’t already, 

Then is it useful or useless ?.. You were already knowing when you posted, in fact it is just an excuse because you wanted to bitch :D

>but the current client is crap when it near perfect like a month ago.

>Why break something when it was fine and should’ve been left alone. That's the only irony here tbh...

Yeah, everybody know... it's bad, developers sucks, blah blah blah...
You can always fork it and maintain a 0.3.10 branch, after all you talk like you can handle things  better (except frustration maybe), so don't just talk, time for action.

Good continuation to you. :/
