### ISSUE TITLE
Nothing loading at all..

### ISSUE THREAD

**Issue by popcornhelp** [popcorntime/popcorntime#1346]
Popcorn time App is no longer loading anything when i Open it, its just stuck on a loading icon, an ideas to fix? thanks

**Comment by dutchy1001** [comment]
If you filled out the issue properly then we would seen what version you use

**Comment by popcornhelp** [comment]
sorry about that, it's 4.3..

**Comment by dutchy1001** [comment]
update to the latest version **[here](https://ci.popcorntime.sh/job/Popcorn-Time-Desktop/413/)**, not sure the same version is on the main download page but if you follow the link you will have for sure the latest

**Comment by alexeyoganezov** [comment]
I had the same issue. Solved it by manual application redownloading/reinstalling.

**Comment by EmmanuelMess** [comment]
Same issue in 4.4 and 3.3.

**Comment by keenminded** [comment]
Unchecking 'Remember Filters' in Advanced Settings, then clicking away from the tab you are currently on (if on Series, click Movies, etc.) loaded everything up for me. Obviously, this is just a workaround, but hopefully, it will shed some light on the matter for the maintainers.

**Comment by EmmanuelMess** [comment]
> Unchecking 'Remember Filters' in Advanced Settings, then clicking away from the tab you are currently on (if on Series, click Movies, etc.) loaded everything up for me. Obviously, this is just a workaround, but hopefully, it will shed some light on the matter for the maintainers.

Can' find the 'Remember Filters' anywhere on 4.4.

**Comment by dutchy1001** [comment]
@EmmanuelMess
You can find "Remember Filters" in the settings screen. You have to tick the "Show Advnced settings" on the top of the settings screen, then it's in the second paragraph "User Interface"

**Comment by jairelee** [comment]
I had not set "Remember Filters" but downloading the latest version from @dutchy1001 comment's link worked for me.

**Comment by EmmanuelMess** [comment]
> I had not set "Remember Filter"

Me neither, but I set it and unset it and it worked.

**Comment by Persei08** [comment]
~~Please follow guidelines and make a valid report.~~

Issue already solved. update to v4.4

**Comment by keenminded** [comment]
@Persei08 Unfortunately, the issue still persists on 4.4. To replicate the issue, clear all DB data and reset settings to start fresh. Click around on top categories and wait until any category page content loads. Now click on Settings, Show Advanced Settings checked, then set the checkbox on Remember Filters. Exit settings. Exit app, then start it again. Content no longer loads until the Remember Filters is unchecked, then on exit from setting a different content tab is clicked to reload content again. Hope this helps!

**Comment by dutchy1001** [comment]
@keenminded @Persei08 
I've done exactly as you described how to reproduce the issue but it wont happen to me. 
I then uninstalled PCT (DB's removed too), downloaded the latest [build](https://ci.popcorntime.sh/job/Popcorn-Time-Desktop/416/) and tried again to reproduce this and again it shows all films and series as normal with "Remember Filters" on or off. 
This all has been tested on a Windows 10 (OS build 18363.778) machine.

**Comment by keenminded** [comment]
@dutchy1001 @Persei08 Sorry, I should have qualified that I am running Popcorn's Mac desktop app on High Sierra and upgraded it from a previous version. I am going to reinstall the app from scratch and see if the issue persists on my end and will try it on Catalina too.

**Comment by Persei08** [comment]
@keenminded Sorry but for me what you describe is another issue related to "Remember filters" option.

If you still experience the issue with "remember filters" (I've experienced it randomly too), you should open a new issue report, with a relevant title and description. I will be happy to label it "bug" as soon as someone will reproduce it.

But here I will keep this issue close, because the title and description aren't helpful enough, it related to the old popcorn-api domain being taken down and this place have to look like an issue board (bugtracker) more than like a support forum (There is [r/Popcorntime](https://www.reddit.com/r/PopCornTime/) for support). Else all the contributors waste time searching useful comments in multiple vague reports.

I hope everyone understand.

**Comment by keenminded** [comment]
@Persei08 Thank you. I was just trying to be helpful and provide a workaround, which turned into a bug tracking discussion. I have now reinstalled the app from scratch, and am still researching the strange behaviour. Will create a new issue once I can come up with a solid reproduction path.

**Comment by Persei08** [comment]
@keenminded thank you too, No problem, even if it happen randomly you can open the issue. In fact if I don't opened it myself it's because I don't really find a way to reproduce it, I noticed that sometimes the filter is empty instead of on "all" and then, the tab not load staying with blue circles endlessly. I thought it was related to the "remember filters" option and it match what you're describing I guess
