### ISSUE TITLE
[QUESTION] Builds & Updates

### ISSUE THREAD

**Issue by Immersion-S** [popcorntime/popcorntime#1385]
Operating System Version:
Windows 10

Popcorn Time Version:
0.4.4.0

Download date:
16/04/20

#### Expected Behaviour

N/A

#### Actual Behaviour

N/A

#### Steps to reproduce the behaviour

N/A

Question: Is there a way tell what current build we have installed as they are updated on: https://ci.popcorntime.sh/job/Popcorn-Time-Desktop/ 

Do builds automatically get updated by the client or do you have to manually download them or wait for a new general release?

**Comment by Persei08** [comment]
> Is there a way tell what current build we have installed as they are updated on: https://ci.popcorntime.sh/job/Popcorn-Time-Desktop/

In PT no longer since recently, Previously, You could have used the commit id on bottom right (after version number) of the about page and then searched on CI for same commit id.


>Do builds automatically get updated by the client or do you have to manually download them or wait for a new general release?

I think dev builds are updated when the is new "general" release. There isn't auto update from one dev build to another.

**Comment by kiriles90** [comment]
@Persei08 close this since its not an issue?
