### ISSUE TITLE
Stuck on 'Init Database' mac OS Mojave 0.4.4

### ISSUE THREAD

**Issue by raffaluisi** [popcorntime/popcorntime#1394]
Operating System Version:
OS Mojave 10.14.6

Popcorn Time Version:
0.4.4

Download date:
04.23.2020

#### Expected Behaviour
Run application

#### Actual Behaviour
After upgrading to 0.4.4 on Mac OS Mojave I keep getting stuck on "Init Database" state. Checking the system files it seems that the folders are not even getting installed. 

#### Steps to reproduce the behaviour
Uninstall 0.3.9; install 0.4.4

1. ...
2. ...
3. ...

**Comment by snowc0de** [comment]
Got the exact same issue on Linux (need to be run as root)
Can you try to press F12 when loading. I got several errors in the console because of a lack of rights to access to the files.

![image](https://user-images.githubusercontent.com/33733474/80471567-df46e180-8943-11ea-981d-9e4cac88e44b.png)

If you can try to run it as root. Try to, It solved my issue but I still want a way to solve that because it's really annoying. (I need to write my password each time I launch PT)

**Comment by kiriles90** [comment]
@raffaluisi @chopin2712 have you tried the latest dev build from ci.popcorntime.app? Is this fixed?

**Comment by kiriles90** [comment]
@Persei08 maybe close this, it doesnt seem to be an issue with Popcorn Time, rather.. it doesnt have permission to open its own databases thats why it errors out (also its a bit old so if its an actual issue and still exists someone will reopen)
