### ISSUE TITLE
Build instructions include manually copied external dependencies

### ISSUE THREAD

**Issue by kumavis** [popcorntime/popcorntime#144]
The readme explains that the following files must be pulled from the website: 
- popcorntime.sh/package.json
- popcorntime.sh/torrent_collection.js
- popcorntime.sh/ysubs.js

Why are they not part of the source control?
Seems to unnecessarily complicate the build setup.

**Comment by kumavis** [comment]
If its determined unnecessary I'm happy to update the documentation.

**Comment by VitorVRS** [comment]
Hi,
some months ago, DMCA notified GitHub that this repo should remove this files because their are infringing some copyright.
So, team pct had to remove these files and make and workaround. If you see git history you will see the commit https://github.com/popcorn-official/popcorn-desktop/commit/d5125bc4d643b3c401e481cdd0d77c511e79aa11

If you want, i can paste the email GitHub sent to me to remove these files.

**Comment by kumavis** [comment]
woah crazy - those files in particular? or just needed to neuter the system in some way. id love to see the email, its quite interesting.

**Comment by Breaking1** [comment]
@kumavis here you can see it what it was all about:

https://github.com/github/dmca/blob/master/2016-03-16-MPAA.md

**Comment by kumavis** [comment]
package.json, destroyer of worlds
