### ISSUE TITLE
WebTorrent Engine

### ISSUE THREAD

**Issue by team-pct** [popcorntime/popcorntime#146]
Looking to Migrate Peerflix to Webtorrent engine

**Comment by VitorVRS** [comment]
I'll take a look on this engine.
Are you already developing something about it?

**Comment by G-Ray** [comment]
What are the advantages of webtorrent over peerflix ?

**Comment by team-pct** [comment]
Hello, we did not start yet , 
Avantages ? : a faster metadata fetching 
more peer discovery 
well maintained

**Comment by VitorVRS** [comment]
I want to know if this enhancement is still valid, since there are some butter branches (to merge?).
Or submit this feature to butter instead PCT and sync the repos later?

I would like to discuss this better and other issues too.

**Comment by VitorVRS** [comment]
@team-pct I have this enhancement 80% done, there are some test cases in order to avoid some specific issues?

**Comment by VitorVRS** [comment]
First implementation: https://github.com/VitorVRS/popcorn-desktop/tree/feature/webtorrent

At this moment, i'm able to reproduce any show or pasted/dragged torrent.
Could not test on movies since provider changes.

Todo:
- [x] Introduce WebTorrent
- [x] Subtitles compatibility
- [x] Drag/drop and paste torrent compatibility
- [ ] Stream Info view (show ratio infos)
- [ ] Clean peerflix from other sources
- [ ] Implement Preload (?)
- [ ] Seeding (?)
- [ ] Refactoring

Tested devices:
- [x] Local
- [x] VLC
- [x] MPC HC
- [ ] Chromecast
- [ ] AirPlay (?)
