### ISSUE TITLE
Tv show The Blacklist

### ISSUE THREAD

**Issue by ghost** [popcorntime/popcorntime#1466]
Operating System Version:

Windows 10 Home 64-bit
Popcorn Time Version:

Download date:

January 2020
Download url (optional):

#### Expected Behaviour

...Play me actual episodes from Blacklist

#### Actual Behaviour

...Play other tv show, from Netflix, not sure whats name

#### Steps to reproduce the behaviour

1. ...The Blacklist tv show
2. ...first 15 episodes 1 season
3. ...

**Comment by Persei08** [comment]
EZTV issue. go to their shows page (https://eztv.io/showlist/) visit "Blacklist, the" page, check torrent list, episodes of show "The A list" were added 8 months ago.

Corrupted data in their database. Eventually you can ask them to fix it, but i don't know if they will. This said I close the issue because it isn't a PT issue :|
