### ISSUE TITLE
Watch now button does not work properly.

### ISSUE THREAD

**Issue by harshbgupta** [popcorntime/popcorntime#1485]
Operating System Version:
MAC

Popcorn Time Version:
0.4.4

Download date:
25 may

Download url (optional):
https://popcorntime.app

#### Expected Behaviour
"Watch now" button should work every time. when I clicked on it.
...

#### Actual Behaviour
Sometimes (a few time) "watch now" and most times not (like after after watching 5 or 6 episode)
...

#### Steps to reproduce the behaviour

1. I was watching few of episodes watch now button does not work. 
2. Tried restarting app and fluching all database cache ... tried restated my laptop but still not working.
3. ...

**Comment by robot3498712** [comment]
Same issue - erratic / unreliable behaviour with various error messages via console.. or none.
Used to work fine couple days ago. Perhaps automatic update since, plus I did a manual update to latest version, including purging of all data, confirming this isn't fixed yet via official release.

Download sometimes works.
Watch now sometimes works, or at least associated download, but without triggering player (internal or vlc).

**Comment by Persei08** [comment]
Duplicate of #1437 #1340

I close, we already have 2 reports for this.

**Comment by rosoubr** [comment]
Same thing happens with me!
 
Operating System Version:
Windows

Popcorn Time Version:
0.4.4

Download date:
12 june

I choose a tv serie, the season and episode, click on "Watch now" and nothing happens.
