### ISSUE TITLE
ERROR Cannot read property 'path' of undefined

### ISSUE THREAD

**Issue by Loly2302** [popcorntime/popcorntime#1505]
[Operating](url) System Version:
 Manjaro

Popcorn Time Version:
 Love in time of corona Beta

Download date:
 less than a month before

Download url (optional):

#### Expected Behaviour
 stream an episode
...

#### Actual Behaviour
 nothing
...

#### Steps to reproduce the behaviour

1. ...
2. ...
3. ...

#### Screenshot of error from developer console (optional)

![Screenshot from 2020-06-02 12-49-52](https://user-images.githubusercontent.com/63849343/83512081-fa22ed80-a4cf-11ea-9844-13779b384db8.png)

**Comment by CAVAh** [comment]
Actually the problem is this...

I already have this torrent downloaded (in part, in my case) and I try to download again or watch now. I got this error after open and try again...

![image](https://user-images.githubusercontent.com/5540350/83707236-e8d10280-a5ef-11ea-8f44-92222d30ba59.png)

TypeError: Cannot read property 'path' of undefined
    at WebTorrentStreamer.selectFile (chrome-extension://hecfofbbdfadifpemejbbdcjmfmboohj/src/app/lib/streamer.js:346:62)
    at WebTorrentStreamer.handleTorrent (chrome-extension://hecfofbbdfadifpemejbbdcjmfmboohj/src/app/lib/streamer.js:359:22)
    at WebTorrentStreamer.<anonymous> (chrome-extension://hecfofbbdfadifpemejbbdcjmfmboohj/src/app/lib/streamer.js:84:22)

**Comment by kiriles90** [comment]
@Persei08 issue is fixed, close please
