### ISSUE TITLE
[removed]

### ISSUE THREAD

**Issue by matej2** [popcorntime/popcorntime#1549]

**Comment by dutchy1001** [comment]
Not sure were you downloaded v0.3.10 Beta on the 5th of July 2020, but the official download page will have a lot newer version then that.
Update your PCT from **[here](https://ci.popcorntime.app/job/Popcorn-Time-Desktop/424/)** and see if the issue still happens. 
If your issue is fixed close this topic please.

**Comment by matej2** [comment]
Yes, sorry I was looking at changelog. In right bottom corner it says 0.4.4-0

**Comment by Persei08** [comment]
Codec issue. Install VLC, restart PT, and in the drop-down menu of the "Watch now" button, select to play in VLC.

**Comment by matej2** [comment]
Why did you close this? Codec is not supported and as I belive, this is a bug..

**Comment by dutchy1001** [comment]
If this is a bug then many others would have created an issue about this ( this is a windows 10 issue, not PCT's).
Have yoiu tried the suggestion **@Persei08**  mentioned?
Have you updated to the version I linked you too?

Depending on your version of Windows10 it could be that some codecs have not been installed due to various reasons/versions.
To get codecs you can google "[**video codecs windows 10**](https://www.google.co.uk/search?safe=off&source=hp&ei=nwIrX_rBNq-elwTpu6fQAg&q=video+codecs+windows+10&oq=video+codecs&gs_lcp=CgZwc3ktYWIQARgBMgIIADICCAAyAggAMgIIADICCAAyAggAMgIIADICCAAyAggAMgIIADoRCC4QsQMQgwEQxwEQowIQkwI6CAgAELEDEIMBOgsILhCxAxDHARCjAjoICC4QsQMQgwE6CAguEMcBEKMCOg4ILhCxAxCDARDHARCjAjoCCC46BQgAELEDOgQIABADOgUILhCTAjoECAAQClCoB1jYJGCQMmgBcAB4AIABb4gBswiSAQQxMy4xmAEAoAEBqgEHZ3dzLXdperABALgBAg&sclient=psy-ab)" and a few links will be there, take your pick of a link you like and see if that fixes your issue.

I would try first **[VLC](https://www.videolan.org/vlc/index.en-GB.html)** or **[SMPlayer](https://www.smplayer.info/)** before downloading a codec pack. 
I use myself SMPlayer and it's working great for PCT.
Let us know how you get on, just dont wait a month answering....
