### ISSUE TITLE
No Movies, TV Shows, or other content loads when behind a VPN

### ISSUE THREAD

**Issue by douglasg14b** [popcorntime/popcorntime#1578]
Operating System Version: Windows 10

Popcorn Time Version: v0.4.4

Download date: 04/2020

Download url (optional): From links on this repo

#### Expected Behavior

That the content loads

#### Actual Behavior

Content does not load

#### Steps to reproduce the behavior

1. Enable VPN (PIA, mullvad, or Nord)
2. Open popcorn time
3. Observe an infinitely loading page for each content tab
4. Close Popcorn TIme
5. Disable VPN
6. Open Popcorn time
7. All content loads immediately

#### Screenshot of error from developer console (optional)

No errors in console.

**Comment by dutchy1001** [comment]
Update to the latest dev build from **[here](https://ci.popcorntime.app/job/Popcorn-Time-Desktop/lastStableBuild/)**
(**Do not get the newer build (426 or 427) as there might be an issue**)

**EDIT:**
issue seems like a user mistake, all builds are good to go.

If the issue still excists after report back orclose issue if fixed.

**Comment by Persei08** [comment]
What you describe is VPN issue. 
If you get the spinning loader it because popcorntime can't get the response from the popcorn-api server.

There is nothing we should fix on popcorn-time for that.

Maybe those VPN providers are blocking popcorn-api server, or maybe something is wrong with your networks settings when you use a VPN.

**Comment by dutchy1001** [comment]
As the OP hasn't reported back, I presume it is solved.

**Comment by douglasg14b** [comment]
If that was the case, would errors not show up in the console?

Unfortunately I cannot find a log file that might provide more information, as failed requests should be logged no?

From my troubleshooting this MAY be related to cloudflair requiring an captcha for some providers, or another CDN blocking the VPN IP. If I start to cycle through IPs it will work, and then not work, suggesting that this may be an issue on the content delivery side of things, not the VPN provider itself.

<hr>

Can you provide a list of endpoints (And their HTTP method) for popcorn time content that I can attempt to access outside of popcorn time when on an IP that does not work to see if it's being blocked in some manner?

**Comment by douglasg14b** [comment]
Sorry I took so long to reply, I get hundreds of github notifications each week and this got buried.

**Comment by Persei08** [comment]
@douglasg14b 
In theory in a perfect world there should be a timeout and an error triggered. Now, it's was maybe forgotten or it's bugged and stay on loading state indefinitely.

Now as you're describe, it could be related to some specific IP being blocked by cloudflare.

I think the issue here is more about having an appropriate error message. Something like "Timeout: It seem you can't reach the server or get response from it."

**Comment by kiriles90** [comment]
Closing this since its fixed with https://github.com/popcorn-official/popcorn-desktop/pull/1942, https://github.com/popcorn-official/popcorn-desktop/commit/67c8088207dcb1c3e874c30fa2e98be3a15ed1af & https://github.com/popcorn-official/popcorn-desktop/commit/ef6cfef0c0f28c0b7133acf4f076ddb7c2d51a3e  

Remains to see why the default API doesn't behave accordingly but you can test what the above do by setting a custom api(s) in the settings.
