### ISSUE TITLE
Science Fiction filtering doesn't work

### ISSUE THREAD

**Issue by kaypoush** [popcorntime/popcorntime#160]
Hi,

Science Fiction filtering doesn't work and returns "No movies found...". Only the "Movies" and "Series" sections are concerned. 

Info :
- Windows 10 Family 64 bits
- Popcorn Time version 0.3.9 (https://ci.popcorntime.sh/view/All/job/Popcorn-Time-Desktop/105/)

I tried a fresh reinstall but it still doesn't work.

Thanks.

**Comment by VitorVRS** [comment]
It seems that PCT API its not returning content for "Sci-Fi" content.
I could not get PCT API url to make some tests, maybe @team-pct can check if there are something wrong with this genre on API.

**Comment by beppe9000** [comment]
I confirm this on Windows 10 Pro. Here is a screenshot showing the problem:
![popcorn-time_2016-06-12_15-56-05](https://cloud.githubusercontent.com/assets/6625123/15991546/41a60620-30b6-11e6-8e15-d82dfe39bb61.png)

**Comment by finwefeanor** [comment]
not only scifi category is empty, also most movies-tv series had been misplaced in some wrong categories. It's probably related to this issue i don't know.

this is one of the examples:
![adsasdasdadsasd](https://cloud.githubusercontent.com/assets/20141941/16357269/7a6a9d88-3afa-11e6-8154-76b140656295.PNG)

**Comment by finwefeanor** [comment]
even the lord of the rings doesn't have a "fantasy" title on it, some scifi products have fantasy title.

I don't want to start an argue about what movie is fantasy or what is not, just simply pointing out that for some shows , some categories are essential. 
![lotr](https://cloud.githubusercontent.com/assets/20141941/16357294/368cf2fe-3afb-11e6-97cb-a109de114f54.PNG)

**Comment by beppe9000** [comment]
How can Star Wars be fantasy and not science fiction? I think something is wrong with IMDB...
![applicationframehost_2016-06-25_17-19-40](https://cloud.githubusercontent.com/assets/6625123/16357509/2c5a9a04-3af9-11e6-8e07-7cd4789d7ed8.png)

**Comment by finwefeanor** [comment]
You just need to scroll down beppe
![screenshot_2016-06-25-18-42-53](https://cloud.githubusercontent.com/assets/20141941/16357633/deba59e0-3b04-11e6-89db-ebd64ef64a10.png)

Sci fi movies can also include fantasy most of the time(because there are many fantasy elements in star wars also)  but they always labelled as sci fi along with fantasy. But fantasy movies can not include sci fi most of time. You can't see game of thrones as sci fi.

**Comment by beppe9000** [comment]
The question is: how does popcorn time get the list of movies for a genre? Can we have an example url to investigate? Maybe popcorn time has an hardcoded list of genres somewhere and the api doesn't recognize the science fiction one? ie. popcorn time has `sci-fi` and the api has `scifi`

**Comment by finwefeanor** [comment]
Honestly I don't know I am not a programmer (just beginner), I came here to report this problem and seen it has already been reported, just wanted to add something. 
I don't know if api is gathering data from a hard-coded list but it seems to me that this is somehow related to developers who didn't want to spend many time to correcting genres. Because not only sci fi genre is the issue,  most of the movies and shows have been generalized. Almost all of them includes "action adventure".  Yes they are very common genres in movie industry but come on almost every movie or show in popcorn time includes this.

**Comment by finwefeanor** [comment]
And I don't know if popcorn time has an editable interface (it says open source) but if it can be editable like imdb, users can fix this problems by manually(correcting genres of movies and shows). Developers might not be needed if it can be fixed this easily.

**Comment by beppe9000** [comment]
I investigated further. 

This is an example v2 API call to get metadata about a sci-fi movie:
`https://yts.ag/api/v2/movie_details.json?movie_id=5768`

An an excerpt of its result, showing its genres.

```
[...]
      "genres": ["Action", "Drama", "Sci-Fi", "Thriller"]
[...]
```

Now let's compare with what is defined in PCT: [the configuration](https://github.com/popcorn-official/popcorn-desktop/blob/development/src/app/lib/config.js#L26) uses "Sco-Fi" too, so I'm baffled, here.

**Comment by ChrisAlderson** [comment]
Hello,

I was reading the comments on this issue and I'm here to clear a few things up.

First of all what content gets provided by the kind of content. For now the movies are still coming from the API of [yts.ag](https://yts.ag/) and the TV series/shows are coming from the [popcorn-api](https://github.com/popcorn-official/popcorn-api). Since PT does not have control over the YTS API they cannot fix issues with their API, but PT can fix issues with the show API as it is open source and publicly available.
The [popcorn-api](https://github.com/popcorn-official/popcorn-api) does also provide movies, but these are not used for PT yet as you'll need a new [butter-provider](https://github.com/ChrisAlderson/butter-provider-movies/). A new version of PT is in the make to support this butter provider, so in the future both movie and show content will be given out by the popcorn-api.

Secondly I'm here to clear things up about the metadata. The popcorn-api gets its metadata from [trakt.tv](https://trakt.tv) and not IMDB as they do not have a nice API to get metadata from. Since trakt.tv and IMDB are separate entities their metadata can be different from each other. This is also the reason why ratings and sorting can look different if you are used by the metadata provided by IMDB. Sadly I do not know where the API of YTS is getting its metadata.

Thirdly and lastly the issue with the Sci-Fi content. This should be fixed in the latest version of the API as shown [here](https://github.com/popcorn-official/popcorn-api/blob/master/src/controllers/shows.js#L127). This is a quick and dirty solution and this should be fixed by the client-side (desktop and mobile applications), but for now this will have to do. And again since PT does not have any control over the YTS API we cannot fix it on the movie side of PT.
If there is other content of a genre not showing like with Sci-Fi you can check the supported genres [here](https://github.com/popcorn-official/popcorn-api#genres).

I hope this helped clear somethings up, but if you have any other questions I'm pleased to answer them.

Yours sincerely,

Chris

**Comment by twyzeas** [comment]
What I can tell is both 'sci-fi' and 'film-noir' has the same issue. I assume it's the hyphen what causing the problem, but I'm no coder, so can not tell for sure. Can you confirm or disprove?

**Comment by ChrisAlderson** [comment]
The genre 'film-noir' should work correctyl, only the database does not contain any movies with this genre. A version of the popcorn-api which fixes the issue with the 'Sci-Fi' genre should be in production atm so I'm closing this issue.

**Comment by beppe9000** [comment]
It is working now! :D

**Comment by twyzeas** [comment]
> It is working now! :D

Definitely not for me. As far as I can tell there was no update (still version 3.9), and clicking on Sci-Fi gives me still no results.

**Comment by beppe9000** [comment]
Try a fresh install: delete the popcorn time folders from appdata (do a backup first, in case you want to restore the watched database) and then install again.

I am using 3.9 on Windows 10 x64. (This version: https://github.com/popcorn-official/popcorn-desktop/tree/43d3386b0555ab18366492bbaf5a91dbac432648)

**Comment by twyzeas** [comment]
Thanks, a fresh reinstall solved it!
