### ISSUE TITLE
Memory leak when opening and closing seedbox often

### ISSUE THREAD

**Issue by ArcticZeroo** [popcorntime/popcorntime#1613]
This issue is here to track an issue where each navigation of the seedbox causes a memory leak. Each time we navigate to the seedbox, we add listeners on the torrent for events such as ready, upload/download, etc., but these listeners are never removed when we leave the page. This results in a significant amount of extra listeners if the user downloads many movies, keeps the app open for a long time, etc.

Affected versions: Current development branch, aka all of them. This is not new to my changes to the seedbox page

**Comment by Devologger** [comment]
Maybe it has something to do with Webtorrent #1373?

**Comment by kiriles90** [comment]
@ArcticZeroo https://github.com/popcorn-official/popcorn-desktop/commit/82a4d9c7ee9dce5af5538f771794c51de7578e6d removes the upload/download ones that I guess would be the ones that most affect this. Not sure what we can do about the 3 remaining ones, if just `.off()` could be a solution or if we even need to worry about them.

Any insight?

**Comment by ArcticZeroo** [comment]
@kiriles90 I am a bit short on time right now, so I haven't had a chance to debug this myself yet. If `onAttach` is _not_ called every time the seedbox window comes up, I think this issue should be solved with those changes you linked

**Comment by kiriles90** [comment]
Hmm, I might be getting this wrong but wouldn't avoiding re-attaching the view also mean forgoing destroying it which will basically mean the Seedbox and all its DOM elements will always be attached/active and updating/consuming resources/etc?

How about an `App.WebTorrent.removeAllListeners('torrent')` on `onBeforeDestroy` ? Nothing else other than the Seedbox sets these and we can just clear without affecting.. anything basically. The only thing that needs one (Seedbox) will just re-set one the moment the user open the view.

**Comment by kiriles90** [comment]
So, after testing this further with something like
```
for (var i = 0; i < 500; i++) {
    setTimeout(function() {
        $('#filterbar-seedbox').click()
    }, 2000 * i);
}
```

(*paste it in the console, just make sure you have some time to waste it will run for 15+ minutes with i < 500)

and 5 torrents active (4 downloading, 1 streaming) maxing out my internet connection I didnt notice any memory leak at all while the script was running or when it finished. After leaving the app downloading another 15 minutes the memory usage even dropped to less than before I started all this since some of the downloads had finished by then. No extra listeners seem to linger in `App.Webtorrent` either so `App.WebTorrent.removeAllListeners('torrent')` and the other changes seem to have done the job. Closing this for now unless someone thinks I missed something in which case let me know.
