### ISSUE TITLE
Moves and series list won't load

### ISSUE THREAD

**Issue by GKid94** [popcorntime/popcorntime#1650]
Same issue https://github.com/popcorn-official/popcorn-api/issues/138

**Comment by dutchy1001** [comment]
maybe try the latest dev build as you don't specify enough info I cant see which version you have.

**Comment by Persei08** [comment]
@GKid94 stop opening useless issues just for the pleasure to bug us. 
You're here since long time now, [you've opened 41 issues already](https://github.com/popcorn-official/popcorn-desktop/issues/created_by/GKid94)

How do you still not able :
- To fill the issue report usefully/accurately ?
- To search for duplicate issue ?
- To understand it's waste of time to create duplicate issue ?
- To find answer to this issue, which we replied too often already ?

If PT catalogue don't log, it's because you can't receive response from popcorn-api... which in 99% is because user can reach popcorn-api servers which... to be more specific, it mean in 99% of the case it's because users ISP is blocking popcorn-api.

**The usual way to bypass this is to use a not lying DNS like google DNS (8.8.8.8, 8.8.4.4) or Cloudflare DNS (1.0.0.1, 1.1.1.1) else the other solution is to use a VPN.**

By the way, I close your issue because it's on your network side.
