### ISSUE TITLE
Allow to add/search a title in the Watchlist

### ISSUE THREAD

**Issue by ppo** [popcorntime/popcorntime#1763]
From the list of titles, search results or detail view of a title, please allow to add a title to my watchlist.

**Comment by kiriles90** [comment]
Merging with https://github.com/popcorn-official/popcorn-desktop/issues/1762 which is tagged as a bug and closing this one.
They are very closely related issues (e.g a module update could fix both) and tbh when/if the Watchlist is eventually repaired it should fix both otherwise its not really functional.
