### ISSUE TITLE
Favourites memory problem

### ISSUE THREAD

**Issue by geoffrey5239** [popcorntime/popcorntime#1850]
Popcorn time is now only remembering one favourite.

**Comment by dutchy1001** [comment]
As you didn't fill in the issue form it's hard to help you were the issue can be. Update to latest dev build from **[here](https://ci.popcorntime.app/job/Popcorn-Time-Desktop/lastStableBuild/)** and see if the issue is resolved.

I have plenty of favourites in my list that  have always been there and still are.
