### ISSUE TITLE
White Collar Serie TV - AUDIO ok - VIDEO no, it does not work

### ISSUE THREAD

**Issue by Papermillo** [popcorntime/popcorntime#1888]
Operating System Version:
 APPLE

Popcorn Time Version:
 Version 0.4.4

Download date:
11/2020

Download url (optional):

#### Expected Behaviour
 Show the film/video od the episode of WHITE COLLAR - SERIE TV.
...

#### Actual Behaviour
 Does not show any image on the screen, only audio of the episode.
...

#### Steps to reproduce the behaviour
 Just reproduce one episode of the serie TV White Collar

1. ...
2. ...
3. ...

**Comment by kiriles90** [comment]
That's probably because of a missing codec. Install a supported external player (e.g VLC) and select it in the dropdown menu next to the 'Watch now' button in Popcorn Time.  

Also maybe since you are using release version 0.4.4 (=build 413) update to the latest dev build from ci.popcorntime.app (build 445 at the moment). It wont dont anything about the missing codecs, but it will fix other issues 0.4.4 has.

**Comment by dutchy1001** [comment]
White Collar has a 99% red magnet link meaning there are none or very few seeds shared. Also I can only see 480p version which are mostly in Xvid format that isn't supported by PCT.
This is explained in the post here:
https://github.com/popcorn-official/popcorn-desktop/issues/1742#issuecomment-708483797

PCT is not responsible for the content, they have no control what is showing as that comes from 3rd party torrent sites.
Hope this will clear the issue for you
