### ISSUE TITLE
Remote anime API failed to load

### ISSUE THREAD

**Issue by dermil** [popcorntime/popcorntime#191]
Operating System Version:
Windows 8

Popcorn Time Version:
Beta ver. 3.9

Download date:
I've had it installed for a while.
#### Expected Behaviour

Show the anime listings
...
#### Actual Behaviour

It says "Anime API failed to load, try again later." It's been doing this for a few days and has never done that before.
...
#### Steps to reproduce the behaviour

I just went into anime and thats it.

http://prntscr.com/bi617f

**Comment by Bloodcore** [comment]
**Operating System Version:**
Windows 10 Pro [x64] - (Fresh install with Build 1607)

**Popcorn Time Version:**
Beta ver. 3.9

**Download date:**
Today. (Used PopcornTime in the past)

**Expected Behaviour**
Show the anime listings

**Actual Behaviour And Steps to reproduce the behaviour:**
Same as dermil.

Any solution or suggestions would be lovely.

**Comment by voddan** [comment]
Same on Mac

**Comment by ChrisAlderson** [comment]
This issue should be fixed with #223
