### ISSUE TITLE
Filter out years but keep popularity

### ISSUE THREAD

**Issue by Celuni** [popcorntime/popcorntime#1984]
I love to sort by Popularity but at the same time I don't want to see anything older than a few years, like only Movies from 2010-2021 anything else should be hidden.
Can you make such feature please? 🥺🙏

**Comment by kiriles90** [comment]
The official API at the moment doesn't support sorting or searching by year. Better make an issue at https://github.com/popcorn-official/popcorn-api. When that's done the app can easily implement it.

*For some other APIs (e.g yts) that support sorting/searching by year you can set the filters that you want and just include the year in your search query. It already works the app doesn't need any modification.

Closing this issue since its API and not app related but feel free to continue the conversation or ask anything below.
