### ISSUE TITLE
"Not for me" button - to remove movies you are not interested to see

### ISSUE THREAD

**Issue by Aspir32012** [popcorntime/popcorntime#1989]
It is great that there is a possibility to mark the movie as watched, so it becomes dark, and it is much easier to scroll the movie list, however, all the movies that I am completely not interested in are still distracting me and it would be amazing to hide them too. This would make choosing the movies much easier and with less distraction. 

I would suggest having a similar button as Netflix has - "Not for me" button. Which could take off the movie completely from the list or at least make it also dark as watched. If the movie is taken completely off, there should be a list of those movies somewhere, so the user could always review it and resume some if required. 

The current workaround could be to mark movies that I don't like also as watched, but I do not want to do so in case there will be a function in the future that will suggest movies on what you have already marked as watched.

**Comment by kiriles90** [comment]
There is an option to hide those movies not just darken them in the settings. Just set 'Watched Items' to Hide. You can then set it to Show or Fade again if you want to unmark items individually or just clear your databases to reset everything.  

Closing this since I dont think  

> a function in the future that will suggest movies on what you have already marked as watched  

is happening any time soon (or at all, there have been a couple of closed issues about it in the past) since it would imply that Popcorn Time monitors and records its users history somewhere which isn't such a great prospect for everyone considering the nature of the app.
