### ISSUE TITLE
Subtitle flag dropdown for series

### ISSUE THREAD

**Issue by sorin-costea** [popcorntime/popcorntime#1990]
For a movie I can see on the movie screen the subtitle languages and select one before playing. For episodes of a series, there's no dropdown for this (okay there's less space as well but still). 

I know I have a default language in the settings but changing it every time is cumbersome. For episodes in languages I'm able to speak, I'd like to have also subtitles in the respective languages, while for anime or Bollywood I want English subtitles. But in the settings I cannot know beforehand which languages I will have available for that particular episode from OpenSubtitles...

**Comment by kiriles90** [comment]
I think this was never implemented due to the sheer number of API calls to opensubtitles that it would cause. At the moment it will only make one when you actually play an episode and they already have issues (with us and with traffic in general) which led them to require to be logged in for apps to use their API. They did exempt Popcorn Time after some 'back and forth' from this but it might change at any time.

Anyway, leaving this open for a while in case someone has some insight on the issue.

**Comment by sorin-costea** [comment]
Lol I was about to suggest the same :)
