### ISSUE TITLE
App crashes when download speed is too high

### ISSUE THREAD

**Issue by vviotto** [popcorntime/popcorntime#1991]
Operating System Version:
Windows 10

Popcorn Time Version:
0.4.4 Dev build 452

Download date:
Updated to the latest version today, but this has been happening since the 4.3 update

#### Expected Behaviour
Stream any torrent without issues

#### Actual Behaviour
When streaming a custom torrent, the app starts to lag(its easy to notice this just by hovering over the icons in the player), subtitles will start to get delayed and eventually the app will crash after a few minutes.
I've noticed that this only occurs when the download rate is high, I'm not sure of the exact number, but I can say that, for me, it happens around 8~10mb/s or more. (It might be related to the number of connected peers too, but I was unable to properly test this)

At least here on my machine this happens 100% of the time, I've been having this problem for a few months now and I get around that by just opening the app and trying again until the download completes, at that point the movie will play without any issues.

#### Steps to reproduce the behaviour
1. Grab a custom torrent with good health
2. Throw it in the player and start streaming
3. Ensure that the download rate is very high
4. Let it stream for a few minutes, the interface will start to lag and eventually the app will crash

#### Screenshot(s) of issue or error(s) logs of developer console (Windows/Linux: F12, MacOS: ⌘ + 0 ... then 'console' tab) (recommended)
Not sure how to do this because the app closes and I couldn't find any log files in the Popcorn-time folder

**Comment by kiriles90** [comment]
WebTorrent is cpu bound. They have several open issues about this (e.g https://github.com/webtorrent/webtorrent/issues/1026)  

For now I guess the only thing you can do about it (other than adding in more ram or a better cpu) is limiting the max. connections in Popcorn Time settings.

Closing since this is not really up to Popcorn Time to fix. When something over at WebTorrent changes we'll just bump the version we use.

**Comment by DAOWAce** [comment]
This is still an issue and doesn't appear to be related to any custom torrent (unless the default movie list in the program is "custom").  I also don't see any other issue talking about a crash when downloading besides this one. Can it be re-opened?

Updated to the stable build of 4.6 (from 4.4) hoping for a fix, but sadly it's still happening.  And it can happen when only downloading; has nothing to do with actively viewing the content.

I don't know if this is related solely to the "download" feature itself as I've been using it instead of actively watching an in-progress download, but it's pretty much reproducible every time I download a 4K video since the filesize is quite big.  It'll just crash either in the background, or after bringing the window up again.  Becomes more easily reproduced by downloading multiple files in parallel.

Bit of a pain because it wipes the download list after the crash (or after a restart of the app anyway), but starting the download again will pick up where it left off, so while annoying to deal with, it's not a major problem, but a problem nonetheless.

No windows error logs, so the program must be hard closing.  Don't know where to get logs for it, if any get written to disk, the console doesn't appear to have any relevant information (as I assume it's just for that session).

**Comment by dutchy1001** [comment]
Would it be an option to set the download speed in the setting to a lower value?
Of course this would not be the permanent solution as you should be able to use your full bandwidth of your provider but worth to see were the "sweet spot" is for you in downloading a movie/serie.
I dont know what speeds your connection is but I have no problem with 350mb

**Comment by DAOWAce** [comment]
I don't know, I'm only on a 200mbit connection, and don't really monitor the speeds, so I'm not totally sure it's a download speed issue like the OP has reported. Can test in future though.

All I know is that when downloading, PCT will usually just hard CTD after a while.

**Comment by DAOWAce** [comment]
Getting back to this, it doesn't seem to have anything to do with the download speed.  I'm also now using the latest (4.7) build.

I read over this issue and it seems related: https://github.com/popcorn-official/popcorn-desktop/issues/2355 I'm using Windows 10 though.

It seems if you have something downloading with protocol encryption enabled, the RAM usage just keeps going up and up and up, never seeming to clear itself.  It also heavily bogs down the program's UI, as it seems to be singlethreaded.

Once it hits around 8GB, the app hard crashes with no errors in event log.

RAM usage still seems to increase without protocol encryption enabled, but at a slower rate.  While writing this, I just saw it clear memory when it hit around 1.55GB.

Additionally, there's some weird process execution: ![tm_2022-03-22_11-18-19](https://user-images.githubusercontent.com/480587/159518469-c00d6f36-b722-4277-857e-cc3845962f17.png)

When closing PCT, it doesn't close the processes with those small bytes of memory.  I have to terminate them all manually.

I don't remember any of this happening in the past, but that was a number of years ago.  PCT didn't have the download feature back then, nor did it offer 4K videos.  Could've always been a problem, who knows.

**Comment by kiriles90** [comment]
@DAOWAce 

>  It also heavily bogs down the program's UI, as it seems to be singlethreaded.

It does, hence its disabled by default and has a warning next to the option in the settings (and yes being singlethreaded is the culprit, its a limitation of the version of nwjs we use, it doesn't have a native option for calculating the secure keys needed and the third party solution incl webtorrent itself cant run on anything else than the main thread, e.g a worker)
This all has to do with cpu usage though, you are talking about a memory leak which personally I've also noticed happening in odd occasions while PE/MSE was enabled though haven't definitively conclude it was also the cause or just happened to be enabled.

Keeping an eye on this also, I'll reply here if I find something more.
