### ISSUE TITLE
How do I contribute uploading videos?

### ISSUE THREAD

**Issue by henryfy** [popcorntime/popcorntime#1992]
How does this community service? 

Do we have any website to upload the videos??

I would like share one video with my friends and only have on USA netflix, I a ready did the download and I need upload in any hosting provider.

Do we have any torrent hosting link available as a website?

Kindest Regards,

Henry

**Comment by kiriles90** [comment]
Hi, Popcorn Time doesnt upload, host or maintain any of the content. It uses torrents which its APIs automatically index from 3rd party providers. At the moment for movies its YTS.mx and for series EZTV.re (and some others for other data/metadata/subtitles/etc)  

I dont know if you can make a request in either of them because they don't really accept user uploads, maybe some requests, but you can try. If it gets added to either of them and has an IMDb id Popcorn Time will automatically index it.

Closing this issue since it doesn't really depend on Popcorn Time but feel free to comment below if you need help with something or some of the above wasn't clear.

**Comment by reddo** [comment]
@kiriles90 what is the url to use eztv.re? https://eztv.re/ does not work for custom series server

**Comment by dutchy1001** [comment]
@reddo
depending on if your ISP has blocked this site. I can access this through a VPN from the UK, if I turn off my VPN I can't connect.

**Comment by reddo** [comment]
@dutchy1001 it's not blocked by the isp, I can access the page fine in the browser. I'm fortunate enough that my ISP does not block any sites.

**Comment by kiriles90** [comment]
@reddo none said that you can use eztv.re as a custom series server just because you can use yts.mx for custom movies server :)  

Popcorn Time's API uses eztv.re as the series provider, then the app connects to that. Direct yts.mx API support was added as a solution for the issues the official movie API is having with updating etc but since the official series API updates just fine none went to the trouble of doing the same for eztv (both arent directly butter-provider compatible so someone has to make some adjustments to the wrapper like https://github.com/popcorn-official/popcorn-desktop/blob/development/src/app/butter-provider/yts.js for yts). If someone wants to take a shot at it though (even if a bit unnecessary imo) just make a PR.

**Comment by reddo** [comment]
Ahh, gotcha, all clear now
