### ISSUE TITLE
TV Show is missing, however it exists on RARBG

### ISSUE THREAD

**Issue by aidenmitchell** [popcorntime/popcorntime#2008]
Operating System Version: Windows 10

Popcorn Time Version: 0.4.4

Download date: January 27th, 2021

Download url (optional): https://github.com/popcorn-official/popcorn-desktop/releases/download/v0.4.4/Popcorn-Time-0.4.4-win32-Setup.exe

#### Expected Behaviour

Find the TV show "Friends".

#### Actual Behaviour

Returns incorrect results.

#### Steps to reproduce the behaviour

Search for Friends.

#### Notes
RARBG link: https://rarbg.to/tv/tt0108778/

**Comment by dutchy1001** [comment]
Popcorn Time itself does not add any movies or series, there linked from YTS (Movies), eztv (series) or similar torrent agents.
Every time you open PCT it will get updated from these torrents, if nothing has been added the list will not change then.
If episodes are missing then it could be that the seeds have dried up (meaning, no one shares the files anymore).

They have no control over what's added and not.

Please close this issue as it can't be fixed by PCT

**Comment by aidenmitchell** [comment]
The issue is that it does exists on the torrent agents that Popcorn Time pulls from, so why doesn't it appear in PT?

**Comment by dutchy1001** [comment]
> If episodes are missing then it could be that the seeds have dried up (meaning, no one shares the files anymore).

Torrent sites are depending on users that share the files, RARBG is only indexing files but (as far as I know) hardly "purge" old files that are not shared anymore (almost all torrent sites don't purge old index files). 
It's the same as a torrent index site, sometimes you see files that you just can't download, same count for PCT.

**Comment by kiriles90** [comment]
@aidenmitchell Where are you searching for it? In the Series tab? If so, its because Popcorn Time doesnt index series from rarbg, they are from eztv.
Update to the latest build from ci.popcorntime.app and search for it in the Torrent Collection. That searches in rarbg, 1337x and omgtorrent (and tpb but its broken for some time now)

**Comment by aidenmitchell** [comment]
@kiriles90 Yep, that worked, thank you. Is there a way to cast from the Torrent Collection? (like the menu usually next to the Watch Now button)

**Comment by kiriles90** [comment]
Yep, click the torrent that you want and when the file selector screen opens there should be the player dropdown at the bottom.

**Comment by aidenmitchell** [comment]
Great, thanks! It appears that casting to a Chromecast device doesn't work, is that a known issue?

**Comment by kiriles90** [comment]
It depends what you are trying to cast since Popcorn Time wont transcode the video. If the codecs are supported by the chromecast it will play if not it wont. You could try using VLC as an external player and casting from there in these cases.

Or just find a different torrent. Btw forgot to mention that you can also drag&drop / copy&paste magnet links in, you arent limited to only the sites Popcorn Time indexes.
