### ISSUE TITLE
git commit fails due to jshint issues

### ISSUE THREAD

**Issue by tkSimon** [popcorntime/popcorntime#2040]
Operating System Version:
Linux

Popcorn Time Version:
development

#### Expected Behaviour
commit jshint check shouldn't find issues in already committed code

#### Actual Behaviour
jshint prevents commit due to issues with already versioned code

#### Steps to reproduce the behaviour
1. clone this repo
2. make changes & git commit, or just do git commit --allow-empty

For now "--no-verify" needs to be used to prevent the git pre-commit hook from running.

**Comment by tkSimon** [comment]
see #2041

**Comment by kiriles90** [comment]
#2041 merged, thanks!

Closing

**Comment by tkSimon** [comment]
@kiriles90 
>This isnt supposed to break its supposed to fall through

Sorry about that. Without the break, this would be needed for jshint to be happy: tkSimon/popcorn-desktop@fd81fbe4be191b3ad32aef2b9a584e926147bac6

I didn't thoroughly check all my changes. For example this, whole block here: 
https://github.com/popcorn-official/popcorn-desktop/pull/2041/files#diff-39975c8d34a8c203249066cb4b7a8c063fdad45c2709e41e86b152858aae0648R259-R269
I checked if the cast seems to be shown correctly, but not sure whether to pay attention to anything specific. The code mentions "crew" but there doesn't seem to be any "crew" in the UI. Maybe you could have a look?
I'd be happy to rewrite those couple of lines to be more readable if you'd be open to that.

**Comment by kiriles90** [comment]
> this would be needed for jshint to be happy: tkSimon/popcorn-desktop@fd81fbe  

Added, thanks.
The rest is all good as far as I can tell but if you want to double-check everything I wont stop you.

About 'crew', the director is a part of it.

> I'd be happy to rewrite those couple of lines to be more readable if you'd be open to that.

You could if you want, the only thing is, they are like that because if we just spread them out like they are they will take a lot of movie_detail with all that inline html, and since showing the cast is not that much of a main feature its 'concentrated' there so as to not be too much in the way. I do understand your point though (and the general consensus about lines like these) they are not very readable indeed.

But tbh (if you want ofc) a better use of your time would be picking one of the issues tagged as 'bug' or 'feature' and doing that but I understand the ones that remain at this point are the ones that are somewhat of a hassle so I'm not putting this on you, just throwing the idea out there.. :)
