### ISSUE TITLE
make "show advance setting" default

### ISSUE THREAD

**Issue by dutchy1001** [popcorntime/popcorntime#2047]
As some users cant find some of the settings because they don't know that you have to tic the "show advance settings" on top I would suggest to make all settings to show as default.

**Comment by kiriles90** [comment]
I understand where you're coming from but wouldn't that mean we should just get rid of the whole advanced/not advanced system? Having that option, and having it enabled by default.. for what? Someone to disable it later? I'm not aware of any app that does this tbh.

**Comment by dutchy1001** [comment]
> get rid of the whole advanced/not advanced system?

yes, that's what I meant. 

There aren't a ton of options anyway so why not make it 1 page. This will stop some confusion for some ppl as they can't see an "advanced" option that is mentioned in the comments.
How many ppl have we told in the comments to tic the "Show Advanced Settings" as they couldn't see/find an option?

**Comment by kiriles90** [comment]
Many I know, the thing is.. should those people be messing around with advanced settings to begin with without someone explaining a few things or they'll just end up breaking their installation and need help anyway? How about the guy who just wants to e.g change the subtitle language but gets scared by all those other settings? I thought about this before but couldn't decide then either one way or the other. Personally I'm still at 50-50.

It would be great if some people who see this offer an opinion.

**Comment by dutchy1001** [comment]
> It would be great if some people who see this offer an opinion.

Totally agree

**Comment by Persei08** [comment]
Hi,

I understand the need but it's a really a common feature in lot of apps... even a convention. I have Kodi app in mind, which have different levels (Basic / Standard / Advanced / Expert... if I remind correctly), or VLC, Google Chrome also have some advanced settings, ... there are ton of examples if we really think of it...
 
In PCT, it's something you just need to enable once, (well... or every time you re-init PCT).

It could be boring with time to repeat that too users but it also teach them how to enable/see advanced options in some apps. And since some options require more technical knowledge, if think it make sense to keep a basic level to not confuse users which will not understand what those advanced options are really doing.

**Comment by dutchy1001** [comment]
When you put it like that it makes more sense to "split" between normal and advanced.

**Comment by kiriles90** [comment]
So, I guess closing this.., especially since we keep adding more stuff in the settings page and more to come (e.g Ivan's pending PR). Maybe when these are done we should see if we can make the API server options 'not advanced' so they are visible even without advance settings enabled and how all that looks.

**Comment by kiriles90** [comment]
https://github.com/popcorn-official/popcorn-desktop/commit/43bbd8173cea080fb7c43c34adc3bd0260bb61e6 Changed the 'API Server' and 'Activate Automatic updating' options to 'not advanced'. Should help a bit?

**Comment by dutchy1001** [comment]
This might help when explaining to add a "custom" servers  to the settings so it's easier to find.

I dont think the update field makes a difference, I presume this only updates when a new "proper" release is made and not when there is a new dev build.
