### ISSUE TITLE
Local series, more cartoon series and more audiotracks

### ISSUE THREAD

**Issue by ElroyNL** [popcorntime/popcorntime#205]
It would be a great improvement to have local series from several countries around the world. It would also be great having more cartoon series like Yu-Gi-Oh! and Pokémon.

And finally, I think it is a good action for a lot of people around the world to adding all of the audiotracks which are available for all films, series and cartoons. Popcorn Time is available in a lot of languages, but adding this will make this section complete.

Yours faithfully,

A Dutch user from The Netherlands

---

Het zal een geweldige verbetering zijn om plaatselijke series van verschillende landen ter wereld beschikbaar te hebben. Daarnaast zal het geweldig zijn als er meer tekenfilms zoals Yu-Gi-Oh! en Pokémon beschikbaar komen.

Ten slotte, denk ik dat het een goede daad voor vele mensen ter wereld is om alle geluidssporen toe te voegen welke voor alle films, series en tekenfilms beschikbaar zijn. Popcorn Time is beschikbaar in vele talen, door dit toe te voegen is deze afdeling voltooid.

Met vriendelijke groeten,

Een Nederlandse gebruiker uit Nederland

**Comment by ChrisAlderson** [comment]
PT does not have very much control over the content it presents. It uses several API's to get the content. This makes it hard to get local content (as you call it), like 'Goede Tijden, Slechte Tijden' as an example. Content like Yu-Gi-Ho and Pokémon is (sorry for being a snob) anime content, not animation. I believe there is an issue with the anime API, which PT does not have any control over, at this moment.

As for the audio tracks, again PT cannot control this, but we are looking into making an API which provides movies with multiple language audio's.

I hope this helped, if these are anymore questions I'll be glad to answer.

Yours faithfully,

Some guy who thinks he can make an API

**Comment by ElroyNL** [comment]
Hello ChrisAlderson,

Thank you for the answer. I have respect for your contribution. I hope this will be add soon. And when adding the anime (hey, I improved it now) like Yu-Gi-Oh!, Pokémon and Shaman King, please adding also the Dutch audio tracks, otherwise i'd rather watching a movie.

Yours sincerely,

A Dutch user from The Netherlands

---

Hallo ChrisAlderson,

Bedankt voor het antwoord. Ik heb eerbied voor je bijdrage. Ik hoop dat het snel wordt toegevoegd. En wanneer anime (kijk eens aan, ik verbeterde mezelf) zoals Yu-Gi-Oh!, Pokémon and Shaman King wordt toegevoegd, voeg dan ook meteen de Nederlandse geluidssporen toe, anders kijk ik liever gewoon een film.

Met vriendelijke groeten,

Een Nederlandse gebruiker uit Nederland

**Comment by ChrisAlderson** [comment]
This issue is divided up into two parts, local series and anime.

As for the anime part I am working on a new API, because the community still wants anime content as displayed [here](https://www.reddit.com/r/PopCornTime/comments/4s5prf/are_there_still_users_interested_in_anime/). We are looking into providing different audio tracks for movies, so a similar implementation could be used for the anime part.

For the local series it really depends on how many torrents there are available and how many of those torrents will get through the entire process of the algorithm implemented in the API. This mean the availability of torrents for each country would need to be examined. And with almost 200 counties in the world it will take some time. And as I do not like favouritism, adding 200 more providers will make the scraping process incredible long.

P.S: With the help of Google Translate I assume the last part of the message is just the same but in Dutch?
