### ISSUE TITLE
Watch Movie button doesn't work

### ISSUE THREAD

**Issue by MariosKiour** [popcorntime/popcorntime#2050]
So I am on windows 10 and I have already seen many other issues created relating to the same problem but non of the fixes previously mentioned works for me. I am also in the latest build. What I have noticed is that the button works for most of the movies but doesn't for most of the series. its really inconsistent. 
![2021-03-07](https://user-images.githubusercontent.com/80219854/110252028-22bea300-7f8c-11eb-9770-5e3052eb8f44.png)
The error reads : Uncaught TypeError : Cannot read property 'toString' of null

**Comment by dutchy1001** [comment]
update to the latest dev build from **[here](https://ci.popcorntime.app/job/Popcorn-Time-Desktop/lastStableBuild/)**.
If fixed plz close this issue otherwise report back.

**Comment by kiriles90** [comment]
You are not using the latest build. You are using release version 0.4.4 (that line that produces the error in the screenshot you linked has since been changed to `tvdbid: (value.tvdb_id || '').toString(),` with https://github.com/popcorn-official/popcorn-desktop/commit/045e33f6eaaf7acc496abdf5bb07042517cd686f)  

Check the link @dutchy1001 posted above and update. Closing this.
