### ISSUE TITLE
subtitles

### ISSUE THREAD

**Issue by 1samiamidaki** [popcorntime/popcorntime#2075]
Hi. I am Loukas from Greece. I REALLY like your work. But is it possible to lock subtitles at movies somehow?  So many times some bad people try to still your good work, erase your presentation and subtitles are not synchronized with the movies. You could find a warn when someone is attacking to this project! Or checking the movies time to time! I do not know. you know better. :) about how and what you can do about it. :)

**Comment by kiriles90** [comment]
Hi, the subtitles cant be locked on the movies since they are automatically fetched from a separate provider (opensubtitles.org). Popcorn Time tries to find the correct one for the specific rip based on some criteria but its not always successful. Even more so because sometimes people just input bad or incomplete info when uploading those subtitles. 

You could try syncing them yourself by pressing the `H` and `G` keys when in the player screen (or the relevant keys if you are using an external player) but sometimes the easiest solution is just selecting a different subtitle. You can already see all the available subtitles for all languages in the player subtitle menu and if you want to see them in the flag popup menu too you can enable the  "Show all available subtitles for default language in flag menu" option in the settings. (*if you cant find this option update to the latest build from ci.popcorntime.app first)
