### ISSUE TITLE
No access to repo

### ISSUE THREAD

**Issue by 1337-537h** [popcorntime/popcorntime#2090]
That was not an actually bug.
I used to watch and download always the latest builds of popcorntime desktop at this repo (https://ci.popcorntime.app/job/Popcorn-Time-Desktop/)
Today a "new" redirect site appears and i can't visit it.
Here in github repo the latest version is 14 Apr 2020 the other site updates versions about every 1 to 10 days (still 0.4.4 but newer builds).
Is there any other way to update/watch/monitor that?
Im not using github cause the old versions..

**Comment by LoLo2207** [comment]
Try with Wayback Machine from Internet Archive. 
They have a snapshot from February 24th, with build #453

https://web.archive.org/web/20210224003904/https://ci.popcorntime.app/job/Popcorn-Time-Desktop/

**Comment by 1337-537h** [comment]
I already have much newer version than the latest of the site (end of March).
I also want to continuous watch the progress and dl the latest versions.

**Comment by kiriles90** [comment]
Nothing anyone here can do about it. The website's status for the moment is what it says in the announcement that pops up when you try to visit it. You could either build it yourself from source or just wait and see what happens in the future.

**Comment by 1337-537h** [comment]
So that's  mean the development end until further notice?

**Comment by kiriles90** [comment]
Not necessarily but I'm not gona lie the current state of things is an issue, at least to my eyes. Anyway as long as the github repo is still here anyone can submit a PR and one of the collaborators might check and merge. If you noticed though development has slowed down by a lot lately anyway because of the simple reason almost all of the known issues have been fixed. Yeah there are a bunch of feature requests still open but considering the nature of the project I guess that will always be the case..?
