### ISSUE TITLE
Subtitle download not working

### ISSUE THREAD

**Issue by hojnikb** [popcorntime/popcorntime#2094]
Running on desktop Windows client, i'm not getting any subtitle options (just an X) unless i load them externally.
Am i doing something wrong or is this a known issue?

**Comment by dutchy1001** [comment]
have you set the "default" subtitle  in the settings?
Subtitles are 3rd party added so it could be that opensubtitle.org is/was down.

**Comment by hojnikb** [comment]
> have you set the "default" subtitle in the settings?
> Subtitles are 3rd party added so it could be that opensubtitle.org is/was down.

yep set default language as english. Must be something iffy with their hosting, although site itself works.

**Comment by dutchy1001** [comment]
I have found some movies without or limited subs. As a 3rd party api to compliment PCT there is noting our devs can do about. 
You already know how to add external subs, wich is a big +  you are still able to enjoy PCT.

**Comment by kiriles90** [comment]
If you still dont have subtitles try creating an account and login in opensubtitles in Popcorn Time's settings. If you still cant connect they might have your IP range blacklisted or your ISP have them blocked so you'll need something like a VPN to bypass it.

Closing this since its now an issue with the app.
