### ISSUE TITLE
Improper sorting of 'Favorites'

### ISSUE THREAD

**Issue by vdaenterprises** [popcorntime/popcorntime#2097]
Operating System Version:
Windows 10

Popcorn Time Version:
0.4.4

Download date:
2020

Download url (optional):

#### Expected Behaviour
Allow me to sort saved titles in alphabetical order AND then specify whether I want to view 'TV Series' titles, 'Movie' titles, or all of them combined.

#### Actual Behaviour
The desktop app allows me to sort alphabetically, but for some reason it has SOME of the movie and series titles added at the end (a double sort). Screenshot:
![Screenshot 2021-04-14 154141](https://user-images.githubusercontent.com/82520056/114720025-f0952380-9d37-11eb-9e22-0165f755273e.jpg)
Subsequently, when attempting to change the 'Type' to view only movie titles or TV series titles, I receive a blank page. In other words, I can only view all the bookmarked titles combined.

#### Steps to reproduce the behaviour

1. Bookmark various tv series and movies.
2. Sort Favorites by 'Title'.
3. Attempt to change Type to 'TV Series' or 'Movies'.

#### Screenshot(s) of issue or error(s) logs of developer console (Windows/Linux: F12, MacOS: ⌘ + 0 ... then 'console' tab) (recommended)
![Screenshot 2021-04-14 155843](https://user-images.githubusercontent.com/82520056/114722905-7dd97780-9d3a-11eb-80de-6d14f2b69eef.jpg)
![Screenshot 2021-04-14 155747](https://user-images.githubusercontent.com/82520056/114722911-7e720e00-9d3a-11eb-8efb-fb14bd79207b.jpg)
![Screenshot 2021-04-14 155545](https://user-images.githubusercontent.com/82520056/114722913-7e720e00-9d3a-11eb-983f-dc45785df91f.jpg)
![Screenshot 2021-04-14 155506](https://user-images.githubusercontent.com/82520056/114722916-7f0aa480-9d3a-11eb-9ead-fc15361759dd.jpg)
![Screenshot 2021-04-14 155319](https://user-images.githubusercontent.com/82520056/114722917-7f0aa480-9d3a-11eb-8e68-47bf86831f8e.jpg)

**Comment by kiriles90** [comment]
This has been fixed. You need to update to the latest build but ci. has been taken down since last week. You can either check the subreddit for mirrors or build it yourself from source (the development branch)

**Comment by vdaenterprises** [comment]
0.4.4 IS the latest build as far as I'm aware (you know, the one I'm using?), and then pointing out that the latest build has been taken down but I MIGHT be able to find a mirror for it or build it myself (which I don't have the skill to do)....wow, less than helpful is an understatement here. The Popcorn Time community has really become somewhat self-righteous as of late....sad to see such a great endeavour being driven to ruin by ego's.

**Comment by kiriles90** [comment]
> 0.4.4 IS the latest build

0.4.4 isnt a build number its a version. 0.4.4 release version that you have is build 413, the latest build is build 458

> then pointing out that the latest build has been taken down but I MIGHT be able to find a mirror for it

The website and everything on the .app domain have been taken down due to legal issues. Read the torrentfreak article. People host that stuff for no personal benefit so you and people like you dont need to learn to build from source then they end up with legal issues and multimillion lawsuits/threats. This happened again last week. Perhaps you'd like to be the next to host those websites/files, you are part of the community arent you?

> or build it myself (which I don't have the skill to do)

There is a guide which you can read -> https://github.com/popcorn-official/popcorn-desktop/wiki/Windows-Build-Instructions:-quick-version.

> The Popcorn Time community has really become somewhat self-righteous as of late....sad to see such a great endeavour being driven to ruin by ego's.

Indeed, you are doing a very good job at proving that.

P.s this isnt a support forum, that's what the subreddit and the forum are for. You opened an issue for something that has been fixed and you got the perfectly valid answer that you need to update your build which you might have been able to do like everyone else if you read one of the thousands of posts in github or closed issues here before you opened a new one or even after if you read and did what my reply above said instead of crying about your ego.

**Comment by dutchy1001** [comment]
Just to point out:

> less than helpful is an understatement here

I (we) have been answering most ppl within hours or sometimes within minutes with solutions to their issue or redirecting to the latest build so they can fix their problem, 9 out of 10 times with success. Unfortunately due to the legal issue's mentioned above by @kiriles90 there is nothing WE can do, but we would if we could.

To say that we aren't helpful here is an **INSULT** to all that give support here .

**Comment by vdaenterprises** [comment]
I apologize for my previous outburst. A combination of frustration combined with a lack of knowledge of the whole situation. The more detailed explanations by you both were much more appreciated. As for reading posts on Reddit....I signed up 3 months ago, requested access to the PT thread and never received a response. As a result, it's been hard finding out anything about what you've now explained....my apologies again....I'll try to locate a copy of the latest "build" and likewise have a look at the posted guide link.

**Comment by dutchy1001** [comment]
Not to worry, everybody can have an OFF day (special these days with all the world sh!t going on).

**Comment by kiriles90** [comment]
Check r/popcorntimeapp not r/popcorntime. The latter was set to private about 6months ago (legal reasons probably again though none is really sure afaik, the subs owner just set it to private one day and kicked out all the moderators) so the community moved on to the new one.

**Comment by vdaenterprises** [comment]
Thank you both. With the actual build number I managed to find the required threads with a simple search...from there found links, read the latest linked headlines, and downloaded. Will try it out in full shortly. I feel like such a dick....thanks for the undeserved courtesy after my outburst. 
![Thank-yiu-you-the-beth-thank-you-meme 1](https://user-images.githubusercontent.com/82520056/114779641-a717f900-9d76-11eb-9a75-190efea381d0.png)

**Comment by kiriles90** [comment]
No worries, an honesty apology is rare these days so its fully accepted from my part and all is good. Let us know below if you're still having issues, a closed/fixed issue doesn't mean the conversation must end too.

**Comment by dutchy1001** [comment]
What @kiriles90 just said I totally agree with as well. It makes a bigger person that can admit to a mistake. No worries if you need further help with PCT.

**Comment by vdaenterprises** [comment]
There are a few things I learned to believe fully in life:

- your word is your bond...keep it except in extreme circumstances (face it, we all know it can happen)
- treat others as you yourself want to be treated (except when they don't....then all bets are off)
- admit to your mistakes...again with the proviso of exceptional circumstances (sometimes the truth CAN do more harm).

Humility and a damaged ego are a much smaller price to pay than the price of lost reputation. I've tried to teach my kids these things but, "kids today"....time will tell.

Having said all that, being helpful to strangers AND accepting an apology is rare these days as well (especially online), so consider yourselves somewhat special also. Don't ever change that mentality because it's what this world desperately needs.
