### ISSUE TITLE
Popcorn doesnt load any movi or series.

### ISSUE THREAD

**Issue by mbjunqueiraweb** [popcorntime/popcorntime#2108]
Operating System Version:
Pop OS 20.10 - base ubuntu

Popcorn Time Version:
Popcorn-Time-0.4.4-linux64.zip

Download date:
2020-10-16

Download url (optional):

popcorntime.sh || github

#### Expected Behaviour

Show the list of mivies and series, but keep spinning a loading image.
#### Actual Behaviour

...Load the movies when you open the app.

#### Steps to reproduce the behaviour

1. ...Came to github, verified if exists any newer version
2. ...Deleted all my popcorn folders
3. ...Reinstalled the app following the instructions here on github.

#### Screenshot(s) of issue or error(s) logs of developer console (Windows/Linux: F12, MacOS: ⌘ + 0 ... then 'console' tab) (recommended)

![date-download-popcorn](https://user-images.githubusercontent.com/69853875/115479887-c653d200-a21f-11eb-9b91-9ecadcd42d0f.png)
![popcorn-image-running](https://user-images.githubusercontent.com/69853875/115479899-d075d080-a21f-11eb-8740-dcf3640f6649.png)

**Comment by kiriles90** [comment]
Check #2105. Closing since duplicate but you can comment in the other issue if you need more help. (its also closed because its not an issue with the app, its with the API and there isnt much anyone here can do about it, only the future will tell, in the meantime you can use other APIs, there is further explanation in #2105)
