### ISSUE TITLE
Popcorn time loading issue

### ISSUE THREAD

**Issue by alimarchant** [popcorntime/popcorntime#2109]
dude every time I open popcorn time version 0.4.4 it gets stuck and the loading spin keeps spinning.

help fix this please, this just started happening today
![x](https://user-images.githubusercontent.com/82922326/115491035-d91cd580-a224-11eb-9d6c-73a51fa022d8.png)

**Comment by kiriles90** [comment]
Check #2105. Closing since duplicate but you can comment in the other issue if you need more help. (its also closed because its not an issue with the app its with the API and there isnt much anyone here can do about it, only the future will tell, in the meantime you can use other APIs, there is more info on how to do that in #2105)
