### ISSUE TITLE
Bug: no content anymore

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [popcorntime/popcorntime#2137]
Operating System Version:
Windows 10

Popcorn Time Version:
Popcorn-Time-0.4.4-win64-Setup

Download date:
2021-04-27
From here:
https://github.com/popcorn-official/popcorn-desktop/releases

Download url (optional):
https://github.com/popcorn-official/popcorn-desktop/releases/download/v0.4.4/Popcorn-Time-0.4.4-win64-Setup.exe

#### Expected Behaviour
Should show stuff to watch

#### Actual Behaviour
Always loads. Nothing shown.

#### Steps to reproduce the behaviour
1. Open app.

#### Screenshot(s) of issue or error(s) logs of developer console (Windows/Linux: F12, MacOS: ⌘ + 0 ... then 'console' tab) (recommended)
![image](https://user-images.githubusercontent.com/5357526/116152090-277f1800-a6ee-11eb-9703-0a08ea8343a6.png)

**Comment by RoboticsRabbit** [comment]
**The official website, the forum site and the Dev build site have all been taken down probably due to the recently reported legal issue. [➝ Read here](https://torrentfreak.com/popcorn-time-plans-to-make-a-comeback-despite-legal-trouble-210423/)
There is now a workaround with all OS official builds hosted at http://popcorn-ru.tk/build/**

The following is a current list of issues which users are regularly posting about:

First step for any issue is to update to the latest working Dev build (see link above) (currently #458)

**Series not loading**

The official API is currently down so copy/paste https://popcorn-ru.tk/ into the 'Custom Series Server' (follow Movies not updating steps for help).

**Movies not updating**

Run the app then go to settings, check 'show advanced settings', find the API server section and copy/paste either https://yts.mx/ (VPN maybe required) or https://popcorn-ru.tk/ into the 'Custom Movies Server'.

Restart the app when prompted and this will 'fix' the current movies updating issue.

To change back to the default API, delete the text and restart the app.

**App not closing or Watch Now not responding**

You haven't updated to latest Dev build from link above.

**Movies/Series unavailable**

Use the search function in the Torrent Collection page. You can also copy/paste or drag/drop magnet/torrent links from other sites into the Torrent Collection page. If it's a series then search for a full season instead of individual episodes.

**Download not starting (stays on connecting)**

If the movie/episode has good health (green dot) then you'll probably need a VPN and if it has bad health (red dot) then use the Torrent Collection as detailed above.

**Subtitles**

Create an account on OpenSubtitles.org and add the details in the apps settings page.

**VPN prompt**

This is only a reminder / advert to use a VPN which can be removed by unchecking 'Enable VPN' in settings. If you have (or need) a personal VPN it will still work with the app.se of a legal issue and the old app version 3.1

Copied from the r/Popcorntimeapp Reddit **https://www.reddit.com/r/PopCornTimeApp/**

**Comment by AndroidDeveloperLB** [comment]
@RoboticsRabbit @kiriles90 Seems working now, but Anime doesn't load, and subtitles work fine without a login.

**Comment by RoboticsRabbit** [comment]
> @RoboticsRabbit @kiriles90 Seems working now, but Anime doesn't load, and subtitles work fine without a login.

Yeah Anime is an area where I don't think they have a solution yet, but once they get the website back or make a new one (not sure how they gonna be doing that, there might be a fix)

There might be some solution on the reddit, so check there maybe... It might take slightly longer to get that back, because there are not that many anime servers.

**Comment by AndroidDeveloperLB** [comment]
@RoboticsRabbit Thank you very much.
