### ISSUE TITLE
Better Scrubbing

### ISSUE THREAD

**Issue by PsycloneTM** [popcorntime/popcorntime#2168]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated with the fact that I cant see what scene I'm jumping to. Most video players nowadays have a good scrubbing feature.

**Describe the idea you'd like**
I would like you to add a scrubbing feature close to or better then what YouTube has. I know this is easier said then done I'm sure its been talked about before but its just something I noticed you don't have and if you don't say anything then it will never get done.

**Describe alternatives you've considered**
I don't really see any alternatives you could do to make this its pretty straight forward no way around it.

**Additional context**
![](https://i.imgur.com/pMhnx33.png)

**Comment by kiriles90** [comment]
Realistically this isn't possible. Youtube uses pre-rendered low quality thumbnails that it generates when people upload a video. Popcorn Time uses torrents that it fetches from third party providers it has no control over so pre-generated thumbnails cached "somewhere" isnt an option. Even worse if this could somehow be done on-the-fly on the client part (not a good idea due to the extra resources necessary) most of the time the part you try to skip to isn't even downloaded. How would it have a thumbnail of a not downloaded part of a video that it didn't knew it had to play until now?

Closing until someone has a feasible proposal on how this could be done.
