### ISSUE TITLE
Popcorn-Time doesn't work with macOS 12

### ISSUE THREAD

**Issue by jamesf-hub** [popcorntime/popcorntime#2192]
Operating System Version:

macOS 12 Developer Beta 1

Popcorn Time Version:

PT #557

Download date:

Today, after reinstalling

Download url (optional):

#### Expected Behaviour

Launch.
...

#### Actual Behaviour

Quits.
...

#### Steps to reproduce the behaviour

1. Open app
2. Quits
3. ...

**Comment by kiriles90** [comment]
Is it an M1 device that you are testing this on? Any errors when it quits? Either way its still probably nwjs requiring an update, for which there is already an open issue/feature request for some time now.

**Comment by dutchy1001** [comment]
Please read issue #2105, this count for all versions

**Comment by jamesf-hub** [comment]
> Please read issue #2105, this count for all versions

This is different, Application is crashing

**Comment by jamesf-hub** [comment]
> Is it an M1 device that you are testing this on? Any errors when it quits? Either way its still probably nwjs requiring an update, for which there is already an open issue/feature request for some time now.

It just crashes without error logs

**Comment by kiriles90** [comment]
Well, M1 devices aren't natively supported at the moment. They only work via translation. Additional to this you are using a beta operating system. There is already an open feature request to update the nwjs version we are using, that will (provided we update to a recent enough version) solve this support issue too. It will create other issues though, almost all major jumps in nwjs version do, so its not really a top priority right now. If someone wants to have a go at it and fix all the issues that will arise, just clone the repo, update nwjs, fix the bugs that this will create, and make a PR. After that someone will have to compile that new version to enable the extra codecs, and upload it somewhere for Popcorn Time to build with. Closing this since there is not much else to do about the issue.

**Comment by jamesf-hub** [comment]
mid2015 MBP Monterey.

Latest build through Actions continues to crash

**Comment by Ge0rges** [comment]
Same here on v0.4.6
