### ISSUE TITLE
Error: getaddrinfo ENOTFOUND wehen trying to build using yarm

### ISSUE THREAD

**Issue by MatheoDumont** [popcorntime/popcorntime#2194]
Operating System Version:

Linux mint 
Popcorn Time Version:

Last on dev
Download date:

Today
Download url (optional):

#### Expected Behaviour

I was trying to build using yarn 

#### Actual Behaviour

```
$ yarn gulp build
yarn run v1.22.10
$ /home/matheo/Documents/popcorn-desktop/node_modules/.bin/gulp build
[18:25:50] Using gulpfile ~/Documents/popcorn-desktop/gulpfile.js
[18:25:50] Starting 'build'...
[18:25:50] Starting 'injectgit'...
Branch: development
Commit: 4b759320
[18:25:50] Finished 'injectgit' after 23 ms
[18:25:50] Starting 'css'...
Stylus files compiled in /home/matheo/Documents/popcorn-desktop/src/app/themes/
[18:25:55] Finished 'css' after 4.95 s
[18:25:55] Starting 'nwjs'...
{ Error: getaddrinfo ENOTFOUND popcorntime.app popcorntime.app:443
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:56:26)
  errno: 'ENOTFOUND',
  code: 'ENOTFOUND',
  syscall: 'getaddrinfo',
  hostname: 'popcorntime.app',
  host: 'popcorntime.app',
  port: 443 }
[18:26:17] Finished 'nwjs' after 22 s
[18:26:17] Starting '<anonymous>'...
[18:26:17] Finished '<anonymous>' after 722 μs
[18:26:17] Finished 'build' after 27 s
Done in 27.89s.
```
did i miss something? thnaks !

**Comment by MatheoDumont** [comment]
Or the domain is not reachable ?

**Comment by kiriles90** [comment]
Yes its because the domain is down. As a temporary workaround check Ivan's reply to https://github.com/popcorn-official/popcorn-desktop/issues/2105#issuecomment-830823755 (or ofc you could build using the default nwjs location, up to version 0.49 afaik, but you'll be missing on the extra proprietary video codecs that [arent enabled in the prebuild nwjs binary](https://docs.nwjs.io/en/latest/For%20Developers/Enable%20Proprietary%20Codecs/#enable-proprietary-codecs-in-nwjs))

**Comment by MatheoDumont** [comment]
Thanks !
