### ISSUE TITLE
Application does not open on MacOS Monterey 12.0 Beta

### ISSUE THREAD

**Issue by marky291** [popcorntime/popcorntime#2230]
Although this is only beta, it will need to be fixed for next operating system.

Operating System Version:
MacOS Monterey 12.0 Beta

Popcorn Time Version:
0.4.5

Download date:
4th July 2021

Download url (optional):
https://github.com/popcorn-official/popcorn-desktop/releases/tag/v0.4.5

#### Expected Behaviour
Application opens with error
...

#### Actual Behaviour
Application asks to accept incoming connections then does nothing. (Never opens)
...

#### Steps to reproduce the behaviour
Install MacOS Monterey 12.0 Beta and application, then open.

#### Screenshot(s) of issue or error(s) logs of developer console (Windows/Linux: F12, MacOS: ⌘ + 0 ... then 'console' tab) (recommended)
<img width="591" alt="Screenshot 2021-07-04 at 19 24 45" src="https://user-images.githubusercontent.com/5384515/124395712-7ef8c000-dcfd-11eb-8850-b997e3b62788.png">
<img width="270" alt="Screenshot 2021-07-04 at 19 25 21" src="https://user-images.githubusercontent.com/5384515/124395735-95068080-dcfd-11eb-85d3-8d66f3bc8e62.png">

**Comment by kiriles90** [comment]
Its an nwjs issue. When they release a version with a fix Popcorn Time can compile it to include the extra codecs, fix any bugs the update will cause and release a new version. Until then not much can be done about it its not Popcorn Time code thar crashes the app. Closing this since there is already an open issue about updating nwjs.
