### ISSUE TITLE
Brew installation does not work on Mac Big Sur

### ISSUE THREAD

**Issue by maelsan** [popcorntime/popcorntime#2242]
Operating System Version:

Mac Big Sur `11.4`

Popcorn Time Version:

`0.4.5`

Download date:

Today, with:

`brew tap popcorn-official/popcorn-desktop https://github.com/popcorn-official/popcorn-desktop.git`

Download url (optional):

#### Expected Behaviour

Executing these two commands [from the README](https://github.com/popcorn-official/popcorn-desktop#macos) should correctly install PopcornTime: 

```shell
brew tap popcorn-official/popcorn-desktop https://github.com/popcorn-official/popcorn-desktop.git
brew install --cask popcorn-time
```

#### Actual Behaviour

Executing these two commands will result in an error in the terminal:

<img width="1674" alt="Screenshot 2021-07-12 at 1 01 28 PM" src="https://user-images.githubusercontent.com/7117292/125277308-8f1e2a00-e311-11eb-9a85-918b94b21e34.png">

#### Steps to reproduce the behaviour

1. Execute the first command as mentionned in the README: `brew tap popcorn-official/popcorn-desktop https://github.com/popcorn-official/popcorn-desktop.git`
2. Then the second one: `brew install --cask popcorn-time`
3. You should then have an error message without popcornTime installed on your system.

**Comment by kiriles90** [comment]
Is the path to that file `/Popcorn-Time/User Data/Default/data/settings.db` instead of `/Popcorn-Time/Default/data/settings.db` ?

**Comment by kiriles90** [comment]
Is the path to that file `/Popcorn-Time/User Data/Default/data/settings.db` instead of `/Popcorn-Time/Default/data/settings.db` ?

@danielbayley @shekhardesigner any insight?

**Comment by daniel-sphereo** [comment]
+1

**Comment by long2ice** [comment]
Same here

**Comment by kiriles90** [comment]
@maelsan @daniel-sphereo @long2ice Can someone please check and see if that file that is looking for is actually in `/Popcorn-Time/User Data/Default/data/settings.db` instead of `/Popcorn-Time/Default/data/settings.db` and that's why you are getting the error? If you can confirm this is the issue I can make the change myself, if not, we will have to wait for a macOS user to confirm this.

**Comment by marcelrodrigo** [comment]
same

**Comment by frank3stein** [comment]
I have the same issue, m1 macbook air

```bash
==> Downloading http://popcorn-ru.tk/build/Popcorn-Time-0.4.5-Mac.zip
Already downloaded: /Users/xxxx/Library/Caches/Homebrew/downloads/5cd843802ade9d9845834cec202709e75d189751bd9fe79135fb36a114733497--Popcorn-Time-0.4.5-Mac.zip
==> Installing Cask popcorn-time
==> Moving App 'Popcorn-Time.app' to '/Applications/Popcorn-Time.app'
==> Backing App 'Popcorn-Time.app' up to '/opt/homebrew/Caskroom/popcorn-time/0.
==> Removing App '/Applications/Popcorn-Time.app'
==> Purging files for version 0.4.5 of Cask popcorn-time
Error: No such file or directory @ rb_sysopen - /Users/xxxx/Library/Application Support/Popcorn-Time/Default/data/settings.db
```

**Comment by hchauvat** [comment]
Hi, 
Same problem here.

It also seems that there is no `Popcorn-Time` folder in `/Users/xxxx/Library/Application Support`. Could this be an indication that something broke before reaching this step? Should we try creating the missing folders and file to see if it "unblocks" the installation?


**EDIT**: I can confirm that by doing so, I was able to continue the installation and run PCT.
The commands I ran:
```bash
mkdir -p /Users/xxx/Library/Application\ Support/Popcorn-Time/Default/data
touch /Users/xxx/Library/Application\ Support/Popcorn-Time/Default/data/settings.db
brew install --cask popcorn-time
```

**Comment by kiriles90** [comment]
I'm not sure what @danielbayley messed up but that settings.db file isn't supposed to exist for a clean install. As for when its not a clean install it should normally be in that directory so no error. Since I don't think he is coming back anytime soon, if someone else can confirm a fix for the brew installation just let me know and I can merge it. Other than that sorry I cant help much, I'm not a macOS user so I cant even test some of the possible solutions.

**Comment by nicocossiom** [comment]
Yeah same issue here in MBPro M1. This was the error shown. 
==> Installing Cask popcorn-time
==> Moving App 'Popcorn-Time.app' to '/Applications/Popcorn-Time.app'
==> Backing App 'Popcorn-Time.app' up to '/opt/homebrew/Caskroom/popcorn-time/0.4.5/Popc
==> Removing App '/Applications/Popcorn-Time.app'
==> Purging files for version 0.4.5 of Cask popcorn-time
Error: No such file or directory @ rb_sysopen - /Users/nicolas_cossio/Library/Application Support/Popcorn-Time/Default/data/settings.db

**Comment by WoefulWrecker** [comment]
MacOS Sur 11.5 intel
XXXXXX@iMac ~ % brew tap popcorn-official/popcorn-desktop https://github.com/popcorn-official/popcorn-desktop.git
brew install --cask popcorn-time
Updating Homebrew...
==> Auto-updated Homebrew!
Updated 1 tap (homebrew/core).
==> Updated Formulae
Updated 2 formulae.

==> Downloading http://popcorn-ru.tk/build/Popcorn-Time-0.4.5-Mac.zip
######################################################################## 100.0%
==> Installing Cask popcorn-time
==> Moving App 'Popcorn-Time.app' to '/Applications/Popcorn-Time.app'
==> Backing App 'Popcorn-Time.app' up to '/usr/local/Caskroom/popcorn-time/0.4.5
==> Removing App '/Applications/Popcorn-Time.app'
==> Purging files for version 0.4.5 of Cask popcorn-time
Error: No such file or directory @ rb_sysopen - /Users/XXXXXX/Library/Application Support/Popcorn-Time/Default/data/settings.db

> Ok, I had the same problem and found a way to get around it.
> 
> After running the two commands and getting the error:
> In the Finder, I went to `~/Library/Caches/Homebrew/downloads/` and found the .zip.
> Just had to unzip it, move the app in my Applications folder, and ctrl + open. 👍

The remote movies API failed to respond, please check "movies-v2.api-fetch.sh" and try again.

**Comment by kiriles90** [comment]
https://github.com/popcorn-official/popcorn-desktop/pull/2288 hopefully fixed this. Closing this issue for now.

**Comment by JntSlvDrt** [comment]
This is happening because of the space between in "Application Support", it should be "Application\ Support" @kiriles90 Take a look at this, could be that simple thing, I just dont know how to change that in the installation process ˆˆ

For now what you guys can is to QUIT terminal exactly when it reads:
==> Backing App 'Popcorn-Time.app' up to '/opt/homebrew/Caskroom/popcorn-time/0.4.6/Popcorn-Time.app'
That way it wont be removing the app neither purging the files.
