### ISSUE TITLE
[FR] Add option to prioritize download of beginning and end of file

### ISSUE THREAD

**Issue by vdurante** [popcorntime/popcorntime#2254]
**Is your feature request related to a problem? Please describe.**
I enjoy using MPC-HC, specially since it is integrated with opensubtitles org and it usually has better subtiles for my native language. Unfortunately, MPC-HC uses a hash of the beginning and end of the file to search for subtitles on its api, making it hard to use the subtitle feature since the end of the file is not in popcorn's download priority.

**Describe the idea you'd like**
I see 2 possible solutions:
1. automatically make downloading the end of the torrent a priority when opening the torrent on an external player
2. add an advanced option to enable/disable this option from the menu

**Describe alternatives you've considered**
Atm I either have to manually download multiple subtitles on opensubtitles and try them until I find one that fits my needs or I have to wait the whole movie be downloaded on popcorn

**Additional context**
This could also be an issue on other players, since this hashing methods delivers the most precise match with subtitle APIs and makes it way easier to find a good subtitle.

**Comment by kiriles90** [comment]
Closing because after taking a closer look at this, its not possible as far as I can see using WebTorrent internals. A fix would be a hacky one on Popcorn Time's side and it wont even solve the original problem this issue was opened for since Popcorn Time serves a local stream to the external players not a file (if I'm mistaken in any of the above and there is indeed a good way and a valid use for this just say so and I'll reopen)
