### ISSUE TITLE
[FR] Pass the file name or similar to external players

### ISSUE THREAD

**Issue by vdurante** [popcorntime/popcorntime#2255]
**Is your feature request related to a problem? Please describe.**
(this issue is somewhat complementary #2254)
I enjoy using MPC-HC, specially since it is integrated with opensubtitles org and it usually has better subtitles for my native language. Unfortunately, MPC-HC the filename as fallback for searching for subtitles when hashing of the file data is not available. Since popcorn doesn't share the file name (or similar) with MPC-HC, it becomes impossible to search for subtitles on it.

Here is what is being shared with MPC:

![image](https://user-images.githubusercontent.com/5401232/127025984-afe5518a-3c1f-43cb-a770-4744d62de84f.png)

**Describe the idea you'd like**
I would like popcorn to somehow share the file name with MPC-HC, so it can properly search for subtitles.

**Describe alternatives you've considered**
Atm I either have to manually download multiple subtitles on opensubtitles and try them until I find one that fits my needs or I have to wait the whole movie be downloaded on popcorn

**Additional context**
This could also be an issue on other players.

**Comment by kiriles90** [comment]
Popcorn Time does pass the filename to external players e.g for VLC is https://github.com/popcorn-official/popcorn-desktop/blob/78f3d473b6e6037af68e84ee0adbd25b3054bc33/src/app/lib/device/ext-player.js#L16  

I might be wrong but I don't see any command line switch that can pass a title name to MPC-HC (Help > Command line switches in the MPC-HC player window). This is necessary because Popcorn Time doesn't send a file to the external player, it sends a stream URL (e.g http://[your local IP]:[local port number]/[file index]) so the filename has to be given like this.

Closing this issue since not much can be done if MPC-HC doesn't have this feature but if I'm wrong let me know and I'll reopen it and try to merge a fix.

**Comment by vdurante** [comment]
thank you so much for the answer!

I tried to contact MPC-HC on this [issue](https://github.com/clsid2/mpc-hc/issues/1216), but there seems to be no option. Is the file streamed to MPC-HC, hence no filename?

**Comment by kiriles90** [comment]
@vdurante Yes, Popcorn Time sends a local stream to the external players (the one you see in the loading screen) not a file, so the actual filename has to be passed as a title or something similar.
