### ISSUE TITLE
V.0.4.5 does not load

### ISSUE THREAD

**Issue by jimsuev** [popcorntime/popcorntime#2256]
![Screenshot 2021-07-24 152627](https://user-images.githubusercontent.com/63857454/127171385-72bffda3-d1a8-4ac4-9d95-75cc7c4ef8fb.jpg)
Downloaded and installed both the V.0.4.5_win64 and update, once Popcorn Time opens, I get this screen. I click on the weblink in the screen and get the message, Hmmm… can't reach this pageCheck if there is a typo in movies-v2.api-fetch.sh.
If spelling is correct, try running Windows Network Diagnostics.
DNS_PROBE_FINISHED_NXDOMAIN

Is there a newer version or fix for what is available?

**Comment by kiriles90** [comment]
Check the [FAQ](https://github.com/popcorn-official/popcorn-desktop/wiki/FAQ)

**Comment by andresmmujica** [comment]
I'm having the same error, I know the solution is to change the API server, but why did you close the issue without at least which api server use?  am I missing something?

**Comment by kiriles90** [comment]
@andresmmujica Because there are at least 40 more closed issues like this one by people who don't read the pinned issue (#2105), or the [FAQ](https://github.com/popcorn-official/popcorn-desktop/wiki/FAQ), or try clicking that 'Change API server' button in the middle and selecting one of the pre-set choices since not being able to reach the default API server is the issue here.
