### ISSUE TITLE
Composite lexicographic sort order

### ISSUE THREAD

**Issue by eyalroz** [popcorntime/popcorntime#2263]
**Describe the idea you'd like**
Instead of being able to specify just one axis/feature by which to sort, it should be possible to specify a lexicographics sorting order - an order of significance among the different axes/features, and an up/down indication for each regarding the direction of sorting.

**Describe alternatives you've considered**
"Sort by X, then by "Y - the UI would be simpler than a full-fledged composite sort order.

**Additional context**
Currently looking at v0.4.5b

**Comment by kiriles90** [comment]
So the same (or very similar) as #2262 ? Can we close this and include anything I'm missing in the other issue?

**Comment by eyalroz** [comment]
@kiriles90 : No, not at all. One is about ordering, the other is about filtering.

**Comment by kiriles90** [comment]
Because making 150 general API calls of 25 movies each to filter out 3 movies locally is not the way to go? :smile:

**Comment by kiriles90** [comment]
Same issue, this has to be done API side. Sorting is even worse than the filters. It wont even work correctly if done locally.

**Comment by eyalroz** [comment]
@kiriles90 : Why is it the same issue? Here, given the screen you currently fill based on your first/most-major axis sort order, you just need to sort the items with no extra API calls. The server is none the wiser.

**Comment by kiriles90** [comment]
Same issue as in same problem
> this has to be done API side

Ok.., lets say I filter out movies by rating, I want 7+ only, and I make 10 API calls, get 250 movies, 30 of them are 7+ and are displayed, then I sort those by year. This sorting has no meaning, its 30 random movies since this 'sort by year' wasnt done API-side. When you scroll down a couple of times, and load 250 more movies, and filter them, and get 20 7+ back, then those logically should be automatically sorted by year too, which will pretty much make them appear in between the 30 already loaded ones in random places depending on the new one's year, then same when you scroll down more. This is just a simple issue of the top of my head with one of the sorters you want to use client-side, others might be even more problematic. And all this is forgetting the excessive API calls and all the data you pretty much ask for then throw away on the client.

I suggest checking a bit how the currently available APIs work, and code some simple calls, you don't even need Popcorn Time for it even a browser will do, then try to sort them or filter them locally in a way that would make sense, update them, add more filters, sorters etc locally, and you'll immediately see many of the way too many issues with it.

**Comment by eyalroz** [comment]
> Ok.., lets say I filter out movies by rating

Let's not say that. This feature request is about sorting, only. So let's say you don't filter out anything. 

So, you make 10 API calls and get 250 movies. For each of these movies you know the Year, Date Added, Rating etc. Now just sort them lexicographically by the order the user specified. That's it. Easy peasy.

**Comment by kiriles90** [comment]
You opened another issue about filters at the same time as this so I think we both understand the example I'm describing.

And what about when I load 250 more, or 25 more?

>  appear in between the 30 already loaded ones in random places depending on the new one's year

**Comment by eyalroz** [comment]
> And what about when I load 250 more, or 25 more?

This point clinches it. I was ignoring it. Sorry.

**Comment by kiriles90** [comment]
No worries. If you want open an issue at the API repo and maybe the RU API repo (since its the one online and most active atm) whatever Ivan has metadata for and can add can be then easily added in the app.
