### ISSUE TITLE
Multiple download option for series

### ISSUE THREAD

**Issue by dutchy1001** [popcorntime/popcorntime#2308]
As we can already download multiple movies and series you have to click each one separate. For movies this isn't an issue but what if you want a series downloading? Each time you need to go back and click the next episode to download.
I know there is an option "Play next episode automatically" but then you have to watch them strait away (as far I know this option isn't working properly, but that's not the point atm). 

Could there be an option to click multiple episodes and then download at once?

**Comment by kiriles90** [comment]
Not sure how this would account for the fact that some of the series are full season torrents without making a mess of things but it can probably be done. @ivan1986 any ideas?

**Comment by ivan1986** [comment]
I think need only add two buttons - download season and download all
for now if we select all episodes step by step and click dowload we get all season, it works because we add selection of file and need only elect all files.
Because usually torrent it's all season or all serial this will be work perfect.

**Comment by dutchy1001** [comment]
I would suggest for only "per season". If someone wants to do all seasons then the chance that there are missing episodes is a lot bigger and ppl will then complain about that. Yes this also possible when downloading 1 season but the disappointment will be less then when you watched 2 seasons and finding out season 3 is not complete.

Either way I think it's a big plus for PCT if this is possible.

**Comment by MCUxDaredevil** [comment]
Yes it would be a very useful feature to download whole seasons at once instead of going after individual episodes.
Some series have a lot of seasons and a lot more episodes in each season. So download each episode individually is very tiring and stressful. Instead just a download button for each season at the top would be very helpful.

**Comment by FireFox53** [comment]
I guess one of you got your wish, I do not want to down load the whole series at once. Some series I can pick as many episodes I wish to download others it automatically downs all. I do want this as it takes up to much my free space.

**Comment by kiriles90** [comment]
@FireFox53 what version/build are you using? Get the latest build from the 'Actions' page and check if its fixed. (atm 0.4.6+217.g https://github.com/popcorn-official/popcorn-desktop/commit/426e8d6ac49c670741620120866afca7c36786a7)

**Comment by kiriles90** [comment]
Closing this for now. Not sure it can be implemented in a cohesive way even if someone manages to.code it since the presence of the 'more..' button and mixed full season and single episode torrents if combined with this complicate things too much (the code as well as the UI/UX)
