### ISSUE TITLE
Episode list from favorites remain empty / renders incorrect

### ISSUE THREAD

**Issue by jorkzijlstra** [popcorntime/popcorntime#2338]
Operating System Version: 

Popcorn Time Version: 0.4.6

Download date: Nov 5 2021 (Upgraded from 0.4.4)

Download url (optional):

https://github.com/popcorn-official/popcorn-desktop/releases/download/v0.4.6/Popcorn-Time-0.4.6-linux64.zip

#### Expected Behaviour

Show the complete episode list
![image](https://user-images.githubusercontent.com/15804835/140577016-2eae313b-9135-434b-a0cd-15d93b0d76c5.png)

#### Actual Behaviour

![image](https://user-images.githubusercontent.com/15804835/140576984-2e39efa3-7ae1-45c2-9dbb-6856a9913a75.png)
![image](https://user-images.githubusercontent.com/15804835/140577494-38f2658a-03dc-4fd4-9fef-97653b97ce16.png)

#### Steps to reproduce the behaviour

1. Install 0.4.4
2. Save a series as favorites
3. Install 0.4.6
4. open the favorite and it show an empty episode list (see above error)

Workaround:
1) On tab series it shows the correct list
2) Resave into favorties

**Comment by dutchy1001** [comment]
This seems something I had as well, removing and re-add the series did fix this (windows version). Not sure if you update to the latest build will fix this.

**Comment by jorkzijlstra** [comment]
As stated in workaround option 2 re-adding it does seem to work but since I have some favorites this would be a hassle to do. 

in the console the show series ID does seem to be the same

**Comment by kiriles90** [comment]
@jorkzijlstra @dutchy1001 can you update to https://github.com/popcorn-official/popcorn-desktop/commit/104be4bcdf335312ed7a06c6cc4bb5d1a87284b6 then run the rebuild function and see if the issue was resolved?

**Comment by kiriles90** [comment]
@jorkzijlstra @dutchy1001 It seems the rebuild function had more issues (https://github.com/popcorn-official/popcorn-desktop/commit/104be4bcdf335312ed7a06c6cc4bb5d1a87284b6, https://github.com/popcorn-official/popcorn-desktop/commit/600aabf0003e1c823ad6161070cd7c7ed16ebd4d & https://github.com/popcorn-official/popcorn-desktop/commit/46a5196e0f27b938fa7b28a63ca19ea5715808f0)  
Can you update to the latest build (https://github.com/popcorn-official/popcorn-desktop/commit/46a5196e0f27b938fa7b28a63ca19ea5715808f0 atm) and re-run the rebuild function and see if the issue was resolved?

**Comment by dutchy1001** [comment]
As far I know I have updated after I had this issue and it did not happen again.
