### ISSUE TITLE
Very high memory usage

### ISSUE THREAD

**Issue by recapir** [popcorntime/popcorntime#2345]
Hi, I have an old Core 2 Duo 4GB laptop running Windows 8.1 and PT 0.4.6 that I use for media playback. But  I've been getting system running out of memory warnings. Nwjs memory usage is very high and has gone near 3Gigs on occasion. See atached image. If any logs are needed I'll be happy to provide them (will probably need instructions though). Thanks!

![memory](https://user-images.githubusercontent.com/94152584/141398271-16c70963-1ae1-4d13-860a-4f9aefcbcefd.png)

**Comment by kiriles90** [comment]
It's not Popcorn Time or nwjs that causes it, its WebTorrent. You can open an issue in their repo if you want but since we are using the latest version and the memory usage issue has been mentioned a number of times over the years I wouldn't hold my breath that it will/can be resolved/improved any time soon.
