### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by Franck78** [popcorntime/popcorntime#2355]
Operating System Version:

Linux OpenSuse 

Popcorn Time Version:

0.4.6

Download date:

November 2021

Download url (optional):

github

#### Actual Behaviour

Some TV shows have the abality to totally screw the system by requesting chunk by chunk all the memory !

#### Steps to reproduce the behaviour

TV show "Invasion" episode 9 season 1 shows the problem.
http://image.tmdb.org/t/p/w500/7rpiHZx10Nm50AtzTUEO9eyaKdq.jpg

1. Search for Invasion TV show
2. .Select s1ep9
3. .Start watching

Some other shows seems also to act weirdly. They also freeze the linux machine, you can see the initial horizontal progress bar stop moving for 3 minutes or have hicups while none of the counters evolve.
Sometimes it reaches 100% download and the bar keep moving. Or the percentage is 12% for 2 minutes and jumps to 80% and freezes again.

Two images : rapid memory usage at starting Popcorn
then completly screewed machine, no more memory !!

![popc-memOK](https://user-images.githubusercontent.com/1778884/144685930-2c091a86-3f89-4736-8da7-4bd653562bc4.png)
![popc-memSCREWED](https://user-images.githubusercontent.com/1778884/144685931-a3de852a-cee0-49ed-a9aa-9b2a5e6783fc.jpg)

**Comment by kiriles90** [comment]
Did you enable 'Protocol Encryption' in the settings because the current implementation will cause high CPU usage on the same thread the UI is on and as a result it has the potential to cause UI lag and freezes on certain systems.  

As for the high ram usage.. its mostly WebTorrent from previous testing done. How much ram does the specific device have? 4GB? Because if that's the case.. its an issue.

**Comment by Franck78** [comment]
Nop!
no encrypt, no vpn, no changes in this defaults for.

Basic laptop with 4GB ram split 3.8 and 256Mo for video.

Most of the shows are fine. I will try again Invasion and tell you if something changed.

F.

**Comment by Franck78** [comment]
just retried Invasion, same as yesteday.

That a screenshot about 2 minutes after starting. Progress bar is freezed , memory swap is slowly growing in use, more and more lag , barely launched the printscreen utility !


![pop-goingbad](https://user-images.githubusercontent.com/1778884/144708331-542bce0b-0872-4cf3-a270-1e66e860d8e6.png)

**Comment by kiriles90** [comment]
Maybe its something with the specific torrent that causes it? In either way, Popcorn Time just does a [App.WebTorrent.add](https://github.com/webtorrent/webtorrent/blob/master/docs/api.md#clientaddtorrentid-opts-function-ontorrent-torrent-) in every scenario where you start downloading or playing something and that's it so its something related to WebTorrent's internals not Popcorn Time's code. Given that we are pretty much using the latest version for some time now there's not much else to be done about it (if the devs at WebTorrent even consider this a bug)

As for the crashes and freezing (if you are using the default settings) its probably the fact that you are running out of memory. 4GB isn't much at all these days, even for a phone.

Closing this for now since there not much anyone here can do about it and switching from WebTorrent to something else (what?) is not very realistic at the moment.

**Comment by Franck78** [comment]
webtorrent says
```
As a command line app

WebTorrent is also available as a command line app. Here's how to use it:

$ npm install webtorrent-cli -g
$ webtorrent --help
```

do you have any idea how to call it from inside the node_modules installed by Popcorn app ? Where do I get the torrentID from Popcorn ?

**Comment by kiriles90** [comment]
`App.WebTorrent` to call it from Popcorn Time's (NW.js's) console since you'll need something to run the module and for their desktop app you can find it at the [webtorrent/webtorrent-desktop](https://github.com/webtorrent/webtorrent-desktop) repo (still runs on Node and Chromium which basically is what makes up NW.js)

**Comment by Franck78** [comment]
I think they are aware of some memory problems:

https://github.com/webtorrent/webtorrent/issues/1973

**Comment by aha999** [comment]
EndeavourOS, KDE 5.24, Intel i7-4770, 8GB ram, Popcorn-0.4.7

When running the app, and not playing anything, CPU usage is up to 10%, but it fluctuates all the time.
When playing anything, it causes high CPU usage and it jumps from 30 - 80% but can go to 100 and freeze my PC completely, the latter happens sometimes. Popcorn is the only app that does this to my PC.

**Comment by Franck78** [comment]
Not a good news if still happening with 0.47. 

It means no 'external' package was updated ? I need to check. 

Easy with the shitty encoding you can find. 3,5 Gbyte for a basic 40minute 720hd....


Well, 9 minutes. It's the time it takes to completly screw my Linux system (with 0.47).

The p2p module is so bad that I use the magnet link + kde (ktorrent) to download. And yes, with ktorrent, no problem of any sort.
This java thing is so screwed that even a simple thing as the progress bar is buggy. It can stay at the same percentage for minutes, even at 100% and nothing !!!!
