### ISSUE TITLE
App crashes under Monterey

### ISSUE THREAD

**Issue by Aluhut** [popcorntime/popcorntime#2365]
Operating System Version:
OS X 12.1 Monterey

Popcorn Time Version:
0.4.6
Download date:
yesterday

Download url (optional):
homebrew

#### Expected Behaviour
start and open a window

#### Actual Behaviour
instead of opening a window it crashes

#### Steps to reproduce the behaviour

1. .install
2. start (right click open)
3. watch it crash and cry

im unsure what to show :/

**Comment by kiriles90** [comment]
Its a known issue with the current version of NW.js that Popcorn Time uses. Not much else to do other than update it but due to it being a custom compiled version with extra codecs that's not as straightforward as it sounds.

Closing this issue since there is already an open issue about it https://github.com/popcorn-official/popcorn-desktop/issues/2062

**Comment by Kief5555** [comment]
https://youtu.be/3IZid6lBMJM I have a fix, you can watch from the link.
