### ISSUE TITLE
butterproject.org is a dead site redirect

### ISSUE THREAD

**Issue by Dreamedc2015** [popcorntime/popcorntime#2372]

**Comment by Dreamedc2015** [comment]
license has the link at the top

**Comment by kiriles90** [comment]
Butter Project was shutdown yes but Popcorn Time still has a lot of code from using it as a base back in 2016.  

I'm not sure if we should change any of that, and even then it wont matter much since that's the GNU GPL license, generally a "copyleft" license just used to indicate that this is an open-source project that anyone can distribute or fork freely.
