### ISSUE TITLE
App doesn't start: FATAL: Failed to load node library

### ISSUE THREAD

**Issue by ghost** [popcorntime/popcorntime#2483]

**Comment by kiriles90** [comment]
The issue is caused by libatomic missing.
Check the relevant section in [README.md](https://github.com/popcorn-official/popcorn-desktop#linux---debianubuntu-based-distros) and older similar issues (e.g https://github.com/popcorn-official/popcorn-desktop/issues/2368, https://github.com/popcorn-official/popcorn-desktop/issues/1506, https://github.com/popcorn-official/popcorn-desktop/issues/1419) for more info.

**Comment by rany2** [comment]
This should be reopened, there is a missing dependency to `libatomic1` for the Debian package.

**Comment by dutchy1001** [comment]
This is an issue from a very old version (0.4.7) and will not be reopened.

If you have the same or simular issue in a **[dev build version](https://github.com/popcorn-official/popcorn-desktop/actions/runs/5874418704)** of 0.4.9 then make a new bug report with the info asked when filling in the report.
