### ISSUE TITLE
Remote API failed to respond?

### ISSUE THREAD

**Issue by kiran-vemuri** [popcorntime/popcorntime#2493]
Operating System Version:

MacOS Monterey

Popcorn Time Version:

0.4.7 installed via homebrew

Download date:

May 2 2022

Download url (optional):

#### Expected Behaviour

Show a list of movies, tv shows

#### Actual Behaviour

Shows a message `Remote API failed to respond`

#### Steps to reproduce the behaviour

1. Installed the app via homebrew
2. Opened the app
3. ...

#### Screenshot(s) of issue or error(s) logs of developer console (Windows/Linux: F12, MacOS: ⌘ + 0 ... then 'console' tab) (recommended)

![Screenshot 2022-05-03 at 12 49 19 AM](https://user-images.githubusercontent.com/1210749/166311381-cdd5d89c-9c2c-4208-9259-4e0e10f58305.png)
![Screenshot 2022-05-03 at 12 49 26 AM](https://user-images.githubusercontent.com/1210749/166311389-5026c377-eb69-428f-87e0-77fecca95e22.png)

**Comment by kiriles90** [comment]
Do you have the auto update of API servers set to disabled? If so, manually update them (the refresh button next to the API fields in the settings) and select a working API from the suggested list. Ofc you can also skip the update step if you want and you already know the url of the API you want to use and just enter it in the relevant field.

**Comment by Jaladhjin** [comment]
Why are all reports of this issue getting closed without response?

I'm here looking for info on the same issue & see a ton of reports many of which like this 1 closed without response.

The few that do have a response seem to be the same answer, try a different API from the drop down, "something must be blocking it", or change your VPN around if you're using 1.

Is that the general consensus? Are there more APIs coming & perhaps an auto try next API to keep tickets like these from getting created as often?

Happy holidays too folks! :-)

**Comment by kiriles90** [comment]
@Jaladhjin that's not a consensus, its a fact. If you can't connect to the API and you get shown the error message above, while the API is online for everyone else, then you either haven't updated the API list yet, or you have but something is blocking you from accessing it, most likely your ISP. Use something like a VPN to bypass the block. 

> an auto try next API to keep tickets like these from getting created as often?  

That's already the case that's why there are multiple APIs per line, it auto-tries the next one in random order until it finds the first working one. The people that get the error message above have either not updated their APIs and are using old/dead ones, or have updated it but all the current ones are being blocked by their ISP and they need to find a way to bypass the block. (VPN, DNS change, etc..)

Happy holidays and a happy new year :)

**Comment by Jeannaly** [comment]
Switching back and forth between the API server options worked for me.
