### ISSUE TITLE
problems with torrents it is torrent collection

### ISSUE THREAD

**Issue by madrid2022ok** [popcorntime/popcorntime#2524]
![20220628_154547](https://user-images.githubusercontent.com/105641464/176195324-260131e3-6c4c-48a6-bf25-a078d3c6637e.jpg)

The torrents do not come out and I cannot see the movies and series and an airplay question is used to pass the videos to the apple tv the torrents

and if i am using a vpn

**Comment by dutchy1001** [comment]
As before, you don't give any info asked when opening an issue.

**Comment by madrid2022ok** [comment]
ok but because the torrents don't come out and I'm using a vpn in torrent Collection and sometimes it doesn't work to transfer the videos to apple tv torrents

**Comment by dutchy1001** [comment]
what OS?
What version of PCT
What movie/series

PCT is NOT responsible for the content, it could well be that the movie/series you want to watch is not available now (sometimes the API does not remove old data)

**Comment by madrid2022ok** [comment]
I'm only using torrent collection nothing else because some movies and series are in Russian but not in English and Spanish

**Comment by dutchy1001** [comment]
99% of the movies are in English. 
With the main movie pages you have the option to choose an audio language on the bottom right side, with the series pages this this option is on the top. 
In the settings you can set a default language for the app and a "localisation" language for default movie/series language.

If you choose to use (your own found) torrents then PCT can not be blamed if they don't work.
As with the latest (beta) build you can see different torrents listed and then make your choice.

Edit:
It would be handy to know what PCT version as many issue's have been fixed in beta builds

**Comment by madrid2022ok** [comment]
![26AEC3E9-51EA-4368-86BB-BA7DF2767A2F](https://user-images.githubusercontent.com/105641464/176210853-1d8e2676-9043-4a2c-b3f0-dfd974b9c427.jpeg)



in some series and movies it comes out in Russian language
they are not in english and spanish language

**Comment by dutchy1001** [comment]
From the 100 series I just clicked on only 3 were not English. 
If there was an English version of the series you are looking for then I presume the API would have found it and listed it.
All none English I found were only cartoons.
As for the little mermaid, the episode you listed, I used an external player and there are 5 language options 2 rus, 2 ukr and 1 english. Unfortunately you cant choose an audio language with the default pct player, only with an external player.

As said before, PCT is NOT responsible for the content.
