### ISSUE TITLE
[Request] Load API Domains From Github

### ISSUE THREAD

**Issue by zero77** [popcorntime/popcorntime#2592]
**Is your feature request related to a problem? Please describe.**
At the moment when a popcorn time APT domain stops working, you have to manually find a working one and replace it.

**Describe the idea you'd like**
To automate this could popcorn time instead load a list of domains stored on github, as well as having the current option to use a custom domain.

**Describe alternatives you've considered**

**Additional context**

**Comment by kiriles90** [comment]
It doesnt stop working if you have autoupdate on which will get new ones from dht. You also do have the option to use a custom domain, write whatever you want its a textbox. As for not loading them directly from github.. if you mean this github (repo), there is a reason we just dont load them from an .ini file somewhere.. considering the nature of the app etc.. Closing this.

**Comment by zero77** [comment]
Just to clarify, i am meaning the domains that are used for popcorn times API not torrent trackers.
like: popcorn-time.ga and shows.cf

Building and installing a new version seams like a lot of work for everyone involved just to get working domains, unless i have misunderstood.

I am not sure i explained well but, yes the current option to add domains to a textbox is good and i wasn't suggesting removing it

**Comment by kiriles90** [comment]
> Just to clarify, i am meaning the domains that are used for popcorn times API not torrent trackers.

I mean the ones used for API servers as well, the ones where you get the content from.

> Building and installing a new version seams like a lot of work for everyone involved just to get working domains, unless i have misunderstood.

Like I said.. there is the "Automatically update the API server URLs" option in the settings which does exactly what it says, updates the suggestions for the API url textboxes as well as the refresh button next to said textboxes which you can use to manually update them any time you like. As for adding urls for stuff like that to github, or straight up loading them from a textfile somewhere.. piracy etc.. That's why Popcorn Time uses modules and textbox suggestions and dht updating methods instead of a couple of strings in file somewhere in its own code.
