### ISSUE TITLE
popcorntime.app not loading

### ISSUE THREAD

**Issue by vinyll** [popcorntime/popcorntime#2636]
1. attempt to browse to https://popcorntime.app/
2. wait…
3. `The connection has timed out`

Note that browsing from the CLI (Lynx) works but redirects to a scam website (popcorntime4u(dot)com)

My suggestion would be to remove the link from the [project page](https://github.com/popcorn-official/popcorn-desktop)

**Comment by kiriles90** [comment]
popcorntime.app is the now dead official website. There is an explanation about everything in the FAQ as for the reason we don't completely remove it or switch to a new official one is mostly that.. "they" want us dead, so we will be. Beats playing whack-a-mole every 6 months and having other parts/aspects of the app also being targetet in the process.. (e.g the subreddit, the repo here, the API, etc etc)

**Comment by vinyll** [comment]
Thanks for taking the time to reply.

For those like me who didn't see [that FAQ article is here](https://github.com/popcorn-official/popcorn-desktop/wiki/FAQ#-important-notice).

I'm totally aware of why it is down, however having a redirect to another scam website makes it look dubious.

```
➜  ~ http popcorntime.app           
HTTP/1.1 301 Moved Permanently
Connection: keep-alive
Content-Length: 59
Content-Type: text/html; charset=utf-8
Date: Tue, 06 Sep 2022 11:55:13 GMT
Location: http://popcorntime4u.com
Server: ip-100-74-3-146.eu-west-2.compute.internal
X-Request-Id: 5e041591-0216-4f58-8b68-f948cde442ff

<a href="http://popcorntime4u.com">Moved Permanently</a>.
```

**Comment by kiriles90** [comment]
Yes indeed, its a somewhat recent development afaik. Though.. to be honest most users will just attempt to browse normally and get a timeout? Either way I'll see if I can find anyone who can do something about it, if there is something that can be done. And yes I know.. the easy and correct solution would be to just remove or update the url but the reason I'm hesitant doing that is that -if they dont already- I don't want to give them the reason to view the repo as the main place to target now. (also the reason why in many places we have the ru mirror as the go-to place to download instead of just linking the releases page here). Anyway, hopefully we can find the best solution for the situation, as always all thoughts and ideas are welcome.
