### ISSUE TITLE
Watched option for whole series

### ISSUE THREAD

**Issue by dutchy1001** [popcorntime/popcorntime#2648]
As we have this option for movies I would like to see this feature for the "Series" tab (and maybe for anime when that works again).  I know we have the "seen" option, but that is only visible when opening the series page. 
The hide/fade/show option should be on the main series page.

As a bonus (if that is possible with the coding of course) this can also work then for when new episode(s) have been added that it "un-hide" or "un-fade" .

**Comment by kiriles90** [comment]
@dutchy1001 after looking into this more.. we cant mark it as seen from the list view because it has to mark all episodes as seen, and it doesn't know what episodes to mark/exist until you open the show detail view. Loading all the episode info in the list view for all the series visible isn't a viable solution, too much unnecessary data going to waste so.. I guess we need to close this one.
