### ISSUE TITLE
Popcorn-Time quit unexpectedly on M1 Pro

### ISSUE THREAD

**Issue by alaminio** [popcorntime/popcorntime#2658]
Operating System Version:
- OS X 13.0.1 (M1 Pro) and it happened on OSX 12.x too

Popcorn Time Version:
- 0.4.8 & 0.4.9

Download date:
- 17th Nov, 2022

Download url:
- https://github.com/popcorn-official/popcorn-desktop/releases/download/v0.4.9/Popcorn-Time-0.4.9-osx64.zip

#### Expected Behaviour
- Open the app

#### Actual Behaviour
- Popcorn-Time quit unexpectedly.

#### Steps to reproduce the behaviour
- Launch the app (Happened on version 0.48 and today I downloaded 0.49 and same)
- The app launch after trying several times but quit sometimes (randomly)

#### Screenshot(s) of issue or error(s) logs of developer console (Windows/Linux: F12, MacOS: ⌘ + 0 ... then 'console' tab) (recommended)

<img width="372" alt="Screenshot 2022-11-17 at 11 48 28 AM" src="https://user-images.githubusercontent.com/2793040/202368337-cb7d53bf-61eb-4511-ba19-5094dbfa6947.png">

**Comment by kiriles90** [comment]
Popcorn Time doesn't have native apple silicon support yet. That being said there is also a bigger issue with new macOS versions and the app. Both though depend on updating the version of NW.js that we use, for which there is already an open issue at https://github.com/popcorn-official/popcorn-desktop/issues/2062 (a straightforward bump of the version number has its own issues that's why it has happened). Follow the issue above for news/updates.

**Comment by kiriles90** [comment]
Popcorn Time doesn't have native apple silicon support yet. That being said there is also a bigger issue with new macOS versions and the app. Both though depend on updating the version of NW.js that we use, for which there is already an open issue at https://github.com/popcorn-official/popcorn-desktop/issues/2062 (a straightforward bump of the version number has its own issues that's why it has happened). Follow the issue above for news/updates if you want.
