### ISSUE TITLE
popcorn time for kids

### ISSUE THREAD

**Issue by gastontancredi** [popcorntime/popcorntime#2663]
**Is your feature request related to a problem? Please describe.**
There is no pop corn time version for family/kids with safe content

**Describe the idea you'd like**
a version with safe content

**Comment by dutchy1001** [comment]
This will be more an API feature then a Popcorn-Time feature. if the API can sort by PG etc. etc. then i's not an issue (me thinks). PCT itself just shows what the API gives it.

PS. I do think this might be a very nice feature if possible.

**Comment by kiriles90** [comment]
This has been suggested before over the years but it opens another can of worms.. mainly how do you secure/ensure the app cant be used or reset to the adult version, especially since even the API(s) are of mixed content and out of our control.
At the moment the most that can be done is setting your default filters to e.g the animation genre so the app starts to that but it can be easily changed if the child selects a different genre or searches for something.

Closing because tbh this requires a lot of changes to the app and how it works/installs/resets as well as a huge amount of testing (and preferably API control) before we can release something as child-safe.
