### ISSUE TITLE
Set up automated dependency bumping

### ISSUE THREAD

**Issue by mjholub** [popcorntime/popcorntime#2675]
Operating System Version: Alpine Linux 3.17

Popcorn Time Version: latest git commit pull

Download date: last checked on 13th Dec 2022

Download url: this repo

#### Expected Behaviour
set up automatic dependency bumping/replacement with Snyk or Dependabot to not jeopardize the users and save devs' time spent doing these chores manually so that full focus can be dedicated to fixing bugs and delivering new features.
...

#### Actual Behaviour
App uses some dependencies that are a few years old, some with critical vulnerabilities or deprecated. Keeping the dependency network healthy in a P2P app, based on a technology so ridden with security issues as Node is of tremendous importance.
...

#### Steps to reproduce the behaviour
Run npm install/npm audit.

#### Screenshot(s) of issue or error(s) logs of developer console (Windows/Linux: F12, MacOS: ⌘ + 0 ... then 'console' tab) (recommended)
may paste later but it's pretty reproducible enough

**Comment by kiriles90** [comment]
Dependabot is already setup and all its PRs are merged after being checked by someone. Any deprecated dependencies are the ones that are locked at a specific version because anything newer will create bugs someone has to hunt down and fix. In almost all those cases thats not as simple as it sounds (e.g the mess that was version 0.4.0) so.. they remain at their current versions for now. If anyone wants to go ahead and bump any of them make a PR, just make sure its also addresses all the bugs created by it.
