### ISSUE TITLE
App freezing and lagging while downloading

### ISSUE THREAD

**Issue by emipasca** [popcorntime/popcorntime#2694]
App freezes and lags when downloading movies and tv shows at high speeds.
Stops happening when i put max download to 10MB/s, at 15MB/s and over the app will start freezing and lagging when downloading.

Operating System Version:

Windows 11

Popcorn Time Version:

0.4.9

Download date:

22/01/2023

Download url:

https://github.com/popcorn-official/popcorn-desktop/releases/download/v0.4.9/Popcorn-Time-0.4.9-win64-Setup.exe

#### Expected Behaviour

...
Not freeze

#### Actual Behaviour

...
Freezes, takes up to 10 seconds to register mouse hovers and clicks

#### Steps to reproduce the behaviour

1. ... Download Movie
2. ... Have internet speeds of 15+ MB/s
3. ...

**Comment by kiriles90** [comment]
The issue has been opened many times before. WebTorrent is cpu bound in high speeds. It can also only run on the main core/thread when used via NW.js. Nothing that we can do about it with Popcorn Time code other than switching to something else as the app's torrent client, though that requires for a better alternative to exist..

**Comment by emipasca** [comment]
Can you not run the webtorrent and popcorntime UI on two different threads? because when i experiences lagging, im fairly confident the torrent was downloading at 25MB + speeds even though the UI was completely frozen

**Comment by kiriles90** [comment]
No afaik. WebTorrent has to run on the main thread. There are some related open issues at their repo (e.g https://github.com/webtorrent/webtorrent/issues/1524) but I don't see much progress on them.

> im fairly confident the torrent was downloading at 25MB + speeds even though the UI was completely frozen

Yeah, that would do it on most systems on a single core. Though the UI is not really frozen, its just the functions that update it that timeout so it doesn't update. The window/app itself is 'fine'.. (pegged that core to 100% but not frozen anyway).

Try lowering the connections limit and dht udp requests limit options a bit (though lowering them too much will hurt download speed). Also make sure you have the protocol encryption option disabled because like its tooltip says, it will cause high cpu usage in some instances e.g when there are many peers/many peers using it and it makes a lot of encrypted connections, it has to calculate many hashes with a non-native method that also runs on the same 1 core and not very efficiently at that either. A native more efficient method was added in later versions of NW.js, one that can also run on a different thread -just protocol encryption not talking about the Webtorrent issues- that will help and allow us to set this option to enabled by default but for that.. we need to solve the issues preventing us from updating NW.js.. (open issue at #2062)
