### ISSUE TITLE
how can i get popcorntime working on my android phone 

### ISSUE THREAD

**Issue by Gatofelix72** [popcorntime/popcorntime#2707]
Popcorntime will not connect but is connecting on my pc how can this  be solved im looking like crazy !!

**Comment by dutchy1001** [comment]
Get the .apk file from [here](https://shows.cf/build/) for your Android phone.

**Comment by joeyoropesa-dev** [comment]
> Get the .apk file from [here](http://popcorn-time.ga/build/) for your Android phone.

That domen is dead and also no one yet didn't already fixed the source code dependencies and requirements and compile it for public with the new servers update so that it can use the new APIs just like this source code for desktop provides. 

This should be re-opened issue while someone or me are trying to find a way for popcorn-android to work again and have latest apk published from the updated sources.

**Comment by dutchy1001** [comment]
At the time of writing my previous post the link was still valid.
I have updated the link to a working link.

Any further issues with the Android version go to the Android issue page  [here](https://github.com/popcorn-official/popcorn-android/issues)
