### ISSUE TITLE
Last version 4.9 is super slow/laggy and downloads don't show any number

### ISSUE THREAD

**Issue by vRITHNER** [popcorntime/popcorntime#2776]
Operating System Version:
Windows 11

Popcorn Time Version:
last 4.9 version

Download date:
10/11/2023

Download url:
from this site

#### Expected Behaviour
be fluid, and working

#### Actual Behaviour
everything is lagging and slow, every click takes a moment to actually do something... btw v 4.8 was doing the same
all downloads don't show download/upload bandwidth (I can see 0 Kb/s 0 Kb/s for all rows but the right page section shows per example: 1 minute(s) remaining and some %

#### Steps to reproduce the behaviour
1. Download and Install/Run the application
2. Go to movies, click one, click download 

#### Screenshot(s) of issue or error(s) logs of developer console (Windows/Linux: F12, MacOS: ⌘ + 0 ... then 'console' tab) (recommended)
![image](https://github.com/popcorn-official/popcorn-desktop/assets/238842/557224ed-aa33-4427-a59f-dc1978c5a45f)

**Comment by dutchy1001** [comment]
All things you discribe can be caused by a multitude of factors outside PCT fault.
What are your PC specs and internet speeds. Do you have multiple programs running at the same time etc. ect.
Then there is the issue of "are there enough seeds"

What version do you use, you can find this at "settings > info" (info button on the left top) and PCT version "0.4.9."Ogres are not like cakes" - Beta XXXXXX, what is the XX number.

**Comment by vRITHNER** [comment]
Hello,
please find here the answer to your questions:
Version: 0.4.9 "Ogres are not like cakes" Beta - 64553fa7
Internet speed:
[cid:0ef6407a-c5a6-4a00-8627-9cc0fd894f06]
[cid:7327ed59-d91a-4cb6-973f-8fc3ea234be9]

Yes, I have some programs running but nothing specials; no one is acting like your's...
Concerning Seeds, I tried with Movies with lots of Seeds like ex:
[cid:7c074ac2-00d2-4dd4-8625-7f5c09082b6f]

Hope this will help...
Best Regards,
-vince
________________________________

**Comment by dutchy1001** [comment]
hi Vince,
the version you use is from September 2022 (which is a bit old), there are many newer dev builds made with many improvements.
Go to [here](https://github.com/popcorn-official/popcorn-desktop/actions/runs/6017288107) and update to the latest dev build and report back how things go. If your happy enough you may close this issue after.

**Comment by merseyV** [comment]
@dutchy1001 
Have you tried replicating it? I get the same issue on my Mac (using the OP's list) with dev build. Not noticed it before ... rarely use PT app downloads feature myself (I use qBittorrent instead).

Haven't tried a variety of (older) torrents, but in my case I suspect it's the same memory leak in WebTorrent - that I'd get when watching "latest releases" (especially larger files). The download/app response grinds to a halt and app memory usage goes into the red. Don't know if the OP's Windows issue has the same cause? ..  but my resulting (screenshot) looks similar to his.

**Comment by dutchy1001** [comment]
@merseyV 
I have checked all listed in the OP's download list, besides 1 (Invasion) they all come up with a red dot, meaning the avalability is very low to none. This could be a cause why they dont download.

As of the memory leak, my system uses between 245MB to 265MB, to me this seems normal.

**Comment by merseyV** [comment]
@dutchy1001 
Strange! mine shows decent seeds .. except for the 2160p (last one), but even that starts (as a "Watch Now").

Leaving that aside ... It's the lead download (Invasion) that starts the issue (for me)? You can see his download reached 2.3GB @ 10min (mine was 2.6GB @ 11min). He didn't state if Invasion S02E08 eventually finished (if left running) - mine stuck at that point (with all 0Kb/s in the left-hand tallys). Macs' have run with this issue since 0.3.10 WebTorrent update (goes back some!)

Just the Invasion episode drove memory usage to >10GB ... I've only got 8GB physical (lol). New (popular) releases make things worse (runaway peers .. 200+ sometimes). Otherwise, memory usage is more gradual ... creeps up slow enough (usually) to finish a session (before it hits the buffers!).

No point in keeping the issue open for me ... is aware of it (not specific to 'download only' feature). If OP doesn't give you an update - just use your "discretion!"

**Comment by merseyV** [comment]
https://github.com/popcorn-official/popcorn-desktop/issues/1373

Having just read this thread - I now understand that big lump under the GitHub's carpet ... lol.
(I'm off before I get the brush!)

**Comment by kiriles90** [comment]
Damn, if @merseyV is finally in github after all these years I better drop the popcorn and reply :D Its WebTorrent as you've said guys. Everytime we reopen the issue it always ends up to that and resolving it is not really up to us. I'm not sure if WebTorrent can really do anything about the core of the issue, other than various optimizations, which is that its a module that runs on what is basically a single-threaded language (javascript) that runs in what is basically a browser window (NW.js, Chromium etc). After a certain download speed, depending on the cpu/thread it runs on cpu usage maxes out and everything cr*ps itsself, the UI being the most obvious but background functions suffer too and many just timeout. We could do some things to make sure we get the best performance out of it which is to keep NW.js and WebTorrent as up to date as possible, or use some work arounds, e.g moving the UI on a secondary thread since WebTorrent needs to be on the primary one (a workaround they themselves also use in their WebTorrent app iirc). Anyway.. we can reopen the issue mersey linked since its the one with the most info on the issue but I'm not very optimistic of a miracle fix.

**Comment by merseyV** [comment]
Oh no! dust everywhere now.

(![](https://media.tenor.com/uUDtQidKppkAAAAC/doggo-cold.gif)



>depending on the cpu/thread it runs on cpu usage maxes out and everything cr*ps itsself,

Most of them had maxed-out on RAM (memory) ... same issue we discussed before? The one our old friend `@vankasteelj` was chasing up on the Webtorrent GitHub, about 9 months. ago? They (Webtorrent) seemed to be discussing more than one causation but the outcome was the same (runaway memory).

This comment caught my eye:

>I'd (and I think many others) really appreciate a response from `@team-pct`

.... join the queue! 🤣

**Comment by merseyV** [comment]
@dutchy1001  

> hi Vince ..... and update to the latest dev build and report back how things go. If you're happy enough you may close this issue after.

Looks like "new build" might have helped him? Shame he never got back: Feedback (even negative) might have helped - either way.
 
> As of the memory leak, my system uses between 245MB to 265MB, to me this seems normal.

Yes, It's definitely what someone might hope for. Oddly doesn't appear the case for quite a few users across all three 3 OS's, though? (incl. me)  
Could I ask ... what is your OS and system specs (cpu/ram) And your (internet) download max, if you would? Do you have any custom setting for Popcorntime (WebTorrent) download/connection limits (dl/dht)?

Thanks!

**Comment by dutchy1001** [comment]
@merseyV 
 I always give a few days before closing an issue but often beats me to it (ppl could be busy with real life 😉).

As for your question, I got an i7 10700K 10th Gen and 16gb ram at 4400Mhz and a NVidia RTX 2070 running Windows 11 Enterprice. Max internet speed is 362Mbps and using a VPN. Nothing special beside building my own pc's.

![Screenshot 2023-10-21 004655](https://github.com/popcorn-official/popcorn-desktop/assets/5569980/4702d795-46c5-417b-aad2-4825c4df1e4f)

Hope the screenshot helps.

**Comment by merseyV** [comment]
@dutchy1001 
Thanks for that mate! (appreciated) .... nothing there I can query with you (looks pretty much vanilla). 

If you get a spare 15 minutes or so, can I can drag you away from real life (again!) to do something for me (no rush). Run a particular torrent for me to 50ish% and 100% and screenshot your nwjs Memory (process) results.

Use same torrent as I've been running tests with (if you would) ... invasion.2021.s02e08.1080p.web.h264-nhtfs.mkv ... from the **more...** menu (2nd from top on my set-up).


Cheers!!

**Comment by dutchy1001** [comment]
![PCT test 1](https://github.com/popcorn-official/popcorn-desktop/assets/5569980/3f9eb047-3e07-4f55-8d77-e0f097b259d1)
at start point

![PCT test 2](https://github.com/popcorn-official/popcorn-desktop/assets/5569980/96931fd3-fb55-49a7-8ee0-a67c1b73914a)
50%

![PCT test 3](https://github.com/popcorn-official/popcorn-desktop/assets/5569980/9b2a2bae-3fcd-4271-9016-a48416b8ee56)
75%

![PCT test 4](https://github.com/popcorn-official/popcorn-desktop/assets/5569980/68202e4d-c58a-4a44-963e-ce00947e9b27)
100% (the second it finished)

![PCT test 5 (5 minutes after finish)](https://github.com/popcorn-official/popcorn-desktop/assets/5569980/3c49b3c5-25b1-4b9c-957c-a83a67186f90)
5 minutes after finish

As you can see I left the task manager on top of PCT with all PCT processes on show, I dont have the NWJS process in my list anymore (there used to be one in older versions)

**Comment by merseyV** [comment]
@dutchy1001 

Above and beyond sir! ... thanks for that definitive conclusion.

My best attempt. custom connection 1_25_0 (42 seeds)

<img width="946" alt="Connection 5_25_8" src="https://github.com/popcorn-official/popcorn-desktop/assets/137357177/f0f4053f-6ada-43b6-b4ed-791e715a9b66">


Worst case. default connection 5_55_16 (64 seeds)

<img width="952" alt="Conection 5_55_16" src="https://github.com/popcorn-official/popcorn-desktop/assets/137357177/4f6e614d-9abf-4d90-b70f-e3757389a853">

Torrent has aged a bit since my original post (100+ peers and >10MB) so it actually finished under my MBPro 8GB limit (just).

I'm "stymied!" It's got to be something to do with Webtorrent (torrent engine) ... their own desktop app has the same issue (going back years). Why and how is beyond my pay-grade. 


Hanging up the hat!
![hanging-up-my-hat](https://github.com/popcorn-official/popcorn-desktop/assets/137357177/74e2a4fa-167d-412a-9309-9d60bb0fa69f)

**Comment by merseyV** [comment]
**Postscript:** A trip down memory lane ....


(82 peers)
<img width="711" alt="277118913-e6109d7a-0abb-46f4-b532-f4af1502ff7b" src="https://github.com/popcorn-official/popcorn-desktop/assets/137357177/b2be8e7f-184c-4fc7-a0f6-67980cbd87ea">


.. remember when! 😃

**Comment by dutchy1001** [comment]
I still dont understand why I dont have a memory leak compair to many others, it goes up slightly max about 25 to 30 mb which is nothing.
I hope @ivan1986 (or any dev) can do something with the info.

**Comment by merseyV** [comment]
Might improve for Windows user with WebTorrent 1.9.7 update (Actions Dev build) ... see how it goes.
@vRITHNER never came back?

(https://github.com/webtorrent/webtorrent/issues/2356#issuecomment-1532162034)
