### ISSUE TITLE
Browsing and Playing Local Movies

### ISSUE THREAD

**Issue by physiii** [popcorntime/popcorntime#2794]
The only missing piece for this replacing all of our family movie needs is if we could browse from local storage.

Thinking just a tab at the top. We can grab the titles (or maybe md5 sums) and infer the movie details.

Is this something I would need to add or has anyone got this working?

**Comment by dutchy1001** [comment]
I like this idea to be added to PCT.
I don't know if will cause simular issue's we have with the "watched" tab our devs are trying to add lately ( I hope not 📽 🎞 📺).

**Comment by kiriles90** [comment]
@physiii To be honest.. I just closed #1683 due to the issues mentioned there and this is basically the exact same issue so I think we have to close it too. if you do want to have a go at it though and manage to get some form of working code that doesnt mess other stuff or creates issues in the app in general or the user, I'll merge it as soon as you tell me its ready.

**Comment by kiriles90** [comment]
Closing the issue but open it in PR form anytime you want.
