### ISSUE TITLE
Time for a new release?

### ISSUE THREAD

**Issue by Agusum** [popcorntime/popcorntime#2844]
It's been over a year since the last official release. Perhaps it's a good time to push a new one. What do you think?

**Comment by merseyV** [comment]
@Agusum 
>Perhaps it's a good time to push a new one

[@dutchy1001 reply should give you hope (if all goes well)?](https://github.com/popcorn-official/popcorn-desktop/issues/2840#issuecomment-1906227217)

>As we are waiting to make a new official release (which isn't far off) you can still get updated versions from [here](https://github.com/popcorn-official/popcorn-desktop/actions). As you can see this is just over a week old.

**Comment by dutchy1001** [comment]
The link provided in the previous post is as good as a new release. 
With the constand updates, adding new features and cleaning up/out (old) code a new release is just a version number away. With one of the next comming merges/builds the official release page will be updated to one of them. When this happens we have to see, this will be upto the main devs.

Closing this as it's not an issue, feel free to continue here if there are more questions.

**Comment by merseyV** [comment]
Just noticed this:


<img width="1475" alt="Console log - 82 0" src="https://github.com/popcorn-official/popcorn-desktop/assets/137357177/e07a0eb2-2bb1-4061-91a2-e425d4416ef4">


It's only an amber warning! Shouldn't be any problem, you'd think? Just that my copy started acting up ... refusing to close and opening to a black screen.

I've just unzipped another copy from the original download .. seems ok again?

**Comment by merseyV** [comment]
Been using a few different versions lately: I've probably corrupted a file somewhere? There's copies everywhere.. just like the old "patched-up" version days! :D 

 Using Latest build since last week with no issues (till today's hiccup). Worked new copy for the last couple of hours (stress testing) ... no problems. Only used Console because of the crash, and yes! (if I look) I can see same warning in previous versions, now.   The new NW.js builds have never given me a reason to use it (console) ... even the subreddits a lot quieter these past few months?  Long may it continue! 

I'll stick with the one version instead of "chopping and changing!" 
*... "Mischief Managed!"*  ;)

**Comment by Agusum** [comment]
I totally get that software is an ever-evolving thing with changes being introduced constantly and everyone who is here in GitHub can probably figure out how to install a dev build.

However, the concept of an official release usually tends to bring with it enhanced testing and stability (and conscious decisions of which bugs it's ok to ship with) so that any non-tech user is safe to use it. Perhaps it's not the goal of this project to produce this kind of builds frequently as it used to do in the past, but I'm glad that you're now considering doing one.

**Comment by merseyV** [comment]
I do like a nice clean console! .. :)

**Comment by julianbrasse** [comment]
yay there's new
