### ISSUE TITLE
Cannot open arm64 version on a M3 Ultra and generic 64 bit hangs.

### ISSUE THREAD

**Issue by zatarra** [popcorntime/popcorntime#3000]
#### Operating System Version:
macOS (M3 Ultra)

#### Popcorn Time Version:
v0.5.1 (osxarm64)

#### Download date:
17 April 2024 at 13:15

#### Download url:
https://github.com/popcorn-official/popcorn-desktop/releases/download/v0.5.1/Popcorn-Time-0.5.1-osxarm64.zip

#### Expected Behaviour:
Open and use it as before
...

#### Actual Behaviour:
Does not open. OSX Shows a message stating that it is damaged and cannot be opened.

#### Steps to reproduce the behaviour:
1. Download and try to install on a Macbook M3 Ultra

#### Screenshot(s) of issue or error(s) logs of developer console (Windows/Linux: F12, MacOS: ⌘ + 0 ... then 'console' tab) (recommended):
https://snipboard.io/D7TaoI.jpg

Is this version meant to be used with arm cpus? (Isn't M3 Ultra arm?)

The generic 64 bit version (https://github.com/popcorn-official/popcorn-desktop/releases/download/v0.5.1/Popcorn-Time-0.5.1-osx64.zip) simply hangs 90% of the time. (https://snipboard.io/GZ0oE5.jpg)

**Comment by merseyV** [comment]
https://github.com/popcorn-official/popcorn-desktop/issues/2986

Opened and closed?  

Because it's a Silicon (Arm64) application, Safari will apply a ("sticky") 'Gatekeeper' quarantine flag to the download .. Silicon apps are required to be signed and notarised (with an Apple developer account).

It's necessary to manually remove the quarantine flag using Mac's 'Terminal' (command line) utility. 
The command is `xattr -c` "/path/to/application.app".  

Copy `xattr -c`into Terminal > insert a space > and drag the PTapp into the Terminal window to insert its location (path) > 'Enter' .

**Comment by vareille** [comment]
Same issue on M1 with firefox. "xattr -c" solved it.
As it is a zip file, it would be helpful to simply add a readme.txt with this info.
