### ISSUE TITLE
NSIS 

### ISSUE THREAD

**Issue by team-pct** [popcorntime/popcorntime#302]
Operating System Version:
Windows

Popcorn Time Version:
0.3.10

Download date:
Always 

...

#### Actual Behaviour
NSIS just try to install without checking the Popcorn-Time.exe process is already running 
Should Look for it first then try to kill automatically

**Comment by ChrisAlderson** [comment]
The `installer_makensis.nsi` file already checks if the process is running, but they do this [by the `APP_NAME` variable](https://github.com/popcorn-official/popcorn-desktop/blob/development/dist/windows/installer_makensis.nsi#L332). `APP_NAME` is in our case `Popcorn-Time`, but I think the NSIS function grabs the name which is in the taskbar which was, until two days ago (e56ac3af485f7e72423db566a6a80590c45db92b) `Butter`. I think the issue is solved by changing the name to `Popcorn-Time` which has already been done.
