### ISSUE TITLE
I am getting error when i tried to install in my MAC (silicon)

### ISSUE THREAD

**Issue by nabin-shah** [popcorntime/popcorntime#3027]
Warning: Cask 'popcorn-time' is unavailable: No Cask with this name exists.
==> Searching for similarly named casks...
Error: No casks found for popcorn-time.

**Comment by merseyV** [comment]
Personally, I'd go the easy route and use the `Popcorn-Time-0.5.1-osxarm64.zip` release. 

I've seen that macOS  cask issue reported before (somewhere) ... can't remember if it got resolved? If you want a quick solution - just use the .zip

**Comment by merseyV** [comment]
Personally, I'd go the easy route and use the `Popcorn-Time-0.5.1-osxarm64.zip` release. 

I've seen that macOS  cask issue reported before (somewhere) ... can't remember if it got resolved? If you want a quick solution - just use the .zip

**Edit:**
 just noticed [this](https://github.com/popcorn-official/popcorn-desktop/pull/3013) ... but, I'm not familiar with Homebrew (only the type you imbibe!!)

**Comment by merseyV** [comment]
Personally, I'd go the easy route and use the Popcorn-Time-0.5.1-osxarm64.zip release.

I've seen that macOS cask issue reported before (somewhere) ... can't remember if it got resolved? If you want a quick solution - just use the .zip

Edit:
just noticed https://github.com/popcorn-official/popcorn-desktop/pull/3013 ... but, I'm not familiar with Homebrew & Cask (unless it's Beer!!). @dutchy1001 understands the GitHub better than me ... I don't know if merged means an actual fix/download?

**Comment by merseyV** [comment]
Personally, I'd go the easy route and use the Popcorn-Time-0.5.1-osxarm64.zip release.

I've seen that (Silicon) macOS cask issue reported before (somewhere) ... can't remember if it got resolved? If you want a quick solution - just use the .zip

Edit:
just noticed https://github.com/popcorn-official/popcorn-desktop/pull/3013 ... but, I'm not familiar with Homebrew & Cask (unless it's Beer!!).  
@dutchy1001 understands the GitHub better than me ... I don't know if merged means an actual fix/download?

**Comment by merseyV** [comment]
Personally, I'd go the easy route and use the `Popcorn-Time-0.5.1-osxarm64.zip` release.

I've seen that (Silicon) macOS cask issue reported before (somewhere) ... can't remember if it ever got resolved? If you want a quick solution - just use the .zip

Edit:
just noticed https://github.com/popcorn-official/popcorn-desktop/pull/3013 ... but I'm not familiar with Homebrew & Cask (unless it's Beer!!).  
@dutchy1001 understands the GitHub better than me: I don't know if merged means an actual (downloadable) fix?

**Comment by nabin-shah** [comment]
> Personally, I'd go the easy route and use the `Popcorn-Time-0.5.1-osxarm64.zip` release.
> 
> I've seen that (Silicon) macOS cask issue reported before (somewhere) ... can't remember if it ever got resolved? If you want a quick solution - just use the .zip
> 
> Edit: just noticed #3013 ... but I'm not familiar with Homebrew & Cask (unless it's Beer!!). @dutchy1001 understands the GitHub better than me: I don't know if merged means an actual (downloadable) fix?

I tried installing that way too, it says file is broken

**Comment by merseyV** [comment]
>I tried installing that way too, it says file is broken

Covered [Here](https://github.com/popcorn-official/popcorn-desktop/issues/3000#issuecomment-2092390369)

**Comment by merseyV** [comment]
>I tried installing that way too, it says file is broken

Covered [Here](https://github.com/popcorn-official/popcorn-desktop/issues/3000#issuecomment-2092390369) 👍 

n.b.[ **Apple Silicon:**](https://github.com/popcorn-official/popcorn-desktop?tab=readme-ov-file#install)

**Comment by merseyV** [comment]
>I tried installing that way too, it says file is broken
Covered https://github.com/popcorn-official/popcorn-desktop/issues/3000#issuecomment-2092390369 👍

n.b. @dutchy1001 ...Don't know if you have Editing privilages? The [Apple Silicon:](https://github.com/popcorn-official/popcorn-desktop?tab=readme-ov-file#install) reference would be better placed as a third bullet point under Install > macOS: (I'd suggest?)

**Comment by merseyV** [comment]
>I tried installing that way too, it says file is broken

Read: https://github.com/popcorn-official/popcorn-desktop/issues/3000#issuecomment-2092390369 👍

@dutchy1001 ...Don't know if you have "Editing" privilages? The [Apple Silicon:](https://github.com/popcorn-official/popcorn-desktop?tab=readme-ov-file#install) reference would be better placed as a third bullet point under **Install > macOS:** (I think?)

**Comment by dutchy1001** [comment]
I'm sorry to say but I stay away from Apple products and software as far as possible 🤮🤮🤮. 

>  I don't know if merged means an actual (downloadable) fix?

I think only devs can do the merge which can be downloaded after.

Never tried myself to merge anyting (as I don't code) but it looks like I can alter the readme.
Not sure how you want this then as 3rd bullit point, you can't miss it on the readme page.

**Comment by merseyV** [comment]
>you can't miss it on the readme page.

Lol ... I can't. Others try their best to!! 🤣🤣🤣
Something ike this .... instead of between Casks & Distros?

**macOS:**

Download and install:

* Latest release: check [popcorn-time.site](https://popcorn-time.site/) or the repo's [releases page](https://github.com/popcorn-official/popcorn-desktop/releases)
* Or latest dev build (for testers): check the repo's [actions page](https://github.com/popcorn-official/popcorn-desktop/actions)  
* **Apple Silicon:** If you have Apple Silicon (M-series chips), you need to use the arm64 release. Apple Silicon apps are required to be signed and notarised with an Apple developer account. So it is necessary to manually remove the quarantine flag:

`xattr -c "/Applications/Popcorn-Time.app/"`

**Comment by merseyV** [comment]
>you can't miss it on the readme page.

Lol ... I can't! Others try their best though? 🤣🤣

Like this .... instead of stuck between Casks & Distros? ....

**macOS:**

Download and install:

* Latest release: check [popcorn-time.site](https://popcorn-time.site/) or the repo's [releases page](https://github.com/popcorn-official/popcorn-desktop/releases)
* Or latest dev build (for testers): check the repo's [actions page](https://github.com/popcorn-official/popcorn-desktop/actions)  
* **Apple Silicon:** If you have Apple Silicon (M-series chips), you need to use the arm64 release. Apple Silicon apps are required to be signed and notarised with an Apple developer account. So it is necessary to manually remove the quarantine flag:

`xattr -c "/Applications/Popcorn-Time.app/"`

**Comment by dutchy1001** [comment]
@merseyV 
changes made on the readme file, still has to be "OKed" by devs as far a merge goes.
