### ISSUE TITLE
VPN completely blocking popcorn

### ISSUE THREAD

**Issue by Radiatorcap** [popcorntime/popcorntime#3033]
Hi, it's been like 2 weeks now, i cant load anything with my vpn on. Doest matter which country i'm chosing, as soon as the vpn is on, ratio/clients/seeds drops to zero. Dont really know why.. I'm using latest version of popcorn, 0.5.1 and nordvpn

**Comment by merseyV** [comment]
Have you contacted their help-desk ... https://nordvpn.com/contact-us/ , Nothing's changed here!

You can load with their VPN off?

Looks like something in your set-up changed 2 weeks ago .. maybe due to an update? Check out any Antivirus/Firewall/Security software you may be running?

**Comment by merseyV** [comment]
Have you contacted their help-desk ... https://nordvpn.com/contact-us/ , Nothing's changed here!

Can you can load with their VPN off?

Looks like something in your set-up changed 2 weeks ago .. maybe due to an update? Check out any other Antivirus/Firewall/Security software - you may have running?

**Comment by merseyV** [comment]
Have you contacted their help-desk ... https://nordvpn.com/contact-us/ , Nothing's changed here!

Can you can load with their VPN off?

Looks like something in your set-up changed 2 weeks ago .. maybe due to an update? Check out any other Antivirus/Firewall/Security software - you may have running?

**n.b:** You could try one of the free VPN's ... just for a quick+dirty comparison (make sure to use a p2p server?)

**Comment by merseyV** [comment]
Have you contacted their help-desk ... https://nordvpn.com/contact-us/ , Nothing's changed here!

Can you load with their VPN off?

Looks like something in your set-up changed 2 weeks ago .. maybe due to an update? Check out any other Antivirus/Firewall/Security software - you may have running?

**n.b:** You could try one of the free VPN's ... to eliminate (or not) Nord (make sure to use a p2p server?)

**Comment by merseyV** [comment]
Have you contacted their help-desk ... https://nordvpn.com/contact-us/ , Nothing's changed here!

Can you load with their VPN off?

Looks like something in your set-up changed 2 weeks ago .. maybe due to an update? Check out any other Antivirus/Firewall/Security software - you may have running?

You could try one of the free VPN's ... to eliminate (or not) Nord, as the issue? Make sure to use a p2p server.

**Comment by dutchy1001** [comment]
I have no issue when using my VPN (Privado) and get full speeds (depending on seed availability)
To me this looks like a "local" issue as @merseyV already said.

**Comment by merseyV** [comment]
>I have no issue when using my VPN (Privado) 

Now there's a coincidence? I was going to suggest it as the free (test) VPN .. if asked. **https://www.techradar.com/vpn/best-free-vpn**

FrootVPN does it for me - don't read too much into the name!! 🤣🤣

**Comment by merseyV** [comment]
>I have no issue when using my VPN (Privado) 

Now there's a coincidence? I was going to suggest it as the free (test) VPN .. if asked. **https://www.techradar.com/vpn/best-free-vpn**

FrootVPN does it for me - but don't read too much into the name!! 🤣 🤣

**Comment by dutchy1001** [comment]
I don't have the free version (but it's a nice option) as it comes as a package deal I had few years ago with my usenet provider😉😉.
I'm happy with them as I get full speeds on dl's

**Comment by dutchy1001** [comment]
As there is no further comments and presumed a local issue I will close this for now
