### ISSUE TITLE
App colors flicker and turn to 8bit

### ISSUE THREAD

**Issue by jastreb** [popcorntime/popcorntime#3059]
#### Operating System Version:

Windows 11 23H2
#### Popcorn Time Version:

0.5.1
#### Download date:

IN August this year due to Windows reinstall
#### Download url:

https://github.com/popcorn-official/popcorn-desktop/releases/tag/v0.5.1
#### Expected Behaviour:

Work normally as usual

#### Actual Behaviour:

Doing random graphical shenigans

#### Steps to reproduce the behaviour:

1. Open Popcorn Time
2. Download a Movie
3. It start flickering randomly and changing colors

#### Screenshot(s) of issue or error(s) logs of developer console (Windows/Linux: F12, MacOS: ⌘ + 0 ... then 'console' tab) (recommended):

![Screenshot 2024-11-18 011052](https://github.com/user-attachments/assets/9fef0d9f-cf01-4d56-ac10-b3a5b7877280)
![Screenshot 2024-11-18 013726](https://github.com/user-attachments/assets/1f675273-a9f0-4acb-bff5-0e95c1ada85b)

**Comment by dutchy1001** [comment]
Those are mostly issues with your graphics card or monitor, I don't think this has anything to do with PCT.
Only thing I can suggest to change the theme in the settings (Dutchy's Dark Orange maybe?? 😁😁) and see if that helps

There are also "high contrast" or "colour blind" settings in windows, check if those are still correct/default.

**Comment by merseyV** [comment]
>Download date:
>IN August this year due to Windows reinstall

When did this issue actually start ... straight after reinstall, or more recently?

**Comment by merseyV** [comment]
>Download date:
>IN August this year due to Windows reinstall

When did this issue actually start ... straight after reinstall, or more recently?

Which download (runtime version) are you using ... "0.44.5" or the other one?

Does issue disappear if you turn-off hardware acceleration?

**Comment by jastreb** [comment]
> > Download date:
> > IN August this year due to Windows reinstall
> 
> When did this issue actually start ... straight after reinstall, or more recently?
> 
> Which download (runtime version) are you using ... "0.44.5" or the other one?
> 
> Does issue disappear if you turn-off hardware acceleration?

It happened yesterday once as in I tried to launch it a few times and each time it was doing the same thing.

Unfortunately I do not remember if its 0.44.5 possibly it is, is there any way to tell which one is installed?

I dont know because after a reboot it was gone. I also messed with the Nvidia App and what I suspected that might cause this, its RTX Dynamic VIbrance and RTX HDR, its off now globally. Obviously its HDR monitor but what is weird is that while it was happening it happened only in PCT not in other apps.

I cant reproduce it now so idk what to make of it.

**Comment by merseyV** [comment]
>is there any way to tell which one is installed?

Only mentioned it because one contains a newer chromium version: 0.44.5 (in title) is the older chromium version. If issue has disappeared for now .. I can't see it being that?

It could possibly be some (recent) graphics settings change/update conflicting with the chromium version .. but I'm way out of my depth!! (being a Mac user)?

Two runtime versions:
* Popcorn-Time-0.5.1-win64-0.44.5-Setup.exe (older, has more audio codecs in PTapp default player).
* Popcorn-Time-0.5.1-win64-Setup.exe (newer 0.86.0 runtime, missing most dolby codecs in default player)

**Comment by merseyV** [comment]
>is there any way to tell which one is installed?

Only mentioned it because one contains a newer chromium version: 0.44.5 (in title) is the older chromium version. If issue has disappeared for now .. I can't see it being that?

It could possibly be some (recent) graphics settings/driver change/update conflicting with the chromium version .. but I'm way out of my depth!! ( being a Mac user :)

Two runtime versions:
* **Popcorn-Time-0.5.1-win64-0.44.5-Setup.exe** (older, has more audio codecs in PTapp default player).
* **Popcorn-Time-0.5.1-win64-Setup.exe** (newer 0.86.0 runtime, missing most dolby codecs in default player)

**Comment by merseyV** [comment]
>is there any way to tell which one is installed?

Only mentioned it because one contains a newer chromium version. 0.44.5 (in title) is the older chromium version. If issue has disappeared for now .. I can't see it being that?

It could possibly be some (recent) graphics settings/driver change/update conflicting with the chromium version .. but I'm way out of my depth here!!! ( me being a Mac user :)

Two runtime versions:
* **Popcorn-Time-0.5.1-win64-0.44.5-Setup.exe** (older, has more audio codecs in PTapp default player).
* **Popcorn-Time-0.5.1-win64-Setup.exe** (newer 0.86.0 runtime, missing most dolby codecs in default player)

**Comment by merseyV** [comment]
>is there any way to tell which one is installed?

Only mentioned it because one contains a newer chromium version. 0.44.5 (in title) is the older chromium version. If issue has disappeared for now .. maybe not relevant?

Could possibly be some (recent) graphics change/update conflicting with the chromium version .. but I'm way out of my depth here!!! ( me being a Mac user :)

Two runtime versions:
* **Popcorn-Time-0.5.1-win64-0.44.5-Setup.exe** (older, has more audio codecs in PTapp default player).
* **Popcorn-Time-0.5.1-win64-Setup.exe** (newer 0.86.0 runtime, missing most dolby codecs in default player)

**Comment by merseyV** [comment]
>is there any way to tell which one is installed?

Only mentioned it because one contains a newer chromium version. 0.44.5 (in title) is the older chromium version. If issue has disappeared for now .. maybe not relevant?

Could possibly have been a (recent) graphics change/update conflicting with the chromium version .. but I'm way out of my depth here!!! ( me being a Mac user :)

Two runtime versions:

**Popcorn-Time-0.5.1-win64-0.44.5-Setup.exe** (older, has more audio codecs in PTapp default player).
**Popcorn-Time-0.5.1-win64-Setup.exe** (newer 0.86.0 runtime, missing most dolby codecs in default player)

>(Dutchy's Dark Orange maybe?? 😁😁)  

Lol ... licence fees??

**Comment by dutchy1001** [comment]
So I presume this can be closed then as it cant be reproduced.

> (Dutchy's Dark Orange maybe?? 😁😁)

>Lol ... licence fees??

I get a cookie or shortbread for every one using it🤪🍪🤪🍪🤪

**Comment by jastreb** [comment]
> Popcorn-Time-0.5.1-win64-Setup.exe (newer 0.86.0 runtime, missing most dolby codecs in default player)

Since I dont have any audio with built in player it must be that one then. Thats why I download and then watch in VLC

> So I presume this can be closed then as it cant be reproduced.

Well I guess so until next time 👍

**Comment by merseyV** [comment]
>Since I dont have any audio with built in player it must be that one then.

Feature wise, since there's no major difference between the two versions: If it goes wobbly again .. try the 0.44.5 version, just out of curiosity?

**Comment by merseyV** [comment]
>Since I dont have any audio with built in player it must be that one then.

Feature-wise, since there's no other major difference between the two versions - If it goes "wobbly" again .. try the 0.44.5 version, just out of curiosity?

**Comment by merseyV** [comment]
>Well I guess so until next time 👍

You could always try the 0.44.5 version? Basically it has all the same features as the 0.86.0 version, just uses an older nwjs runtime. I suspect it might be the same with those Nvidia HDR options ... worth a punt?

**Comment by merseyV** [comment]
>Well I guess so until next time 👍

You could always try the 0.44.5 version? Basically it has all the same features as the 0.86.0 version, just uses an older nwjs runtime (+ custom codec set). I suspect it might be the same with those Nvidia HDR options ... might be worth a punt?

**Comment by merseyV** [comment]
>Well I guess so until next time 👍

You could always try the 0.44.5 version? Basically it has all the same features as the 0.86.0 version. It just uses an older nwjs runtime (and custom audio codecs). I suspect it might be the same with those Nvidia HDR options ... but may be worth a punt?
