### ISSUE TITLE
Please return Subtitle language droplist

### ISSUE THREAD

**Issue by WebShapedBiz** [popcorntime/popcorntime#311]
Hi.

I prefer my local language when watching movies or series. However quite often there is no subtitle available for my language or it's in poor quality, done with Google translate or out of sync. Then I'm switching to English subs.
Removing this, while creating no value at all, will cripple the whole experience using Popcorn Time.

Cheers.

**Comment by JimiC** [comment]
You can change the subs language from within the movie (when player starts the movie) , same as you do with TV series.

**Comment by WebShapedBiz** [comment]
Yeah, it seems so, I'm sorry for this but there is a line in CHANGELOG.md that says "Subtitles dropdown for movies has been removed (subtitles are fetched based on default subtitle language in settings)".

**Comment by JimiC** [comment]
Yes. I agree that this statement is kinda misleading but still it's correct.

Never the less though, when you start the movie, the app will search for a subs of the default lang you have set in settings. If subs are not found then the movie will play without any subs, but still you can select from available subs by clicking on the appropriate icon (speech icon) and an upwards dropdown list will appear.

**Comment by WebShapedBiz** [comment]
Thank you for your time and effort.

**Comment by JimiC** [comment]
@ChrisAlderson What's the label for? There is nothing to enhance. This issue should be closed.

**Comment by ChrisAlderson** [comment]
It's still something we want to bring back.

**Comment by Franck78** [comment]
Hello,
just add two new config lines for subtitles
1:  -none|prefered language
2 : -fallback (when 1 is not available)
3 : -fallback (when 2 is not available)

Another bunch of clics removed ;-)

**Comment by marcelorbenites** [comment]
When using Chromecast it is not possible to select the subtitles before or after starting the movie. Basically it is not possible to add subtitles when casting movies on Chromecast. That was a key feature that was removed and forces me to connect a HDMI cable and play the movie in VLC in order to add subtitles.

**Comment by Breaking1** [comment]
@marcelorbenites you need to set a default subtitle language in settings for subtitles to work on Chromecast. And if there are any subtitles available in the language you have set it will show when using Chromecast.

**Comment by marcelorbenites** [comment]
Thanks @Breaking1! It works. But since there is no option to change the subs language after starting the movie when using Chromecast when my preferred language is not available I would have to change my settings to a fallback language in a trial-and-error approach. @Franck78 suggestion is a great solution.

**Comment by Breaking1** [comment]
@marcelorbenites yeah i know what you mean, my workaround is to check what subtitles are available in the butter player, then i cast to Chromecast with one of the subtitles that are available and in a language i can understand.

I hope we get @Franck78 solution implemented it will save us some time and hassle when using Chromecast, it's at least better than no solution.

**Comment by vidra87** [comment]
There is a problem with the poor quality of the subtitles that Popcorn Time choose for some episodes and movies.
This problem will not be if the user will be able to choose the appropriate subtitle like in BS.Player.

**Comment by ancho85** [comment]
When streaming to Chromecast there should be an option to let me choose a different subtitle from opensubtitles or even use a local file. The reason was well described in the first post of this issue: _"However quite often there is no subtitle available for my language or it's in poor quality, done with Google translate or out of sync. Then I'm switching to English subs."_

**Comment by lucasshrew** [comment]
Also when streaming to a TV with DLNA there is not option to change the subtitles settings from the TV player.
+1 to bring back the dropdown in movie details.

**Comment by krulik** [comment]
Guys it makes no sense.
Let us choose or at least see whether there is a subtitle in my language. Now I need to start streaming the movie (which sometimes take as long as 10 minutes) only to find out that there's no sub and I need to look for another movie.
Checkout these discussions:
- https://www.reddit.com/r/PopCornTime/comments/5mgkhw/subtitles_gone_0310/
- https://www.reddit.com/r/PopCornTime/comments/5wjnln/subtitles_gone/

Look how many people are looking for a workaround. It's a crucial feature for international users.

Thanks for all the hard work

**Comment by germanoferreira** [comment]
I am trying to restore this feature. I just created a pull request to solve this. Maybe will be accepted
#1545
