### ISSUE TITLE
[Feature Request] Allow to keep seeding after show is closed

### ISSUE THREAD

**Issue by ki4jgt** [popcorntime/popcorntime#451]
Operating System Version:
Ubuntu 16.04

Popcorn Time Version:
3.10

Download date:
About 2 weeks ago

#### Expected Behaviour
No expected behaviour
...

#### Actual Behaviour
Problem is that there aren't enough seeds and there are too many peers. If one can choose in the options to seed things, then there would be more seeds per file.

**Comment by chtrinh** [comment]
@ChrisAlderson: I have a PR for this. But the strategy involves doing a `child_process.fork()` to spin up another instance of webTorrent. The hand off from player's webtTorrent to this other instance is through message passing via `child_process.send()`.  Is this an acceptable strategy? 

My initial stab at this locked up the UI thread on nwjs because when adding torrents to webTorrent client takes a lot of CPU cycles.

**Comment by WildYorkies** [comment]
I'm going to bump this. As a user, I would like to be able to choose to seed movies all of the time.  Ideally, there would be a section of the app that shows everything that you're seeding.

When you watch a movie, it gets added to your seeding library automatically, then you can manually de-select movies that you don't wish to seed anymore.

The main issue right now is that more obscure movies won't have enough seeders if they only seed at the time that they are watching it.

**Comment by trosel** [comment]
Digging through the advanced settings, does unchecking this setting achieve what this issue is about?

<img width="690" alt="2017-07-16 12_54_28-butter" src="https://user-images.githubusercontent.com/1299322/28250792-06b6a222-6a26-11e7-911d-856cf56fc9f3.png">
