### ISSUE TITLE
Cannot build latest release

### ISSUE THREAD

**Issue by benwaffle** [popcorntime/popcorntime#494]
Operating System: Linux

Popcorn Time Version: 0.3.10 or master
from https://github.com/popcorn-official/popcorn-desktop/releases/tag/0.3.10
or the master branch

Download date: March 4, 2017

---
When i run it, it gets stuck loading because `App.Providers.Generic.prototype.parseArgs` is undefined

**Comment by NicolasEhrhardt** [comment]
Origin of bug: https://github.com/butterproviders/butter-provider/commit/d1aa613cd5bbe0b863a82c9d79705e03c27801ac
And internal commit enforcing this dependency https://github.com/popcorn-official/popcorn-desktop/commit/1ecc3c0fb32dccf36786b4cb340e59e6a732e8cb
Since the butter-provider version is not pinned, this was predictable.

Reverting that change fixes it:
```
diff --git a/make_popcorn.sh b/make_popcorn.sh
old mode 100644
new mode 100755
diff --git a/src/app/lib/providers/generic.js b/src/app/lib/providers/generic.js
index 84c01ea..33a19a4 100644
--- a/src/app/lib/providers/generic.js
+++ b/src/app/lib/providers/generic.js
@@ -42,7 +42,19 @@
             return cache;
         }
 
-        var config = App.Providers.Generic.prototype.parseArgs(name);
+        var tokenize = name.split('?');
+
+        // XXX:reimplement querystring.parse to not escape
+        var args = {}
+        tokenize[1] && tokenize[1].split('&').map(function (v){
+          var m = v.split('=')
+          args[m[0]]= m[1]
+        })
+
+        var config = {
+          name: tokenize[0],
+          args: args
+        }
 
         if (cache[name]) {
             win.info('Returning cached provider', name);

```
