### ISSUE TITLE
Galaxy S7 Android 7 is not working

### ISSUE THREAD

**Issue by Serj1027** [popcorntime/popcorntime#496]
Version: 0.2.9
Download date: 06.03.2017
Android version:
7.0

Expected Behaviour

Work.

Actual Behaviour

It say that i'm using a wrong version of Popcorn time and it say that my device is not supported, but it's a Galaxy S7. On android 6.0.1 it works...

Steps to repoduce the behaviour

Open the app from a Galaxy S7 with Android 7.0
...
...

**Comment by Serj1027** [comment]
![17141494_1249467928468319_1459921127_n](https://cloud.githubusercontent.com/assets/23384432/23621528/bee51d8c-02a3-11e7-8b10-dfa4844ae229.png)

**Comment by syl3n7** [comment]
Yes, that happened to me as well, it seems that the app available for download from the site is in arm, and our processor is arm64, so what you need to do (if i am correct) is download the last stable version from ci.popcorntime.sh 
cheers.
ps. this issue is in the wrong place, you should've reported in here: https://github.com/popcorn-official/popcorn-android
edit: i saw you publish there too, but you should've just published in there.
i am moving this answer there. 
please someone close this issue
