### ISSUE TITLE
Agent's of Shield doesn't appear / Forums 

### ISSUE THREAD

**Issue by jonyroda97** [popcorntime/popcorntime#51]
Agent's of Shield doesn't appear on the official release but appears on community version.
Fix pls.
Wrong link to forum on https://popcorntime.sh/?

**Comment by Breaking1** [comment]
Just use Torrent collection and search for it with Kickass or Rarbg.

Drag/drop/copy/paste from your favourite torrent site should also work just fine, and since they haven't created any Discourse forum yet there isn't any link to put there, if they decide to ditch Discourse(Discuss forum) they will probably remove that link from the official site. For now you need to use https://www.reddit.com/r/PopCornTime/new/ for any support.

**Comment by jonyroda97** [comment]
thanks for the help :)
