### ISSUE TITLE
Breaking bad, bad peers and bad speed

### ISSUE THREAD

**Issue by choombdev** [popcorntime/popcorntime#514]
Operating System Version:

Windows 8.1

Popcorn Time Version:

Latest, 0.3.10
Download date:

A week ago, as a reinstall because my computer broke down
#### Expected Behaviour

Allow me to download the episodes with full potential speed like the previous episodes
...

#### Actual Behaviour

Download the episodes in less than 1/4 of my speed
...

#### Steps to reproduce the behaviour

1. I chose an episodes (4,5) of breaking bad  season 2 (haven't tried all episodes yet but all episodes after 5 are fine with 3+ peers and good connection speed)
2. waited and the first downloading screen isn't using my full speed and has only 1 peer-3 peers
3. takes hours to download 10%

**Comment by Yutsa** [comment]
Well it has nothing to do with Popcorn Time, it's just that Breaking Bad is getting kinda old, and old torrents tend not to have many seeders. Without seeders you can't download. It's the problem of the torrent technology.

And since you seed only when watching the episode when using Popcorn Time, there is not many seeders.

It really is a problem and we should implement auto-seed whenever popcorn time is open and not only when watching a file.

**Comment by streger** [comment]
Close this immediately! 
https://www.youtube.com/watch?v=JN99jshaQbY
