### ISSUE TITLE
Popcorn Time "Illegal Instruction" error output

### ISSUE THREAD

**Issue by frenchiveruti** [popcorntime/popcorntime#528]
Operating System Version:
PuppyLinux Tahrpup 3.0.5

Popcorn Time Version:
0.3.10 - x64

Download date:
16 apr 00:00

#### Expected Behaviour
Search for a title or switching to "TV Series" shouldn't close the app
...

#### Actual Behaviour
It closes the App and gives a console output with just the "Illegal Instruction" line, nothing more, **any way to track it?**
...

#### Steps to reproduce the behaviour

1. Open Popcorntime...
2. Click the search button ...
3. Success! Your app is now closed! ...

**Comment by streger** [comment]
Since your linux version is intended for small systems there can be many problems (missing stuff...)
It would be great to have you commit yourself to resolving this issue because those great linux versions like yours are always at fault of being in minority.
Any more info would be helpful, keep in mind we don't have time to setup your system for testing and also that you could possible commit code here if you find resolution.

**Comment by frenchiveruti** [comment]
Hello! Thanks for the answer, I wish I could provide more info but the thing is I don't know how, the console output it's just that what I stated before and nothing else.
Any suggestions on how to expand on the information for this?
I'm pretty sure is missing "something" important for the correct behavior of PopcornTime, but I can't trace what is it.
