### ISSUE TITLE
1080p too rare - have to manually get the 1080p from kat

### ISSUE THREAD

**Issue by ghost** [popcorntime/popcorntime#56]
1080p not available on most series and movies

what about 4k and 3d ?

**Comment by Breaking1** [comment]
You can just useTorrent collection and search for the quality you want with either KIckass or Rarbg inside PT, the option probably excist because of reasons like this. Hard to get everything users want with the API's that are available.

It's the folder next to your favourites, if it's not there just go to features in settings and activate it.

**Comment by ghost** [comment]
I wish software were architected as information and action flows rather than aligned to abstraction perceived limitations. In order to transcend the current knowledge and state of computer programming. API, Video quality, automation possibilities.

**Comment by ghost** [comment]
TV Shows is understandable as the current EZTV API used returns a lot of low quality shows, take a look at Breaking Bad for example. However most popular movies should always have a 720p and 1080p option, YTS.ag is fairly reliable atm.

**Comment by ChrisAlderson** [comment]
Popcorn Time has little control over the content. If this really is an issue (which is not) it should be on the [popcorn-api](https://github.com/popcorn-official/popcorn-api/).
