### ISSUE TITLE
Issue: Infinite Spinning

### ISSUE THREAD

**Issue by Piecito** [popcorntime/popcorntime#584]
Operating System Version:
Windows 10 Professional

Popcorn Time Version:
0.3.10 Beta, downloaded from .sh

Download date:
29th July, 2017

#### Expected Behaviour
Open the app and load Movies/Series/Anime

#### Actual Behaviour
The loading spinning wheel keeps spinning forever on Movies and Anime, for Series it shows API Failed to respond

#### Steps to reproduce the behaviour
It happens everytime I open the app

Steps I have tried:
1. I visited https://movies-v2.api-fetch.website/status, and it works on the browser
2. Disable antivirus (I have completely uninstalled it)
3. Completely deactivate Windows Defender
4. Firewall disabled, and rule for Popcorn was created

**Comment by HacKanCuBa** [comment]
Sometimes it happens on Linux, too. Usually it's *after a while* of being open, like more than 10 minutes or half an hour. This behaviour has been since I used it in Debian 8.

"Solution": close it and re-open it.

*Version*: 0.3.10-0 HEAD 28112f67  
*uname -a*: `Linux debian 4.9.0-3-amd64 #1 SMP Debian 4.9.30-2+deb9u2 (2017-06-26) x86_64 GNU/Linux`.

**Comment by HacKanCuBa** [comment]
It still happens to me some times :man_shrugging:
