### ISSUE TITLE
PT tries to connect to 195.22.28.198 (Ransomware site)

### ISSUE THREAD

**Issue by AndrejaN** [popcorntime/popcorntime#651]
Operating System Version:
 Ubuntu 16.04 installed on VM

![pt](https://user-images.githubusercontent.com/17863576/32404908-a25b12f4-c15a-11e7-8347-f1a067794b98.png)

Popcorn Time Version:
 Latest from the Source Code

Download date:
 3.11.2017 compiled from the source code

#### Expected Behaviour

... Show the movie and play, but not to connect on a Ransomware site first !!!!

#### Actual Behaviour

...When selecting a movie from the list it shows the movie BUT, PT tries to connect to 195.22.28.198 on random ports. MalwarebytesAnit-malware detects that this is a Ransomware site, so it blocks the sites, https://ransomwaretracker.abuse.ch/ip/195.22.28.198/
PT can play the movie not problem, but is should not connect to Ransomware site before that.

#### Steps to reproduce the behaviour

1. ...Install some firewall or Anti-malware blocking program like i have Malwarebytes Anti-malware Premium
2. ...Compile from the source and start the PT
3. ...Start PT, and select any Movie from the list, before it shows any information for the movie, the PT will try to connect to 195.22.28.198.

Please inspect this problem. Lucky i have run the compiled version only on Ubuntu 16.04 on VM and RasbianARM on my Pi3. So, probable no damage on my OS. Thanks!!

**Comment by Persei08** [comment]
I have checked a bit more the ip you reported, I am not an expert and I don't know exactly which sites are the best to check an ip reputation. 


https://ransomwaretracker.abuse.ch/ip/195.22.28.198/ : What can we see? 

- Ip is owned by [claranet](https://www.claranet.co.uk/) and is a managed services provider
- ip isn't listed by [Spamhaus SBL blocklist](https://www.spamhaus.org/sbl/),
- ip is/was used by different domains
- if you click all those domains, you can see more details and especially: they are not listed in [Spamhaus DBL](https://www.spamhaus.org/dbl/) and [SURBL](http://www.surbl.org/) blocklists.

If I [check Spamhaus SBL, XBL, PBL blocklists](https://www.spamhaus.org/query/ip/195.22.28.198): Not listed
If I [check on IBM X-Force Exchange](https://exchange.xforce.ibmcloud.com/ip/195.22.28.198), it seem safe since 2016-09-12

But I have tried too, installed virtualbox and Malwarebytes Premium Trial, set ubuntu 16.04 VM with dev environment and then compiled and ran PT. I got a warning for a different ip: 89.248.169.131 on port 53177 

[check Ransomware Tracker database for ip 89.248.169.131](https://ransomwaretracker.abuse.ch/ip/89.248.169.131/) :  nothing
[check Spamhaus SBL, XBL, PBL blocklists for ip 89.248.169.131](https://www.spamhaus.org/query/ip/89.248.169.131) : nothing
[check IBM X-Force Exchange for ip 89.248.169.131](https://exchange.xforce.ibmcloud.com/ip/89.248.169.131) : nothing

So, why exactly Malwarebytes is blocking those ips? Did they provides more details ? Is it really relevant?

**Comment by AndrejaN** [comment]
You are rigth. At this moment Malwarebytes reports 89.248.169.131 on port 53177. Probably Malwarebytes database changes too fast. I think that administrator can safely close this issue.
