### ISSUE TITLE
Subtitles issue

### ISSUE THREAD

**Issue by zappe** [popcorntime/popcorntime#682]
Operating System Version:
macOS 10.13.2

Popcorn Time Version:
3.10

Download date:
Not sure

#### Expected Behaviour
Show the correct subtitles

#### Actual Behaviour
Wrong subtitles

#### Steps to reproduce the behaviour
Watch the movie Alien Resurection

**Comment by zappe** [comment]
Actually it seems like a wider issue.
Subtitle in all shows/movies I watch is wrong. Seems to be the same subtitles no matter what movie/show I watch.

**Comment by gabrielbiel7** [comment]
i used to have problems with subtitles, but then i logged in to OpenSubtitles in Popcorn Time's settings and i don't have problems with wrong subtitles again.

**Comment by zappe** [comment]
@gabrielbiel7, didn't help unfortunately.

**Comment by gabrielbiel7** [comment]
sad :/ in mine is working when i log into open subtitles

**Comment by maruja99** [comment]
Having troubles with subtitles too, they didnt load at all, and in the case i can see the options they dont show up neither. Any idea what i can do to fix that?

**Comment by AstridDiepenbroek** [comment]
There are no subtitles at all in any movi or tv serie

**Comment by maruja99** [comment]
@gabrielbiel7 hi gabriel, how do u log into open subtitles? I saw u need an user and password, but cant find the site to create a new user, I keep having troubles with subtitles, so I would like to try that option.

**Comment by Persei08** [comment]
Subtitles are working with or without opensubtitles authentification.  
 
It's hard to help each of you without knowing your version number, OS, movie title, subtitles language defined in settings.

Subtitles are automatically downloaded from opensubtitles.org, they aren't always very good, because opensubtitles don't have all the subtitles for every single release, so the downloaded ones aren't always the best, they aren't always well synced with audio (you can use the G and H keys to adjust the subtitle offset, but it isn't always enough, framerate or cuts could be differents) and for foreign languages sometimes translations are bad.
Also keep in mind opensubtitles have a requests limit. If you reach it, it don't return subtitles list (opensubtitles auth, should increase a bit this limit BTW). If it happen, close the player frame, Wait 30s to 2min and relaunch the movie.

Tell us if it help you, else please provide more details.

Here a screenshoot showing subtitles working (I choose this frame so you will make nightmares :P )
![screenshot from 2018-02-01 13-51-33](https://user-images.githubusercontent.com/22459458/35679375-14c913e4-0757-11e8-9168-bdba4327f50a.png)

**Comment by zepoxnyan** [comment]
Subtitles still dont work as of 11th of February. I was trying to applay the fix someone mentioned under the commits, but i noticed that my Popcorn Time (Installed on windows 10, version 3.10) has a different streamer.js file under the src/app/lib

**Comment by gabrielbiel7** [comment]
as i said before, my subtitles work only when i’m logged into opensubtitles.com from the app. when opensubtitles site is not working, subtitles don’t show. i had just to enter in opensubtitles.com, create my account and then log in by Popcorn Time settings. if your PT subtitles even when logged into opensubtitles don’t show, i don’t know how to help anymore. :/

**Comment by jubial** [comment]
I´m also having troubles with subtitles in Popcorn Time (version 3.10, installed on windows 10) and no matter what movie i watch. Since some time ago, this month, they stopped showing up, although when i installed PT in last January subtitles were working ok, even without opensubtitles authentification. 
Now, even after creating an account in opensubtitles and logging in by PT settings, subtitles still don't show up. On the subtitles balloon, at the bottom of the player, they are shown as disabled and it's not possible to enable them (but they are enabled on the PT settings...). 
I forgot to say that my subtitles language is the portuguese, but i've tried with other languages, such as english or portuguese brazilean, but without better luck. It seems the same issue reported here before. 
Any idea to fix this?

**Comment by jubial** [comment]
I forgot to say that my subtitles language is the portuguese, but i've tried with others, like english or portuguese brazilean and it is the same.

**Comment by maruja99** [comment]
Operating System Version:
windows 7

Popcorn Time Version:
3.10 (build #254)

Download date:
I downloaded again on 01/31/2018

Expected Behaviour
Show the correct subtitles

Actual Behaviour
Subtitles doesnt show up, no matter which movie I try to watch

I registered in opensubtitles.com, but when I try to connect with it from popcorn it keeps 'working' and doesnt connect, and if I try a movie, subtitles are still disabled (and they re enable at settings) My language is spanish, but I tried with english too and it s the same.

Any ideas how to fix all this?

**Comment by Persei08** [comment]
[Opensubtitles.org was in maintenance this weekend](https://www.reddit.com/r/PopCornTime/comments/7wypir/subtitles_not_showing/).

When you think something don't work in PT, you can open the debug windows (F12 key) and select the console tab to check if there are some errors logged.

**Comment by zappe** [comment]
> When you think something don't work in PT, you can open the debug windows (F12 key) and select the console tab to check if there are some errors logged.

What do I press in macOS?

**Comment by mvanroon** [comment]
@zappe `F12`. Or `fn + F12` if you have keyboard function keys disabled.

Subtitles don't seem to be loaded when I stream to my DLNA device (samsung tv) nor do I have the option to select them. Tried restarting the movie, PT entirely and manually dragging the SRT in the PT window. Subs are automatically loaded when playing in the default player.
Subtitles are downloaded (srt file is being downloaded in cache folder) and console is showing no errors.

Default subtitle language is set to English.
Using 3.10.0 on OS X. Tried with and without opensubtitles credentials.
Movie was 'Lion'.

**Comment by danielzzz** [comment]
hello, for me subtitles are not working with latest builds. 

I had an older backup "28112f67852b" and this one works fine, but it has seeds/peers problem.
When upgraded that was fixed but the subtitles stopped working.
It's on ubuntu.

**Comment by PARIANOS** [comment]
I cannot adjust the subtitles with the voice..and there is not any button to do it

**Comment by danielzzz** [comment]
I've been playing with this a bit in order to find how to reproduce this problem but it seem very random.
The movie I'm watching is "In Time"
When going back to my old installation "28112f67852b", I noticed the subtitles were gone.
But closing the movie, then disconnecting opensubtitles and starting it againg brought them back.

Then going to the new install "28112f67852bb9fbf58fc1d0c1094a9c55f61119"
When starting the movie, I am getting almost inmediately the "no subtitules found" message. 
then sometimes (1/10) I can see the language list but the subtitles don't seem to be working or just some of them (in this case pt/pl/ru - sometimes).
For spanish I got a message about wrong timecodes once.

Hope this helps somehow to pin down the problem

**Comment by danielzzz** [comment]
@PARIANOS - try (shift) g/h

**Comment by Persei08** [comment]
@danielzzz 

Was working, but it seem there is an issue ATM with opensubtitles api. Not sure if temporary or what.

You can see the errors in debug window (F12 key) > console tab:

I have that:

```
app.js:21 [ERROR] subtitleProvider.fetch() Error: Unknown XML-RPC tag 'META'
    at Deserializer.onError (/home/persei/apps/Popcorn-Time-0.3.10_262_linux64/node_modules/xmlrpc/lib/deserializer.js:109:20)
    at Deserializer.onClosetag (/home/persei/apps/Popcorn-Time-0.3.10_262_linux64/node_modules/xmlrpc/lib/deserializer.js:202:14)
    at emitOne (events.js:96:13)
    at SAXStream.emit (events.js:188:7)
    at SAXParser.me._parser.(anonymous function) [as onclosetag] (/home/persei/apps/Popcorn-Time-0.3.10_262_linux64/node_modules/sax/lib/sax.js:258:17)
    at emit (/home/persei/apps/Popcorn-Time-0.3.10_262_linux64/node_modules/sax/lib/sax.js:624:35)
    at emitNode (/home/persei/apps/Popcorn-Time-0.3.10_262_linux64/node_modules/sax/lib/sax.js:629:5)
    at closeTag (/home/persei/apps/Popcorn-Time-0.3.10_262_linux64/node_modules/sax/lib/sax.js:889:7)
    at SAXParser.write (/home/persei/apps/Popcorn-Time-0.3.10_262_linux64/node_modules/sax/lib/sax.js:1293:13)
    at SAXStream.write (/home/persei/apps/Popcorn-Time-0.3.10_262_linux64/node_modules/sax/lib/sax.js:239:18)
```

**Comment by danielzzz** [comment]
it's been at least a week like that... maybe the interface changed?
or maybe there is some timeout set to get the subtitles (because I am always getting the "no subtitles found" almost inmediately, even though sometimes they apear when it gets to the movie itself.

**Comment by Persei08** [comment]
I don't know exactly :/, I just tried with dev build 262 and sometimes it work and sometimes it don't for the same movie. Maybe opensubtitles servers are suffering. They were in maintenance 30 minutes ago

**Comment by Leoxur** [comment]
Sorry for the OT. From where can I download the dev build? I'm with an old build o may 2017
When I go to the site i see this "ERR_CONNECTION_REFUSED"

**Comment by Persei08** [comment]
@Leoxur https://ci.popcorntime.sh/

**Comment by Leoxur** [comment]
![image](https://user-images.githubusercontent.com/9626769/37567171-67fee310-2ac3-11e8-88df-ff20938a439c.png)

I got this :( (adblock and ghostery disabled)

**Comment by Persei08** [comment]
@Leoxur look like you have a DNS issue, seem your ISP or network admin is blocking popcorntime.sh.
Use google dns (8.8.8.8, 8.8.4.4)

**Comment by Leoxur** [comment]
I already have the google dns, it's strange that this happens. On the phone I can access the site via VPN. It happens both with chrome and with other browsers (pc)

**Comment by Persei08** [comment]
What the command `nslookup popcorntime.sh` return?

**Comment by PARIANOS** [comment]
hi at th e button subtitles there are no subtitles..i need the greeks..can you help me?
 

    Στις 2:17 π.μ. Κυριακή, 18 Μαρτίου 2018, ο/η danielz <notifications@github.com> έγραψε:
 

 it's been at least a week like that... maybe the interface changed?
or maybe there is some timeout set to get the subtitles (because I am always getting the "no subtitles found" almost inmediately, even though sometimes they apear when it gets to the movie itself.—

**Comment by PARIANOS** [comment]
hi,at the button subtitles,there are no svbtitles..what can i do?i need the greeks

**Comment by Persei08** [comment]
In case it don't automatically show/load your subtitles language you can always search and download subtitles on the web (on opensubtitles.org or subscene.com) and then add it by choosing "Custom ..." in the subtitles list

**Comment by maruja99** [comment]
@danielzzz thank you soooooooo very much for the comment about how to sync up the subtitles!!!! (it was on March 17th, but it soooo helped me now)

**Comment by speedycoyote** [comment]
Hi,
The subtitles do not open on my TV, only on computer
And when I open the movie for the first time, the subtitles open, but if I want to see the movie again, they don't appear anymore.
I have sign in to opensubtitles.org
Is everything more that I need to do?
Thanks
