### ISSUE TITLE
Episodes not playing - error message

### ISSUE THREAD

**Issue by makhtar12** [popcorntime/popcorntime#700]
Operating System Version: OS X 10.13.3 

Popcorn Time Version: O.3.10

Download date: 11th February 2018

#### Steps to reproduce the behaviour

1. Open Altered Carbon tv series
2. Select episode 2 - Fallen angel
3. When attempting to play, error message appears
<img width="1280" alt="screen shot 2018-02-12 at 13 41 25" src="https://user-images.githubusercontent.com/36410433/36099402-734247a0-0ffa-11e8-93b2-8b526973312a.png">

**Comment by Persei08** [comment]
Have you tried to restart PT and retried ?
I got this few day back and restarting PT solved it.

**Comment by rawsp33d** [comment]
~~I have the same issue. And no, restarting did not fix it.~~

Update:  Surprisingly, restarting PT a bunch did actually fix it.  It was on the fifth or sixth time.

**Comment by Persei08** [comment]
> Surprisingly, restarting PT a bunch did actually fix it. It was on the fifth or sixth time.

Now I think to it, I think I restarted PT 2 or 3 times to remove that error.

**Comment by makhtar12** [comment]
I've tried repeatedly closing popcorn time and reopening. But not made the slightest difference. Still getting the error message :(

**Comment by tr0yspradling** [comment]
Why is this issue closed? This bug is still affecting users, including myself. The only fix that worked for me is coping `libffmpegsumo.so` to the `/usr/share/popcorntime` & `/usr/share/popcorntime/lib` folders. Not sure which folder the library is being loaded from so I copied to both folders. This worked for a few days, however this error message that the video can't be loaded has popped up again, on ALL videos I try to watch. It's an application-wide error, not specific to any media.

**Comment by paulovieiraa** [comment]
I've the same problem yet !

**Comment by davidpaley** [comment]
I have the same problem.

Operating System Version: OS X 10.14.1
Popcorn Time Version: O.3.10

**Comment by trosel** [comment]
This error is not in the popcorn time source code. But it is being populated in the `vjs-error-display` element.

Perhaps it's being piped through the below?

https://docs.videojs.com/errordisplay
https://docs.videojs.com/error-display.js.html#line48
