### ISSUE TITLE
[Request] Portable

### ISSUE THREAD

**Issue by zero77** [popcorntime/popcorntime#710]
Can you please make a portable version that you can run on any desktop without any installation.
Thanks

**Comment by Persei08** [comment]
>on any desktop without any installation

Sound like a massive task. How do you think it should be done ? 

One way I can think it could be achieved, is to rewrite everything in Java and it will require machines to already have java installed and more important, lot of time.
And the other way is to make multiples portables versions (for each OS and arch) and mod them to share the same download folder, cache and config files, and the user will have to choose which one to use. 
But both way seem to require lot of times for few benefits.

Just my 2 cents, maybe someone know/have better idea.

**Comment by Persei08** [comment]
Time have passed since this request but if you're interested by how to have a portable version of PT for windows, you can follow those explanations: https://www.reddit.com/r/PopCornTime/comments/btfxm7/portable_version/eozrj5m/

I guess a linux version could be also done similarly but I can't really tell for OSX (i don't use this os)
