### ISSUE TITLE
Bollywood movie category on PopcornTime

### ISSUE THREAD

**Issue by TinyOutsider** [popcorntime/popcorntime#719]
What is the possibility of adding Bollywood (Hindi) movie category? Since all movies are coming from torrents, and there are hundreds of Bollywood movies made each year. There is definitely a lot of demand for it.
Is there any way we can help with it?
Thanks.

**Comment by iMansoorAliKhan** [comment]
It would be great to have good, HD Bolly movies here.
Kudos from me.....

**Comment by Persei08** [comment]
Will be great.

**Comment by Persei08** [comment]
1337x.to have a [bollywood category](http://www.1337x.to/sub/73/0/). Look like it could be linked with trakt.tv and imdb and tvdb have some data too. I don't know if opensubtitles.org is good enough for bollywood movies (site in maintenance ATM).

Maybe there are better websites to relies on, but it could be a start if someone want to try.

**Comment by TinyOutsider** [comment]
Thanks for the research @persei08 now how do we try to implement this into PopcornTime. Is there any dev who will start work on it (coz personally I’m not a coder but I can help with designing things).

**Comment by Persei08** [comment]
>how do we try to implement this into PopcornTime

@ChrisAlderson , @team-pct, what do you think of this idea ? Do you think it's important if audio is not english (hindi / tamil / telegu)? Do you think it is better to implement as a category or a tab ? 

>Is there any dev who will start work on it (coz personally I’m not a coder but I can help with designing things).

I think PT devs are focusing on maintaining the app instead of adding new features. 
I will dig a bit deeper, but don't considerate that as a promise that I will do it. If some coders are interested, the first step is modding the [popcorn-api](https://github.com/popcorn-official/popcorn-api) to scrap 1337x.to bollywood category, filter not lightweight (and dead torrents?) and return hindi movies in a similar way it is done for other movies.

No new design are needed, it's already done

**Comment by TinyOutsider** [comment]
Sounds good.

**Comment by TinyOutsider** [comment]
So any updates on this..! anyone.

**Comment by TinyOutsider** [comment]
Has anyone done more research on this. Would be great to see some Bollywood movies.
