### ISSUE TITLE
Popcorn Time no subtitles when streaming to tv

### ISSUE THREAD

**Issue by DhooreBE** [popcorntime/popcorntime#782]
Operating System Version:
Windows 10

Popcorn Time Version:
3.10

Download date:
05/10/2018

#### Expected Behaviour
Show the subtitles when streaming to tv or with dlna in general.
...

#### Actual Behaviour
not showing the subtitles.
...

#### Steps to reproduce the behaviour

1. Is it only me who doesn't has subtitles when streaming to my samsung smart tv. When streamimg on my pc it does show the subtitles. 
2. Do i have to enable it somewhere?
3. It used to work

**Comment by valdineifer** [comment]
This is happening to me too. I had to watch on my computer.

**Comment by Persei08** [comment]
Any debug console output ? (F12 key)

**Comment by speedycoyote** [comment]
Hi,
This is happening to me also
And, when I open the movie for the first time, the subtitles open (but only in computer), but if I want to see the movie again, they don't appear anymore.

**Comment by CViniciusSDias** [comment]
Why was this closed?

**Comment by CViniciusSDias** [comment]
I still have this problem. :'(

**Comment by Persei08** [comment]
At some point all issues were closed... to clean a bit or something else. The problem is there is too much unnecessary issue reports and it just add noise and make it difficult to find the real issues. So at some point everything was closed, even legit issues (which i think some were reopened later). :/.

But I just seen you opened a report #1495 for it, so I will not reopen this one. Thx
