### ISSUE TITLE
popcorn wont start, keeps on loading without any result, i tried re-installing it without any better result afterwords

### ISSUE THREAD

**Issue by NicolaeAlexandruCiucas** [popcorntime/popcorntime#787]
Operating System Version:

Popcorn Time Version:

Download date:

#### Expected Behaviour

...

#### Actual Behaviour

...

#### Steps to reproduce the behaviour

1. ...
2. ...
3. ...

**Comment by christian130** [comment]
please would you mind to acknowledge this issue your OS, your platform along with the NODE and NPM version, and also the branch where you're trying to build it

**Comment by jaschavd** [comment]
i have the same problem on os and on windows

**Comment by NicolaeAlexandruCiucas** [comment]
pc, win10 about NODE and NPM i have no idea how to provide you with that to
be honest i could use some help about that, ive attached a screen shot with
the error that im getting, thank you in advance!

**Comment by Persei08** [comment]
if you're stuck with the blue spinning loader icon, it's because you can't connect to the PT APi, which is probably because you use your ISP DNS and for some reason they have blocked PT API domain.

Using better DNS like Cloudflare DNS (1.0.0.1, 1.1.1.1) or Google DNS (8.8.8.8, 8.8.4.4) should help you.
