### ISSUE TITLE
MPC-BE icon error on player select

### ISSUE THREAD

**Issue by GameBurrow** [popcorntime/popcorntime#814]
**Operating System Version:**
Windows 10 Pro x64

**Popcorn Time Version:**
0.3.10 - HEAD 28112f67

**Download date:**
Who remembers that?

#### Expected Behaviour
When you choose a player, It would show the icon like MPC-HC and VLC does.

#### Actual Behaviour
It shows missing img icon instead
![image](https://user-images.githubusercontent.com/4341091/42021928-97e1b02a-7ac4-11e8-9eaf-24d8e7c42c1f.png)

#### Steps to reproduce the behaviour
1. Install Media Player Classic - Black Edition (MPC-BE x64)
2. Open a film/show
3. Right click on the player select

**Comment by ikenbe** [comment]
In Windows(since MPC-BE64 is windows only): Under your user folder, open "AppData\Local\Popcorn-Time\src\app\images\icons" and you will see all the icons for player. Make anyone you like a copy and name it "external-mpc-be-icon.png", or use your own image as an icon. Restart PT then it should be working.

![annotation](https://user-images.githubusercontent.com/2187046/45379730-b8446c00-b5b5-11e8-8e57-ab8b8e90f849.png)
