### ISSUE TITLE
Remove The Anime And Indie Tab

### ISSUE THREAD

**Issue by GKid94** [popcorntime/popcorntime#823]
Can you please remove the Anime and Indie tab and merge them with the Movies and Series Tab, for example add Anime and Indie movies and series in the Movies and Series tab so that you have all the movies and series in those 2 tabs

**Comment by Persei08** [comment]
it's lot of works, and i'm not sure most people will like that :|

**Comment by MarioGreen** [comment]
you have already added 2 check-boxes to hide anime and indie tabs, which btw are not working and if you open settings again the boxes are unchecked

**Comment by Persei08** [comment]
@MarioGreen the 2 checkboxes are just here for hiding tabs (indie or anime). 
But the "lot of work" is more about merging tabs, because actually the API can return movies or series or animes or Indie (Indie use a different api) but isn't designed to return movies and indies or anime and series together. You can potentially do that by doing 2 request to api (one for movies and one for indies) and doing some treatment in PT client but it will require some changes.

**Comment by MarioGreen** [comment]
What I tried to say is that the checkboxes are not hiding anything (am using Windows version 0.3.10-0 Beta). 
On the other hand, I personally, don’t think you should merge indie and anime with the rest. Keep as is or make it an option.

**Comment by Persei08** [comment]
@MarioGreen oh ok, it was already reported: https://github.com/popcorn-official/popcorn-desktop/issues/401
