### ISSUE TITLE
Almost the inteire season 1 of YOU is incorrect on Popcorn Time. Someone uploaded another TV show instead of YOU.

### ISSUE THREAD

**Issue by maynaramartins** [popcorntime/popcorntime#835]
Operating System Version: Windows 07 - Linux
 
Popcorn Time Version: 0.3.10-0

Issue: The entire season (but the pilot) of "YOU" was incorrectly uploaded. Someone put another TV show instead of YOU.

**Comment by maynaramartins** [comment]
Please, someone solve this problem

**Comment by kiriles90** [comment]
Popcorn Time doesnt host/upload any content only indexes it. Series are from eztv.ag and you are right they messed something up -> https://eztv.ag/shows/3008/you/
But, no other episodes of 'You' aired yet only the pilot -> https://en.wikipedia.org/wiki/You_(TV_series) so lets just wait and see what happens when ep2 airs.

**Comment by maynaramartins** [comment]
Ok, thanks. The 2nd episode will air tomorrow night (15/09/2018) can't wait

Em 15 de set de 2018 12:18, kiriles90 <notifications@github.com> escreveu:

Popcorn Time doesnt host/upload any content only indexes it. Series are from eztv.ag and you are right they messed something up -> https://eztv.ag/shows/3008/you/
But, no other episodes of 'You' aired yet only the pilot -> https://en.wikipedia.org/wiki/You_(TV_series) so lets just wait and see what happens when ep2 airs.
