### ISSUE TITLE
Collaboration with Nuclear

### ISSUE THREAD

**Issue by DonaldTsang** [popcorntime/popcorntime#851]
https://github.com/nukeop/nuclear could be a possible sister project to Butter/PT, and it would be great to give them some assistance, or possibly integrate the functions into Butter/PT

**Comment by RITACOUTO** [comment]
Thanks for answering me. But I could not understand. I am a 66 year old girl who loves the internet, loves POPCORN TIME, but I do not know how to do these processes that you do. It's too complicated for me to do. You could teach me ? How to put subtitles in Portuguese BR? Forgive me for any wrong word because I'm using an online translator.
Hugs


________________________________
De: Donald Tsang <notifications@github.com>
Enviado: terça-feira, 16 de outubro de 2018 07:38:33
Para: popcorn-official/popcorn-desktop
Cc: Subscribed
Assunto: [popcorn-official/popcorn-desktop] Collaboration with Nuclear (#851)


https://github.com/nukeop/nuclear could be a possible sister project to Butter/PT, and it would be great to give them some assistance, or possibly integrate the functions into Butter/PT

**Comment by DonaldTsang** [comment]
@RITACOUTO sorry can't help you

**Comment by DonaldTsang** [comment]
@team-pct Any comments on adding music support?

**Comment by team-pct** [comment]
Hello,
We would love to do that we do not have the dev to do so ! 
Sorry guys !

**Comment by DonaldTsang** [comment]
@team-pct perhaps give the Nuclear developers for help and collaboration?
