### ISSUE TITLE
Popcorn-Time shuts down/kills my internet connection completely.

### ISSUE THREAD

**Issue by tnmygrwl** [popcorntime/popcorntime#862]
Operating System Version:
macOS Mojave 10.14 (18A389)

Popcorn Time Version:
Version 0.3.10 (0.3.10)

#### Expected Behaviour
I want it to show me "no results found" for something that doesn't exist in the database.

#### Actual Behaviour
It gets stuck on the loading screen and **shuts down my internet completely**. I can confirm that the internet goes down due to Popcorn Time and not something else, I tested it more than a couple of times.

#### Steps to reproduce the behaviour

1. Go to the "Movies" section (my default is "TV Series").
2. Search for a non-existent movie
3. Make sure the search query is unique every time you test it.

#### Additional Details that might help:
1. [This is my router](http://www.dlink.ru/mn/products/3/2178_b.html).
2. I got a 40Mbps connection.
3. A reddit [thread](https://www.reddit.com/r/PopCornTime/comments/4mu3cx/popcorn_time_kills_my_internet_connection/) that discusses this issue.

**Comment by Persei08** [comment]
Not sure if clear or not, but if it doesn't show "no result found" and is stuck on loading screen, it's because PT don't get the response from API, because your internet connexion is crashed. 
Some improvements can probably be done here but I don't think it will avoid your connection to crash.

- Do you use or have you tried with a VPN ?
- Do you have this issue when using another router model/brand ?
- Have you tried by using unfiltered DNS (on) ? Google DNS (8.8.8.8, 8.8.4.4) or Cloudflare DNS (1.0.0.1, 1.1.1.1). Especially because your router seem to have a "Built-in Yandex.DNS web content filtering service" feature, or because ISP can 
- What if you open this url from your browser ?: https://tv-v2.api-fetch.website/movies/1?sort=rating&order=-1&genre=all&keywords=opopo (This is the api url used for search).
Does it crash your internet ?
- What is your value for "Connection Limit" option in PT advanced settings ?
