### ISSUE TITLE
Update to VideoJS 5X

### ISSUE THREAD

**Issue by team-pct** [popcorntime/popcorntime#96]
- Update to VideoJS 5.x 
- Update Video.js Youtube Plugin

**Comment by z11h** [comment]
What are the changes needed to be made to have everything working?

**Comment by team-pct** [comment]
bower.son Update to videoJS version ,
there is issues with Videojshooks.js and plugins on src/app/vendor that is not compatible video.js 5x i guess we need update all component

**Comment by ChrisAlderson** [comment]
Tried it on the [`legacy`](https://github.com/popcorn-official/popcorn-desktop-legacy/tree/videojs) version and got pretty far (I think). The issue is with the srt subtitles which are not supported by VideoJS. I was also unable to override the `TextTrack` class which handles the loading of the subtitles.

**Comment by marcomontani** [comment]
I'd like to help here, since i actually need this upgrade. 
is there a branch with some work done or should i start from scratch?

**Comment by team-pct** [comment]
Some work was done here , but i think you should go from scratch 
https://github.com/popcorn-official/popcorn-desktop-legacy/tree/videojs

If you wanna start from scratch i suggest you to use directly https://github.com/butterproject/butter-desktop Fork and work on master then send PR there

**Comment by team-pct** [comment]
Upgraded to video.js 7 

Skin need remake
