### ISSUE TITLE
[FR] Add "Toggle subtitles" keyboard shortcut

### ISSUE THREAD

**Issue by ImAnnoying2** [popcorntime/popcorntime#966]
Operating System Version:

All
Popcorn Time Version:

0.3.10
Download date:

07.08.2018

I suggest adding a keyboard shortcut that toggles subtitles on and off, like in VLC. Manually choosing to play videos in VLC is detrimental to the overall "all-in-one" user experience...

**Comment by Fantomas4** [comment]
I would like to give this a try! I will post here if I manage to come up with a proper solution.

**Comment by kiriles90** [comment]
A keyboard shortcut like VLC's 'v' that cycles through the available subtitles isnt really great for Popcorn Time. VLC assumes its dealing with local subtitles that's why it has this function while in Popcorn Time you download each sub as you click the language in the player menu, meaning (especially now with multiple subtitles per language) you would have to download like 30 unnecessary subtitles until you get to 'English' or 'French 3' or whatever if you are trying to reach there by cycling through them. Using the mouse to accomplish the same thing (like it is now) is a lot  'cleaner' imo.

@Persei08 thoughts? (also maybe close if you agree that this doesnt really have a good solution)

**Comment by Persei08** [comment]
I don't know. For me what he is asking isn't a shortcut to cycles through subtitles but more something to disable and re-enable them.

I think @ImAnnoying2 should clarify what he want

**Comment by kiriles90** [comment]
@Persei08 hmm well if its just that then forget the issue in my previous comment. Though.. still maybe a bit pointless in Popcorn Time's usage? If you guys think otherwise though I can check to see if I can make a PR.

**Comment by Persei08** [comment]
yeah I wonder if having a keyboard shortcut for that is really useful, because you can disable subtitles in 2 clicks or you can choose to not enable subtitles by default and then enable them when playing in 2 clicks :/ .

In fact i don't see why someone should disable or enable subtitle often. So if @ImAnnoying2  don't provide more infos, I think we will close it until someone ask again

**Comment by dutchy1001** [comment]
I agree here with @Persei08 you either have subs on or off. 

Does PCT have the option to change the the speed (in milliseconds) to let the subs go faster or slower when their out of sync?
That would be the only reason for me to turn subs off  if that option is not build in. I do use subs all the time with an external player that does have this option (it also let me change the subs if I have a "better" file (see my last comment at #1540 were I explain this)).

**Comment by kiriles90** [comment]
@dutchy1001 You mean [this](https://user-images.githubusercontent.com/38388670/94953164-bd9fe680-04ef-11eb-9cd3-67321d35bdf9.PNG) ?

>  (it also let me change the subs if I have a "better" file (see my last comment at #1540 were I explain this)).

Now is https://github.com/popcorn-official/popcorn-desktop/issues/1332 and yeah, that would be a nice feature to have.

**Comment by dutchy1001** [comment]
> @dutchy1001 You mean this ?

Yea, I just went to the list of issue e-mails were this was answered lol

> Now is #1332 and yeah, that would be a nice feature to have.

When using an external player it is not up to PCT to implement that, that is the external players job, like I mention in #1540 . 
If you want something like that implemented into PCT then that is up to you guys.

**Comment by kiriles90** [comment]
Its pretty much the same mechanism though, if Popcorn Time can inject a subtitle in the stream while using an external player, its pretty much the same thing to do it for when casting. The user also see's the same thing in PCT, the loading screen.

**Comment by dutchy1001** [comment]
> if Popcorn Time can inject a subtitle in the stream while using an external player

When using the external player, in my case SMPlayer, the SMPlayer is connecting to Opensubtitles.org if I want to change the subs not PCT, so when changing the subs it's not injected from PCT anymore.

After starting the player, I presume this is streaming, there is no option in PCT to change subs unless you restart the movie.

When casting you will have your Android phone/tablet or pc/linux/mac to cast it to (most likely) a tv, meaning you still have your casting device were you can change settings, if there are any (almost like a remote control then). 

Am I thinking to far now or do I make sense?? (after all it's Friday, I need a drink)

**Comment by kiriles90** [comment]
Yy I get it but that only because SMPlayer has the feature to connect to opensubtitles, some players dont. Having the option in PCT of changing (or adding) the subtitle in the external player without restarting the movie would be a nice feature to have.

> After starting the player, I presume this is streaming, there is no option in PCT to change subs unless you restart the movie.  

As it is no. But it can be done, the native player does it. Depending on the implementation some ext. players make take issue with it but I think its possible, e.g there used to be something that pretty much did this for chromecast when you drag&dropped a sub in the UI. The 'casting' code and 'use ext. player' code is very similar in Popcorn Time, and they both get served the same local stream. So what works for one would mostly work for the other too. Same UI and everything too.

Anyway, it might be possible but nevertheless its not a small job so.. goes on the shelf for now unless someone wants to start working on it.. :)
