### ISSUE TITLE
Implement FFsubsync

### ISSUE THREAD

**Issue by georgiai1** [popcorntime/popcorntime#977]
Operating System Version:
Windows 10
Popcorn Time Version:
Latest
Download date:
02.25.2019
#### Expected Behaviour
Expects subtitles to be in sync https://github.com/smacke/subsync

#### Actual Behaviour
Subtitles are messed up and have to manually sync them

#### Steps to reproduce the behaviour
1. Launch application
2. Choose any movie/series
3. Choose Bulgarian subtitles

**Comment by Persei08** [comment]
Could be a killer feature. Maybe to use with another subtitle file as reference (will require to automatically grab one with perfect match / best score) since the video isn't completely downloaded when PT start to play it... or maybe could be used on a partially downloaded video and relaunched in background at some interval (will require a video reload on chromecast).

Interesting.
