### ISSUE TITLE
Add database of documentaries from VideoNeat.com

### ISSUE THREAD

**Issue by tiotrom** [popcorntime/popcorntime#979]
I am in charge of VideoNeat.com where we curate science documentaries and lectures and we help seed them. We add a cover for each and a trailer whenever possible. We do not have an API but can we work together on somehow adding the gallery to Popcorntime? I think Popcorntime really lacks documentaries and we curate documentaries since 5 years ago.

**Comment by Persei08** [comment]
I'm not part of PT team, but I just take a look at your site. I can be wrong, but I think PT team focus on HD light releases and giving choice between 720p and 1080p (and also 480p for series).
Some magnets I checked on your website have bigger size than usual 1080p in PT. Also, it seem the number of peers is a bit low and the optimal download speed (to watch a video without too much buffering) can't be reached.

This said, first install the PT API and custom PT to use your forked API instead of official one, you will understand better how it works. 
Then you will have to mod the API to get the necessary data from your website (and eventually retrieve additional data: IMDB/TVDB ids, covers, ratings, trailers), filter no lightweight (and dead torrents?). But you should choose if you return results in movie api mixed with existing results, (meaning you should probably check if it's relevant to use your magnet links or the already existing ones based on peers number and file size for exemple) or a dedicated "documentary" api which will also require to implement a documentary tab in PT (which will be basically a customized movie tab).

Then, eventually share your custom PT app and send pull requests so dev can review them and see if they find it useful to include in official version.

**Comment by kiriles90** [comment]
@Persei08 not an issue, close please

**Comment by Persei08** [comment]
I close because it's old enough and no feedback were given. 

@tiotrom you should run your own api to start with, check "popcorn-api" project (or eventually "popcorn-ru api" if your more familiar with php/symfony) then it can be relatively more easy to add a documentary tab which request your api.

**Comment by tiotrom** [comment]
Thank you for the feedback guys! Unfortunately I do not know where to start with this...all I know is to make sure proper good documentaries/courses are available via BitTorrent (seed them, add a proper description, timestamp, and all that). If Anyone comes across this post and can help us come up with an API for VideoNeat I am all eyes and ears. Cheers!
