### ISSUE TITLE
Audio/Video gradually go out of sync

### ISSUE THREAD

**Issue by MyKaleka** [popcorntime/popcorntime#994]
Operating System Version:
Windows 10

Popcorn Time Version:
0.3.10 "Popcorn is Love" Beta Popcorntime.sh version

Download date:
01/03/2019

#### Expected Behaviour
Play audio and video in sync
...

#### Actual Behaviour
Video and audio go out of sync after about 15-30min of watching. Happens for both TV series episodes and movies (happens on both VLC and butter).
...

#### Steps to reproduce the behaviour

1. Start a video
2. Wait for a few minutes - anytime from 15-30min
3. Audio then desyncs from video.

One workaround I've been using is to pause the video for a few minutes - the audio and video go back in sync once the video is resumed. However, the problem often returns later. Is there any permanent fix to this problem? It seems to me that this issue has been raised a lot in previous posts and on the internet in general but I can't seem to see a solution anywhere.

Thanks in advance

**Comment by Persei08** [comment]
Since you said it also happen with VLC and when you pause the video for few minutes everything go back to normal, I think it's related to your system, like your pc is struggling to decode audio or video... and it's more visible with time.

Maybe check graphic/sound settings in your OS, try with AC Power Adapter plugged in and energy saving mode set to "performance" (or "gaming" mode), also maybe check a software isn't slowing your pc (antivirus, live protection scanning the downloaded file, ...).


>It seems to me that this issue has been raised a lot in previous posts and on the internet in general but I can't seem to see a solution anywhere.

[sound desync is pretty common issue not exclusive to Popcorntime](https://www.google.com/search?q=sound+desync)

**Comment by kiriles90** [comment]
@Persei08 not a Popcorn Time issue, close please?
